### ISSUE TITLE
Bar Explicit Size doesn't work

### ISSUE THREAD

**Issue by farshadmb** [uias/Tabman#100]
@msaps i found another issue with your library
appearance.layout.height = .explicit(value:20.0)
doesn't work. check if contentSize.height bigger than explicit value

we need to investigate that what happened.

Best Regard

**Comment by msaps** [comment]
@farshadmb what appearance/bar configuration were you using? I'll have a look and see what I can find out 👍

**Comment by farshadmb** [comment]
@msaps I used custom RTL font and buttonBar Style

**Comment by msaps** [comment]
Having investigated I think the behaviour of explicit sizing works as designed.. 

A `TabmanBar` will not compress it's contents to a height that will compromise the constraints of the items it contains, therefore when setting a height smaller than this, it will use the minimum available intrinsic height. 👍

**Comment by wxxsw** [comment]
Why is the minimum height 40? Hope can change TabmanButtonBar.Defaults.minimumItemHeight.
