### ISSUE TITLE
Content is not appearing on full width

### ISSUE THREAD

**Issue by krishnameena** [uias/Tabman#101]
Some time when we swiping views to left right than content of current view controller is not appearing on full screen width but small part of second view controller's content is overlapping it. how can I remove this behaviour ??

![simulator screen shot 24-jun-2017 12 10 13 pm](https://user-images.githubusercontent.com/10487399/27506488-413c3cec-58d6-11e7-9875-9caa84733c87.png)

**Comment by msaps** [comment]
@krishnameena  That certainly looks strange, is there any chance that the content view in your second view controller is positioned outside of the view bounds?? Or is the page width actually smaller than the screen bounds?

Try setting `clipsToBounds = true` on your view controller's `view`?

**Comment by krishnameena** [comment]
Thanks `clipsToBounds = true` it worked 👍
