### ISSUE TITLE
Tab bar style .blockTabBar is not working properly

### ISSUE THREAD

**Issue by krishnameena** [uias/Tabman#102]
When I am setting tab bar style to `.blockTabBar` than text size automatically becomes very small and Tab bar also becomes of fixed width how can I make tab bar to scrollable as it was in `.scrollingButtonBar` style??

![simulator screen shot 24-jun-2017 12 24 47 pm](https://user-images.githubusercontent.com/10487399/27506571-38c81a66-58d8-11e7-8eda-f35c85567f3e.png)

**Comment by msaps** [comment]
By design, the `.blockTabBar` style isn't scrollable, only the `.scrollingButtonBar` style provides a scrolling behaviour. I am wanting to improve the styling capabilities, but this will probably not happen until the component reaches a bit more maturity. 

I will check out the issue with the label sizing though, as that does seem ridiculous!

**Comment by msaps** [comment]
@krishnameena would you be able to confirm which version of `Tabman` you were using when you saw the above behaviour? Can't seem to reproduce the label scaling problem on the current (`0.7.0`).

**Comment by krishnameena** [comment]
I was using version 0.6.0

**Comment by krishnameena** [comment]
How can I update it to version 0.7.0

**Comment by msaps** [comment]
@krishnameena if you're using CocoaPods, simply run `pod update Tabman` in your repo. Or if you're using Carthage, run `carthage update --platform iOS`.

**Comment by krishnameena** [comment]
I have updated it to version 0.7.0 and still same issue facing. Please add around 10 Tab bar items, probably than you will be able to reproduce the issue.

**Comment by krishnameena** [comment]
I am still facing same issue. If I select style as `blockTabBar` Tab bar is not scrolling.

**Comment by msaps** [comment]
@krishnameena the `blockTabBar` isn't designed to scroll. The only bar that currently offers scrolling behaviour is `.scrollingButtonBar`.

**Comment by krishnameena** [comment]
Ok got it, Thanks!!
