### ISSUE TITLE
rightAligned item distribution

### ISSUE THREAD

**Issue by mblcdr** [uias/Tabman#103]
We have a use case that requires the tabs to be laid out from right to left. Is there a way to achieve this using the current API?

It would be great if there was a `rightAligned` option in `ItemDistribution`.

**Comment by farshadmb** [comment]
@mblcdr Salam (Hi) Hamid
I think library provide support RTL Language which bases on System Language. As we know we for our applications in the Persian Language, we use LTR semantic, so you can clearly reverse your viewController's array with bar items. 

If you can describe more about your conditions in the app and is an application used dynamic viewControllers content or does not?

**Comment by mblcdr** [comment]
@farshadmb Hello (Salam) and thank you for the response.

The number of tabs is dynamic. It is in range of 2 to 6. When using `.scrollingBottomBar`, reversing the array of ViewControllers does not work when the number of tabs is low.

Currently even when using RTL direction, tabs are aligned to the left in `.scrollingBottomBar` style.

Anyway, I think it would be nice to have a .rightAligned option regardless of layout direction.

**Comment by msaps** [comment]
Going to label this as an improvement, not sure when it'll be prioritised, as stability and extendability are the current focus 👍
