### ISSUE TITLE
Custom Tabbar with Image and Title

### ISSUE THREAD

**Issue by krishnameena** [uias/Tabman#104]
It is not bug but it is kind of feature. Is it possible in Tabman to get a view like attached image. I want scrollable Tabbar with Image and Title and selected item size different and not  selected different plus all the data in Tabbar will be coming from API not static data. Please guide me if it possible in this.

![screenshot_20170624-170524](https://user-images.githubusercontent.com/10487399/27508321-a452f3c4-58ff-11e7-9ac6-08fdbbce15a9.png)

**Comment by msaps** [comment]
Hi,

Looks like you're after creating a custom `TabmanBar` implementation.. There is a basic guide available [here](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md) for how to go about implementing this, and the framework should provide you with everything you need to create something similar.

**Comment by krishnameena** [comment]
I have followed this link [Embedding TabmanBar in an external view](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md#embedding-tabmanbar-in-an-external-view)

but tab bar item is appearing for only 1 view controller and I have added 5 view controllers and one more thing I want to know about the selected and not selected items different different view I mean which function I should override to achieve this behaviour. 

![simulator screen shot 27-jun-2017 11 49 32 am](https://user-images.githubusercontent.com/10487399/27573285-b5d85cf2-5b2e-11e7-8b6f-e767c7987e35.png)

**Comment by krishnameena** [comment]
Hi,

any update for me ??

**Comment by msaps** [comment]
@krishnameena Hi,

You shouldn't have had to embed the bar anywhere, implementing a custom `TabmanBar` that gives you the layout with the image / title will be sufficient to achieve the desired look.

So in your custom `TabmanBar` subclass, you'd need to do the following:

- Override `construct(in contentView:, for items:)` and build your layout.
     - This by the looks of it involves a scroll view / horizontal stack view / custom item view.
- Override `update(forPosition position: direction:, indexRange:, bounds:)`.
     - This is where you will update the transform for the currently selected item. 
- Call `itemSelected(at index:)` when one of your item views is selected.

That should give you everything you need to build a similar look and feel 😄

**Comment by krishnameena** [comment]
Hi,

I followed but still I am not getting the desirable behaviour. I have 5 child view controllers

This is my construct func

```
override func construct(in contentView: UIView,
                            for items: [TabmanBar.Item]) {
        //for i in 0..<items.count {
        let label = UILabel()
        label.text = "TITLE"
        label.textAlignment = .center
        label.textColor = .black
        
        let imageName = "not_found"
        let image = UIImage(named: imageName)
        let imageView = UIImageView(image: image!)
        imageView.frame = CGRect(x: 0, y: 0, width: 100, height: 100)
        label.frame = CGRect(x: 0, y: 110, width: 100, height: 30)
        
        self.contentView.addSubview(imageView)
        self.contentView.addSubview(label)
        //}
    }
```

As I am very new to iOS so could you please post a sample code for me for the same. That will be really very helpful for me. Thanks in advance  😄


![simulator screen shot 29-jun-2017 9 02 04 pm](https://user-images.githubusercontent.com/10487399/27696039-3a221bb6-5d0e-11e7-8046-960ac2aa905c.png)

**Comment by msaps** [comment]
@krishnameena the issue you have is the views you are adding all have the same frame of `CGRect(x: 0, y: 0, width: 100, height: 100)`, so they're all being laid out on top of each other.

The image view and label need to be added into a container view and then embedded in a horizontal stack view. This will give you the simplest way of getting the layout:

```
UIStackView (Horizontal)
     -> ItemView
          -> UIImageView (Image View)
          -> UILabel (Title label)
     -> ItemView
          -> UIImageView (Image View)
          -> UILabel (Title label)
     -> ItemView
          -> UIImageView (Image View)
          -> UILabel (Title label)
```

**Comment by krishnameena** [comment]
Hi,

Thanks for the reply.

Now I am trying following and Items UI appearing fine but not able to scroll it horizontally and also clicking on specific item also not working

```
    override func construct(in contentView: UIView,
                            for items: [TabmanBar.Item]) {
        
        let scrollView = UIScrollView(frame : CGRect(x: 0, y: 0, width: 1000, height: 150))
        scrollView.alwaysBounceHorizontal = true
        scrollView.isScrollEnabled = true
        scrollView.showsHorizontalScrollIndicator = true
        
        let stackView   = UIStackView()
        stackView.axis  = UILayoutConstraintAxis.horizontal
        stackView.distribution  = UIStackViewDistribution.fill
        stackView.alignment = UIStackViewAlignment.fill
        stackView.spacing   = 5.0
        
        
        for i in 0 ..< items.count {
            let customView = UIView()
            customView.frame = CGRect(x: 100*i, y: 0, width: 100, height: 150)
            let label = UILabel()
            label.text = "TITLE"
            label.textAlignment = .center
            label.textColor = .black
        
            let imageName = "not_found"
            let image = UIImage(named: imageName)
            let imageView = UIImageView(image: image!)
            imageView.frame = CGRect(x: 100*i, y: 0, width: 100, height: 100)
            label.frame = CGRect(x: 100*i, y: 110, width: 100, height: 30)
            
            customView.addSubview(imageView)
            customView.addSubview(label)
            
            stackView.addArrangedSubview(customView)
            //stackView.translatesAutoresizingMaskIntoConstraints = false
        }
        
        scrollView.contentSize = CGSize(width:1000, height: stackView.frame.height)
        scrollView.addSubview(stackView)
        
        self.contentView.addSubview(scrollView)
    }
```


Please help me out what I am doing wrong? 

![simulator screen shot 22-jul-2017 4 05 41 pm](https://user-images.githubusercontent.com/10487399/28490441-dd9d224a-6ef7-11e7-8a72-4a97eb6bd1ba.png)

**Comment by krishnameena** [comment]
Hi, I have got it scrolling now but 

```
override func itemSelected(at index: Int) {
        super.itemSelected(at: index)
    }
```

above method does not called any how when we select any item.


Also last 2 items are overlapping in the tabman bar.


![simulator screen shot 22-jul-2017 4 34 57 pm](https://user-images.githubusercontent.com/10487399/28490609-e9610020-6efb-11e7-87e5-412896913a99.png)

**Comment by krishnameena** [comment]
Any update for me please??

**Comment by msaps** [comment]
@krishnameena 

The reason for the cutoff of items at the end of your bar is due to the `1000pt` frame width you're setting on the `scrollView`. Really this view hierarchy should be laid out using AutoLayout which would automatically calculate how big the view needs to be. The `scrollView` needs to be pinned to all 4 edges of the `contentView`, the `stackView` needs to be pinned to all 4 edges of the `scrollView` and also has to match it's height. 

Regarding the `itemSelected` function, this is not automatically called, and is required to be called manually by an item in the bar when pressed. This function simply handles all the page transitioning and animation further up the hierarchy. You will need to add actions to the views within your `stackView` and figure out the index of which one was selected, corresponding to the relative view controller index.

**Comment by krishnameena** [comment]
Hi,

I couldn't figure out where and how I can add action to views for `itemSelected` .

It's my humble request to you if you can post sample code for me for this particular thing. Please let me know if it is ok with you than I can send you the sample project code which I have implemented yet.

Thanks in advance.

**Comment by tabacz** [comment]
@krishnameena 
I have the same problem. I couldn't figure out where and how I can add action to views for itemSelected. 
Did you find a solution?

**Comment by krishnameena** [comment]
No still I didn't find any solution. I am waiting for Tabman team to suggest some solution or prototype of the same.

**Comment by msaps** [comment]
@tabacz @krishnameena `itemSelected(index: Int)` is just a function on a `TabmanBar` that you need to manually call to invoke actions on the underlying `TabmanViewController`.

**You are responsible for the content of a custom bar**.  `construct(in contentView: for items:)` is the point at which you should lay out all your views in the bar. So for example: A horizontal `UIStackView` with a `UIButton` for each item. 

You would then add a selector to these `UIButton`s as normal using `addTarget()`. In the resulting selector action function, you would need to figure out the corresponding index of the button, and then call `itemSelected(at: indexOfMyButton)`. 

Hope this is helpful 👍

**Comment by sregg** [comment]
@msaps it would be great to have a way to customize only the view of each "tab", instead of the current simple `UIButton`.
In my case, I'd like to have exactly the same behavior of `TabmanScrollingButtonBar` but with a custom view (a vertical `UIStackView` containing a `UILabel` and a custom `UIImageView`).
This could be achieved using a `TabmanDelegate` protocol with a `func constructTab(item: TabmanBar.Item) -> UIView`.

**Comment by krishnameena** [comment]
Hi @sregg 

Did you get it working with custom view(a vertical UIStackView containing a UILabel and a custom UIImageView) ??

**Comment by sregg** [comment]
Hi krishna,

Yes. I ended up implementing a custom TabmanBar as it is documented here: https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md#creating-a-custom-tabmanbar.

It worked alright but I found the process rather complicated and I ended up having to remove the underline as I wasn't able to make it work properly.

I'd say this solution is great if you want something completely different than the provided styles, but if you want to just have a custom tab button inside the standard TabmanScrollingButtonBar for instance, it'd be great if the library would allow you to do that.

**Comment by krishnameena** [comment]
Hi @sregg 

Following is my code for CustomTabBar but still my `onItemSelected(index: Int)` is not working.

Could you please help me out what I am doing wrong or it would be great if you can post your working code of CustomTabBar

`class CustomTabBar: TabmanBar {
    
    
    override var intrinsicContentSize: CGSize {
        var autoSize = super.intrinsicContentSize
        autoSize.height = 150
        return autoSize
    }
    
    override func defaultIndicatorStyle() -> TabmanIndicator.Style {
        // declare default indicator style here
        return .line
    }
    
    override func usePreferredIndicatorStyle() -> Bool {
        // whether the bar should use preferredIndicatorStyle
        return true
    }
    
    override func construct(in contentView: UIView,
                            for items: [TabmanBar.Item]) {
        
        let scrollView = UIScrollView(frame : UIScreen.main.bounds)
        scrollView.alwaysBounceHorizontal = true
        scrollView.isScrollEnabled = true
        scrollView.showsHorizontalScrollIndicator = true
        
        let stackView   = UIStackView()
        stackView.axis  = UILayoutConstraintAxis.horizontal
        stackView.distribution  = UIStackViewDistribution.fillEqually
        stackView.alignment = UIStackViewAlignment.fill
        stackView.spacing   = 5.0
        
        
        var count = 0
        for i in 0 ..< items.count {
            count += 1
            let customView = UIView()
            print("Count " + count.stringValue + " " + i.stringValue + " " + (100*i+5*count).stringValue)
            customView.frame = CGRect(x: 100*i+5*count, y: 0, width: 100, height: 150)
            let label = UILabel()
            label.text = "TITLE " + (i+1).stringValue
            label.textAlignment = .center
            label.textColor = .black
        
            let imageName = "not_found"
            let image = UIImage(named: imageName)
            let imageView = UIImageView(image: image!)
            imageView.frame = CGRect(x: 100*i+5*count, y: 0, width: 100, height: 100)
            label.frame = CGRect(x: 100*i+5*count, y: 110, width: 100, height: 30)
            
            customView.addSubview(imageView)
            customView.addSubview(label)
            
            let tap = UITapGestureRecognizer(target: self, action: #selector(self.handleTap(sender:)))
            customView.isUserInteractionEnabled = true
            customView.tag = i
            customView.addGestureRecognizer(tap)
            
            stackView.addArrangedSubview(customView)
            //stackView.translatesAutoresizingMaskIntoConstraints = false
        }
        
        print((105*(count)+5).stringValue)
        
        scrollView.contentInset = UIEdgeInsets(top: 5.0, left: 5.0, bottom: 5.0, right: 5.0)
        scrollView.contentSize = CGSize(width:CGFloat(105*(count)+5), height: stackView.frame.height)
        scrollView.addSubview(stackView)
        
        
        self.contentView.addSubview(scrollView)
    }
    
    override func add(indicator: TabmanIndicator, to contentView: UIView) {
        // add the indicator to the bar here
        contentView.addSubview(indicator)
    }
    
    override func update(forPosition position: CGFloat,
                         direction: PageboyViewController.NavigationDirection,
                         indexRange: Range<Int>,
                         bounds: CGRect) {
        super.update(forPosition: position, direction: direction,
                     indexRange: indexRange, bounds: bounds)
        
        // update your bar contents for a positional update here
    }
    
    override func update(forAppearance appearance: Appearance,
                         defaultAppearance: Appearance) {
        super.update(forAppearance: appearance,
                     defaultAppearance: defaultAppearance)
        
        // update the bar appearance here
    }
    
    @objc func itemSelected(index: Int) {
        print(index.stringValue)
        super.itemSelected(at: index)
    }
    
    
    @objc func handleTap(sender: UITapGestureRecognizer) {
        print("Selected")
    }
}`

**Comment by sregg** [comment]
Here's mine:

`class TripPassengersTabmanBar: TabmanBar {
    let inactiveAlpha = CGFloat(0.5)
    let activePictureBorderWidth = CGFloat(2.0)
    
    let scrollViewContentView = UIView()
    var tabStackViews = [UIStackView]()
    
    // MARK: Lifecycle
    
    override func defaultIndicatorStyle() -> TabmanIndicator.Style {
        // declare indicator style here
        return .clear
    }
    
    override func usePreferredIndicatorStyle() -> Bool {
        // Whether to use preferredIndicatorStyle
        return true
    }
    
    // MARK: TabmanBar Lifecycle
    
    public override func construct(in contentView: UIView,
                                   for items: [TabmanBar.Item]) {
        // UI is like this:
        // UIScrollView - scrollView
        //  - UIView - scrollViewContentView
        //    - UIStackView - stackView
        //      - UIStackView - tabStackView (All tab)
        //        - UILabel tabStackView ("All")
        //        - UIImageView (all icon)
        //      - UIStackView - tabStackView (passenger 1)
        //        - UILabel (passenger 1's name)
        //        - UserImageView (passenger 1's picture)
        //      - UIStackView - tabStackView (passenger 2)
        //        - UILabel (passenger 2's name)
        //        - UserImageView (passenger 2's picture)
        
        let scrollView = UIScrollView()
        scrollView.showsHorizontalScrollIndicator = false
        
        let scrollViewContentView = UIView()
        scrollView.addSubview(scrollViewContentView)
        scrollViewContentView.autoPinEdgesToSuperviewEdges()
        scrollViewContentView.autoMatch(.height, to: .height, of: scrollView)
        
        let stackView = UIStackView()
        stackView.axis = .horizontal
        stackView.spacing = 12
        scrollViewContentView.addSubview(stackView)
        stackView.autoPinEdgesToSuperviewEdges(with: UIEdgeInsets(top: 8, left: 12, bottom: 8, right: 0))
        
        tabStackViews = []
        
        for (index, item) in items.enumerated() {
            let tabStackView = UIStackView()
            tabStackView.axis = .vertical
            tabStackView.alignment = .center
            tabStackView.spacing = 4
            
            // title
            let title = UILabel()
            title.text = item.title ?? ""
            title.font = Constants.kHPFontBold(12)
            title.widthAnchor.constraint(equalToConstant: 48).isActive = true
            title.textAlignment = .center
            tabStackView.addArrangedSubview(title)
            
            // title color = based on hitcher's state
            let color: UIColor
            if (index == 0) {
                color = Constants.kPrimaryBlue
            } else if let booking = (item.context as? Hitcher)?.typedBooking() {
                color = booking.color()
            } else {
                color = Constants.kDarkGrey
            }
            title.textColor = color
            
            // image
            var image: UIView
            let imageSize = 36
            if let hitcher = item.context as? Hitcher {
                // passenger picture
                let picture = UserImageView()
                picture.show(hitcher.user, size: .small, enableTap: false)
                picture.layer.cornerRadius = CGFloat(imageSize) / 2
                picture.borderColor = color
                picture.borderWidth = 0
                tabStackView.addArrangedSubview(picture)
                image = picture
            } else {
                // All tab
                let allTabIcon = UIImageView(image: #imageLiteral(resourceName: "icon_all_passengers"))
                image = allTabIcon
            }
            image.autoSetDimensions(to: CGSize(width: imageSize, height: imageSize))
            tabStackView.addArrangedSubview(image)
            
            // start with 50% alpha, will be updated in update()
            tabStackView.alpha = inactiveAlpha
            
            stackView.addArrangedSubview(tabStackView)
            tabStackView.tag = index
            tabStackView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(onItemTapped)))
            tabStackViews.append(tabStackView)
        }
        
        self.contentView.addSubview(scrollView)
        scrollView.autoPinEdgesToSuperviewEdges()
    }
    
    @objc func onItemTapped(_ sender: UIGestureRecognizer) {
        self.itemSelected(at: sender.view?.tag ?? 0)
    }
    
    public override func add(indicator: TabmanIndicator,
                             to contentView: UIView) {
        // no indicator
    }
    
    override func update(forPosition position: CGFloat,
                         direction: PageboyViewController.NavigationDirection,
                         indexRange: Range<Int>,
                         bounds: CGRect) {
        super.update(forPosition: position,
                     direction: direction,
                     indexRange: indexRange,
                     bounds: bounds)
        
        let (lowerIndex, upperIndex) = lowerAndUpperIndex(forPosition: position,
                                                          minimum: indexRange.lowerBound,
                                                          maximum: indexRange.upperBound)
        // selection by click, not scroll
        if (lowerIndex == upperIndex) {
            // clear selection
            tabStackViews.forEach {
                $0.alpha = inactiveAlpha
                if let tabUserPicure = $0.arrangedSubviews.last as? UserImageView {
                    tabUserPicure.borderWidth = 0
                }
            }
            
            // select new tab
            let selectedTab = tabStackViews[lowerIndex]
            selectedTab.alpha = 1
            if let tabUserPicure = selectedTab.arrangedSubviews.last as? UserImageView {
                tabUserPicure.borderWidth = 2
            }
            return
        }
        
        guard tabStackViews.count > max(upperIndex, lowerIndex) else { return }
        
        let lowerTab = tabStackViews[lowerIndex]
        let upperTab = tabStackViews[upperIndex]
        let targetTab = direction == .forward ? upperTab : lowerTab
        let oldTargetTab = direction == .forward ? lowerTab : upperTab
        
        var integral: Float = 0.0
        let transitionProgress = CGFloat(modff(Float(position), &integral)) // 3.45 => 0.45
        let relativeProgress = direction == .forward ? transitionProgress : 1.0 - transitionProgress
        let targetAlpha = inactiveAlpha + (1 - inactiveAlpha) * relativeProgress
        let oldTargetAlpha = 1 - (1 - inactiveAlpha) * relativeProgress
        
        targetTab.alpha = targetAlpha
        oldTargetTab.alpha = oldTargetAlpha
        
        if let targetTabUserPicure = targetTab.arrangedSubviews.last as? UserImageView {
            targetTabUserPicure.borderWidth = activePictureBorderWidth * relativeProgress
        }
        
        if let oldTargetTabUserPicure = oldTargetTab.arrangedSubviews.last as? UserImageView {
            oldTargetTabUserPicure.borderWidth = activePictureBorderWidth * (1 - relativeProgress)
        }
    }
    
    func lowerAndUpperIndex(forPosition position: CGFloat, minimum: Int, maximum: Int) -> (Int, Int) {
        let lowerIndex = floor(position)
        let upperIndex = ceil(position)
        let minimum = CGFloat(minimum)
        let maximum = CGFloat(maximum)
        
        return (Int(max(minimum, min(maximum, lowerIndex))),
                Int(min(maximum, max(minimum, upperIndex))))
    }
    
    override func update(forAppearance appearance: Appearance,
                         defaultAppearance: Appearance) {
        super.update(forAppearance: appearance,
                     defaultAppearance: defaultAppearance)
        
        // update the bar appearance here
    }
}`

**Comment by krishnameena** [comment]
Hi,

Thanks for posting your code but its giving compilation errors may be because of removal of pure layout so could not able to test it.

**Comment by krishnameena** [comment]
Hi @msaps ,

Any help would be much appreciated.

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
