### ISSUE TITLE
Full Width

### ISSUE THREAD

**Issue by RajChanchal** [uias/Tabman#107]
I had only two items in my bar list, I wanted to show them in full width bars. Can it be possible?
This is how it looks now.

<img width="308" alt="screen shot 2017-06-29 at 11 56 22 am" src="https://user-images.githubusercontent.com/7058465/27677294-2b5a007c-5cc2-11e7-9652-05f03b6bd59d.png">

**Comment by msaps** [comment]
Hi @RajChanchal,

That sort of layout is possible, by updating a few of the available appearance properties:

```swift
bar.appearance = TabmanBar.Appearance({ (appearance) in
            appearance.layout.itemDistribution = .centered
            appearance.layout.interItemSpacing = self.view.bounds.size.width / 2.0
})
```

This should give you the following appearance:
![simulator screen shot 29 jun 2017 10 12 26](https://user-images.githubusercontent.com/3515448/27680414-866ce984-5cb3-11e7-9808-0c4b4618607f.png)

Is that what you are after? 😀

**Comment by RajChanchal** [comment]
Wow! thanks a ton.
