### ISSUE TITLE
Table Rows behind TabBar

### ISSUE THREAD

**Issue by csimmonsbluebook** [uias/Tabman#109]
All of the UIViewControllers added to the bar are TableViewControllers. It appears that the first row of the table ends up behind the bar. I thought the automatic inset would take care of this. Am I missing something? Please advise.

**Comment by msaps** [comment]
Hi,

Just had a quick look and it seems to be a problem specific to using `UITableViewController`. The auto-insetting behaviour works fine when using a standard `UIViewController` with a `UITableView` subview as a temporary workaround??

**Comment by msaps** [comment]
Demo project showing the issue:

[Tabman-TableViewControllerTest.zip](https://github.com/uias/Tabman/files/1114539/Tabman-TableViewControllerTest.zip)

Appears that `UITableViewController` is either ignored by auto-insetting or it the lifecycle of the view controller disrupts the insetting behaviour.

**Comment by csimmonsbluebook** [comment]
@msaps Thanks for the quick reply! Gave the demo a download and checked out what you're talking about. I'll use the UITableView subview workaround in the meantime.

**Comment by msaps** [comment]
@csimmonsbluebook just fixed this and it's available from [0.7.1](https://github.com/uias/Tabman/releases/tag/0.7.1) 👍

**Comment by csimmonsbluebook** [comment]
@msaps Awesome! Just switched some code back and it's working great 👍

**Comment by csimmonsbluebook** [comment]
@msaps I've updated to Swift 4 in my app and it seems that the automatic inset issue has resurfaced with `UITableViewControllers`. The first section header and part of the first cell are behind the tabbar. The inset issue occurs when you switch past the first tab.

**Comment by msaps** [comment]
@csimmonsbluebook okay I will reopen and take a look. Are you using the latest version of Tabman?

**Comment by csimmonsbluebook** [comment]
@msaps Yeah I'm using version `1.0.3`

**Comment by msaps** [comment]
@csimmonsbluebook okay cool! Would you be able to upload an example project that shows the issue? I can't seem to reproduce it. 😞

**Comment by csimmonsbluebook** [comment]
@msaps I've attached a project that shows the inset issue. The issue will only arise when you click on the second tab and NOT when you swipe to navigate to the second tab. When you perform the click to get to the second tab named "Posts 2" and then pull down on the table view, you will see that the first two items are hidden underneath.

[TabmanTest.zip](https://github.com/uias/Tabman/files/1407443/TabmanTest.zip)

**Comment by msaps** [comment]
@csimmonsbluebook thanks so much for that, will get on with fixing it tonight! 👍

**Comment by msaps** [comment]
@csimmonsbluebook check out [1.0.5](https://github.com/uias/Tabman/releases/tag/1.0.5), should be all fixed 👍

**Comment by csimmonsbluebook** [comment]
@msaps Looks good man, great stuff!

**Comment by csimmonsbluebook** [comment]
@msaps I think the issue has resurfaced. Same parameters apply for reproducing it. I've updated the Pods and reattached the sample that we used before. It's using `Tabman 1.6.0` and `AutoInsetter 1.2.1`.

[TabmanTest.zip](https://github.com/uias/Tabman/files/1819974/TabmanTest.zip)

**Comment by jxtmo** [comment]
hi @msaps, I am having exactly the same issue as well 🙇

**Comment by msaps** [comment]
@csimmonsbluebook thanks again for the demo project, it really helped! 🥇 

@jxtmo 
I've fixed the issue in [AutoInsetter 1.2.2](https://github.com/uias/AutoInsetter/releases/tag/1.2.2), please run `pod update AutoInsetter` (or however you're integrating) and the issue should be resolved 👍

**Comment by jxtmo** [comment]
@msaps thanks for the prompt fixes, works flawlessly now 👍

**Comment by csimmonsbluebook** [comment]
@msaps Thanks again man. Working for me as well!
