### ISSUE TITLE
Wrong bottom inset for embedded Scrollviews

### ISSUE THREAD

**Issue by jnshey** [uias/Tabman#111]
The top inset for UITableViewController's table view has been fixed in `0.7.1`. But the bottom inset is still wrong for my case. (I have a tab bar.)

It seems that in [TabmanViewController+Insetting.swift](https://github.com/uias/Tabman/blob/18f8d56448c8fc1dad685aa8e4bdad89f5f24b98/Sources/Tabman/TabmanViewController%2BInsetting.swift), there should be the line `requiredContentInset.bottom += self.bottomLayoutGuide.length` between lines 74 and 75.

**Comment by msaps** [comment]
Hi,

Okay I'll check it out and try and get it fixed ASAP. 👍

**Comment by msaps** [comment]
This is now fixed as of [0.7.2](https://github.com/uias/Tabman/releases/tag/0.7.2) 🎉
