### ISSUE TITLE
Pass data between child ViewControllers & Parent

### ISSUE THREAD

**Issue by maasim94** [uias/Tabman#112]
Hi, 
Is there any way to either pass data between Main tab controller and children or using some common method to be share between all children put in parent and use it

**Comment by msaps** [comment]
Hi,

Currently, the best way to pass data to the child view controllers from the parent would be during their initialisation, so probably in the `viewControllers(forPageboyViewController:)` function. 

You could also access the parent view controller from within a child by using the `parentPageboyViewController()` function and casting it to whatever subclass your `TabmanViewController` is.

Hope this helps!

**Comment by maasim94** [comment]
thanks :)
