### ISSUE TITLE
tabbar view's problem after changing the text's font 

### ISSUE THREAD

**Issue by Behnoud** [uias/Tabman#119]
Hi,
whenever I change the font in tab bar the behavior is not what I expected :
this the custom appearance that I am using:
```swift
    private lazy var appearance: TabmanBar.Appearance = {
        let currentAppearance = TabmanBar.Appearance.defaultAppearance
        currentAppearance.text.font = font
        currentAppearance.state.selectedColor = textColor
        currentAppearance.state.color = textColor.withAlphaComponent(0.5)
        currentAppearance.style.background = .solid(color: bgColor!)
        currentAppearance.indicator.color = textColor
        currentAppearance.indicator.lineWeight = .thin
        currentAppearance.layout.interItemSpacing = 5.0
        return currentAppearance
    }()
```
and this the result :

![screen shot 2017-07-15 at 12 11 24 pm](https://user-images.githubusercontent.com/7837270/28237529-c6165278-6956-11e7-90f5-2dfb65658a17.png)

The presented view controller in this tab is not configured correctly as you can see in the picture, the tab bar overlaid on the view controller  and that happens when I change the font 

This test is when I don't change the font :
```swift
  private lazy var appearance: TabmanBar.Appearance = {
        let currentAppearance = TabmanBar.Appearance.defaultAppearance
        currentAppearance.state.selectedColor = textColor
        currentAppearance.state.color = textColor.withAlphaComponent(0.5)
        currentAppearance.style.background = .solid(color: bgColor!)
        currentAppearance.indicator.color = textColor
        currentAppearance.indicator.lineWeight = .thin
        currentAppearance.layout.interItemSpacing = 5.0
        return currentAppearance
    }()
```
and this is the result :
![screen shot 2017-07-15 at 12 15 47 pm](https://user-images.githubusercontent.com/7837270/28237557-6714ef36-6957-11e7-9725-f90602df7066.png)

When I set `currentAppearance.layout.itemVerticalPadding` it will somehow fix it but I don't want padding at the end of tabs 

```swift
    private lazy var appearance: TabmanBar.Appearance = {
        let currentAppearance = TabmanBar.Appearance.defaultAppearance
        currentAppearance.text.font = font
        currentAppearance.state.selectedColor = textColor
        currentAppearance.state.color = textColor.withAlphaComponent(0.5)
        currentAppearance.style.background = .solid(color: bgColor!)
        currentAppearance.indicator.color = textColor

        currentAppearance.layout.itemVerticalPadding = 0.01
        currentAppearance.indicator.lineWeight = .thin
        currentAppearance.layout.interItemSpacing = 5.0
        return currentAppearance
    }()
```

This is the result :
![screen shot 2017-07-15 at 12 18 35 pm](https://user-images.githubusercontent.com/7837270/28237577-cf9f1a86-6957-11e7-98ae-d1d31ac8c978.png)

Any help would be appreciated,
Thanks in advance,
Behnoud

**Comment by msaps** [comment]
Hi,

I'll take a look and see if I can reproduce the issue 👍

**Comment by msaps** [comment]
@Behnoud would you be able to upload a demo project that reproduces this issue please? 😄

**Comment by Behnoud** [comment]
ok I will upload a sample within next week
