### ISSUE TITLE
.centered distribution not honored when there is only one tab

### ISSUE THREAD

**Issue by mblcdr** [uias/Tabman#121]
When there is only one tab, `.centered ` distribution is not honored. And the single tab sticks to the left of the embedding view, not taking the minimum width into account. Also, no indicator is displayed. Here is the screenshot of the problem:

![simulator screen shot Jul 25 2017 15 37 45](https://user-images.githubusercontent.com/3671190/28569653-005cea2c-7150-11e7-8602-40daeebc037f.png)

When there is more than one tab everything works as expected. Here is a screenshot showcasing the behavior of more than one tab:

![simulator screen shot Jul 25 2017 15 41 19](https://user-images.githubusercontent.com/3671190/28569702-3dd10104-7150-11e7-994a-bfd4750eb8c0.png)

**Comment by msaps** [comment]
Think I've fixed this issue, will get it in the next release 👍

**Comment by mblcdr** [comment]
I've tried the latest snapshot and it appears that the positioning issue is fixed. Thank you.
The problem now is that the indicator's width is equal to the width of embedding view, not the width of the item, considering the `minimumWidth`.

**Comment by msaps** [comment]
@mblcdr I believe this is actual the desired behaviour for the `.buttonBar` style. The indicator in that case is sized by dividing the bar container width by the number of items, so it's always fixed width. `.scrollingButtonBar` behaves slightly differently.

**Comment by mblcdr** [comment]
That makes sense. Thank you for clarifying.
