### ISSUE TITLE
Customize Indicator Width

### ISSUE THREAD

**Issue by sarayd** [uias/Tabman#122]
How would I make my buttonBar indicator line shorter? As in the example below:

![example](https://user-images.githubusercontent.com/16440070/28650643-3b3cb95a-724b-11e7-8b81-ae948ff6de3e.png)

**Comment by msaps** [comment]
Hi, 

This is not currently available, but certainly could be available as a custom appearance property. Potentially something like `Appearance.Indicator.horziontalInset`?

**Comment by patniemeyer** [comment]
As a workaround you can create a custom indicator to replace the line indicator like this:

```
class MyLineIndicator: TabmanIndicator
{
    private var lineView = UIView()
    
    override public var intrinsicContentSize: CGSize {
        return CGSize(width: 100.0, height: 3.0)
    }
    
    override public var tintColor: UIColor! {
        didSet {
            lineView.backgroundColor = tintColor
        }
    }
    
    public override func constructIndicator()
    {
        self.backgroundColor = .clear
        self.addSubview(lineView)
        lineView.set(.height, to: intrinsicContentSize.height)
        lineView.set(.width, to: intrinsicContentSize.width)
        lineView.alignToSuperviewAxis(.vertical)
        lineView.pinToSuperviewEdge(.bottom, inset: 0.0)
        lineView.backgroundColor = self.tintColor
    }
}
```
That is copying Tabman's layout extensions but you can replace them with something else.

**Comment by msaps** [comment]
Now available in Tabman 2 (appreciate its a little late 😅)

**Comment by zyflovelam** [comment]
> Now available in Tabman 2 (appreciate its a little late 😅)

How to use it now? help me please.
