### ISSUE TITLE
Tab bar vertical separators

### ISSUE THREAD

**Issue by sarayd** [uias/Tabman#123]
Apologize for submitting another question, but I would like to get some advice on how to achieve this look:
Was unable to find a solution to this so any guiders would be appreciated!

![boxes](https://user-images.githubusercontent.com/16440070/28650896-aca31d54-724c-11e7-9a03-325675b865b0.png)

**Comment by msaps** [comment]
Hi,

This is something I've been meaning to add for quite a while, so I'll try and get around to doing it ASAP!  Another appearance property to add! 😄

**Comment by khanhhungus** [comment]
I need that feature too. Help me

**Comment by chungfk** [comment]
is this feature available?

**Comment by msaps** [comment]
@chungfk unfortunately not - will try and prioritise it for the next release

**Comment by msaps** [comment]
Now available in Tabman [2.5.0](https://github.com/uias/Tabman/releases/tag/2.5.0) 🎉
