### ISSUE TITLE
Tab bar below the navigation bar

### ISSUE THREAD

**Issue by levantaodedo** [uias/Tabman#125]
I need some guidance on how to place the tab bar below a navigation bar.

**Comment by msaps** [comment]
@levantaodedo if you are using the standard system `UINavigationBar` within a `UINavigationController` the tab bar should be insetted below automatically. Are you not seeing this behaviour?

**Comment by otymartin** [comment]
@msaps how do you set it below NavBar is not using UINavigationController?
