### ISSUE TITLE
Tabman Height?

### ISSUE THREAD

**Issue by Lulli4444** [uias/Tabman#126]
Hi,
I don't understand how to set the Tabman height.
If I set it like this:
`case .scrollingButtonBar:`
`...`
`appearance.layout.height = .explicit(value: 20)`
nothing happens. Can you help me please?

**Comment by msaps** [comment]
Hi,

This is due to the bar only allowing an explicit height that won't compromise the constraints of it's contents. Please see the discussion here in [#100](https://github.com/uias/Tabman/issues/100#issuecomment-318397802). 🙂
