### ISSUE TITLE
Crash on TabManViewController+Insetting Line 97

### ISSUE THREAD

**Issue by emadd** [uias/Tabman#128]
I'm using Tabman in two areas of my app and after recently updating one of those areas is now crashing when attempting to switch tabs.   Not much else I can offer as the framework was compiled with optimization.

**Comment by emadd** [comment]
It actually seems Tabman doesn't like UITableViewControllers.  I refactored away from it and no more crashing.

**Comment by Patrick-Remy** [comment]
For the future: I fixed it with #134
