### ISSUE TITLE
How to use this with latest Pageboy beta

### ISSUE THREAD

**Issue by otymartin** [uias/Tabman#129]
@msaps 
Installing the latest version of this pod also installs the latest version of pageboy. However I wrote my project using the latest pageboy beta leaving the version tabman installs out of date.
How can I install this Pod along with the latest Pageboy beta?

**Comment by msaps** [comment]
@otymartin oh cool, I did wonder if anyone would end up using the beta's! 😄 

There is currently a branch open on `Tabman` called [pageboy-2.0](https://github.com/uias/Tabman/tree/pageboy-2.0) which is using the latest beta's from Pageboy and adds Tabman compatibility. However the latest on that branch is using Beta 4 which adds Swift 4 support so you will need to use Xcode 9 to compile. 

Point your dependency at the `pageboy-2.0` branch and you should be able to use the 2.0 beta's 👍

**Comment by otymartin** [comment]
@msaps unfortunatley Im using xcode 8 as I have a production project im submitting this week :(
Any work-around?

**Comment by msaps** [comment]
@otymartin that's strange. What are you using for your dependency management?

I've seen that Cocoapods has issues integrating the latest Pageboy beta (2.0.0 beta 4) which is where I added Swift 4 support. So strange that you're able to build in Xcode 8.x!

**Comment by msaps** [comment]
@otymartin having just checked it out, I think it's by blind luck there aren't any breaking API changes in adding Swift 4 support to Pageboy, so that's why it compiles in Swift 3. 😄

**Comment by otymartin** [comment]
@msaps 🙌🙌🙌🙌
