### ISSUE TITLE
Can Tabman Bar Item be any UIView Element?

### ISSUE THREAD

**Issue by otymartin** [uias/Tabman#130]
@msaps 
I'd like to know if I can put a UITextField as my Tabman Bar Item if so how?
That to me would be a game changer indeed.

I'm trying to create a single inline form that functions similar to stripes credit card textField (STPPaymentTextField) and the closest structure that can help me achieve that is the TabmanBar.

Right now I was adding multiple viewControllers to my tabmanVC each with a single TextField however it would be so much more convinient to add them as Tab Bar Item to avoid creating so many VC's.

**Comment by msaps** [comment]
@otymartin you can put whatever view you want in a `TabmanBar`, and then associate it with a `TabmanBar.Item`. Take a look at the [Advanced Customisation](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md#creating-a-custom-tabmanbar) docs for creating a custom bar 🙂

**Comment by otymartin** [comment]
@msaps You thought of everything🙈 your the real mvp✊
