### ISSUE TITLE
How to use the direct instantiation rather than inheritance TabmanViewController?

### ISSUE THREAD

**Issue by JqyModi** [uias/Tabman#131]
When introducing multiple third-party frameworks, if every one of them need to inherit their parent will conflict with each other

**Comment by msaps** [comment]
@JqyModi you should be able to instantiate a `TabmanViewController` with any of the normal `UIViewController` initialisers. Adding it as a child view controller would then avoid the conflicts with other frameworks and inheritance 🙂
