### ISSUE TITLE
Disable swipe gesture

### ISSUE THREAD

**Issue by lendra85** [uias/Tabman#143]
Dear sir,

I have UIScrollview with horizontally pagination, it seems not working because it's inside this tabman  view controller, in my case how to disable swiping to other view controller? so i can swipe over my scroll view only.

**Comment by msaps** [comment]
Hi,

This can be done by setting `isScrollEnabled` on the `TabmanViewController` 🙂.

**Comment by sugitatestblue** [comment]
Can it be vertically swipe disable and horizontally enable?
