### ISSUE TITLE
Content Offset Adjustment Problems with CollectionView

### ISSUE THREAD

**Issue by thevest** [uias/Tabman#145]
I've run into an issue where (I think) the content inset of a UICollectionView is being incorrectly calculated. However, it has been hard for me to track down where or why this may be happening. The function that does this `func insetChildViewControllerIfNeeded(_ childViewController:)` seems to work correctly until the collection view scrolls beyond the initial bounds of the window.

Initially, everything looks good 

![screen shot 2017-09-19 at 5 19 19 pm](https://user-images.githubusercontent.com/24687169/30618318-78d41eb8-9d5f-11e7-887c-91baf26d5e09.png)

Then when I scroll all the way to the bottom of the list, and back up I get this

![screen shot 2017-09-19 at 5 18 50 pm](https://user-images.githubusercontent.com/24687169/30618328-878b8900-9d5f-11e7-898d-f43834fe5fd9.png)

Any ideas what may be causing this? 

Thanks

**Comment by thevest** [comment]
Well still not sure about the root cause but by setting the child view controllers as `UIScrollViewDelegate`s I was able to set the contentInset back to the correct size when dragging ends.

**Comment by msaps** [comment]
This should be resolved as of [1.0.2](https://github.com/uias/Tabman/releases/tag/1.0.2), contains a load of fixes for insetting on iOS 11 and iPhone X. 😄
