### ISSUE TITLE
Infinite scroll behavior

### ISSUE THREAD

**Issue by JeromeCHA** [uias/Tabman#149]
Is is possible to have the same behavior as the following gif, instead of just going back to the first/last item?

![img](https://raw.githubusercontent.com/wiki/EndouMari/TabPageViewController/images/demo2.gif)

**Comment by msaps** [comment]
Not currently unfortunately, I'll raise it as an enhancement for future versions 👍

**Comment by JeromeCHA** [comment]
@msaps Hi, may I know when this feature will be implemented?

**Comment by msaps** [comment]
@JeromeCHA hey! Erm I'm wanting to perform some pretty big architectural changes for v2.0 first, to hopefully make things like this easier to implement cleanly. So can't really give you an ETA just yet sorry 😢

**Comment by msaps** [comment]
Tracking this in #537
