### ISSUE TITLE
Support AsyncDisplayKit ?

### ISSUE THREAD

**Issue by PatrickSCLin** [uias/Tabman#152]
Just found this amazing framework, one of dependencies is PureLayout ( AutoLayout Compatible ? )

wondering does Tabman support AsyncDisplayKit ( Not AutoLayout Compatible ) ?

**Comment by msaps** [comment]
Hi,

Tabman uses AutoLayout for all layout management, so not sure how it will play with AsyncDisplayKit. Would be interested to hear though? Have you tried integrating them both?
