### ISSUE TITLE
Can't run the example project

### ISSUE THREAD

**Issue by annjawn** [uias/Tabman#153]
I downloaded the example project but it keeps giving me an error `No such module Pageboy`.

**Comment by Junaid6305** [comment]
I'm getting the same error, did you manage to solve it?

**Comment by annjawn** [comment]
@Junaid6305 yes I was able to solve the installation issue, used it, and then removed it since i found a few issues that was not working well for my app.

**Comment by saxahan** [comment]
no, no not working
