### ISSUE TITLE
Swift 3 getting error Tabman.

### ISSUE THREAD

**Issue by joprithiviraj** [uias/Tabman#157]
This code getting error when i installed pod : 

 private func generateSafeAreaInsetsIfNeeded(from viewController: UIViewController) -> UIEdgeInsets {
        if #available(iOS 11, *) {
            return viewController.view.safeAreaInsets
        }
        
        var safeAreaInsets = UIEdgeInsets.zero
        safeAreaInsets.top = viewController.topLayoutGuide.length
        safeAreaInsets.bottom = viewController.bottomLayoutGuide.length
        return safeAreaInsets
    }
error: value of type 'UIView' has no member 'safeAreaInsets'

if #available(iOS 11.0, *) {
                scrollView.contentInsetAdjustmentBehavior = .never
            }

Error: value of type 'UIView' has no member 'safeAreaInsets'

**Comment by msaps** [comment]
Hi,

Tabman v1.x supports Swift 4 and is not backwards compatible with Swift 3 unfortunately, to use Tabman with Swift 3 you will need to use [0.8.3](https://github.com/uias/Tabman/releases/tag/0.8.3) or below. 👎
