### ISSUE TITLE
No such module 'Pageboy'

### ISSUE THREAD

**Issue by mihailsalari** [uias/Tabman#161]
Why?
No such module 'Pageboy'

**Comment by yunchiri** [comment]
import Tabman
import Pageboy

**Comment by ronysteel** [comment]
I already imported and updated via carthage. The same result

**Comment by oskarko** [comment]
Same here into Example project

**Comment by msaps** [comment]
@ronysteel are both dependencies (Pageboy & PureLayout) linked to your project successfully?

@oskarko have you run the Carthage command that is specified in the README? This is required to load the dependencies for the example project.

**Comment by jtressle** [comment]
@msaps what is the resolution here?  The latest version still has the same "No such module 'Pageboy'" when using pods.  

Thanks,
