### ISSUE TITLE
[FEATURE REQUEST] Prevent scrolling

### ISSUE THREAD

**Issue by Blackening999** [uias/Tabman#163]
Hello,

first of all - your library is freaking awesome!

second - can you add some sort of flag so I can prevent planning to switch tabs. Weird right?
Well - no. I have very complex gestures on my screens and I want the pager works as it is - but without scrolling in some circumstances.

**Comment by Blackening999** [comment]
Documentation is poor. I found this - **isScrollEnabled**
problem solved

**Comment by msaps** [comment]
@Blackening999 glad you found it, PR's are always welcome for improving the docs 🙂

**Comment by Blackening999** [comment]
I forked the repo to make a PR to add this feature when I found this config :)
I think it'll take a lot of time from me to understand the library all exposed public flags/features

Thanks for getting back so fast!
Cheers
