### ISSUE TITLE
Example project didn't work with Xcode 8.3.3 !

### ISSUE THREAD

**Issue by Mohammed-Eliass** [uias/Tabman#165]
lots of  errors I don't why !
is there any way for another examples for `Tabman` !

**Comment by msaps** [comment]
@Mohammed-Eliass Hi,

The latest versions of Tabman are written in Swift 4, and are therefore only compatible with Xcode 9. To use Xcode 8.x and Swift 3, you would have to use [v0.8.3](https://github.com/uias/Tabman/releases/tag/0.8.3) or below unfortunately.

**Comment by Mohammed-Eliass** [comment]
@msaps  Thanks man I know that, but my question that is there any guid to deal with this library in swift 3 ?

**Comment by msaps** [comment]
@Mohammed-Eliass if you take a look at the README at v0.8.3 [here](https://github.com/uias/Tabman/tree/0.8.3) it should guide you through using it using the legacy API's.

**Comment by Mohammed-Eliass** [comment]
@msaps Thanks man, I believe this would be a big help for me, but how to distribute the tabs equally inside the bar view for instance: I have 2 tabs and I need to make each of them had the half of the bar view.

I searched into the docs, nothing found !

          bar.appearance = TabmanBar.Appearance({ (appearance) in
                    appearance.indicator.color = UIColor.red
                    appearance.state.color = UIColor.red
                    appearance.state.selectedColor = UIColor.red
                    appearance.layout.itemDistribution = TabmanBar.Appearance.Layout.ItemDistribution.centered
                    appearance.interaction.isScrollEnabled = false
        })
[https://media.giphy.com/media/l1J9MCXCTfzZqf3Og/giphy.gif](url)

**Comment by msaps** [comment]
@Mohammed-Eliass [just replied in #159 ](https://github.com/uias/Tabman/issues/159#issuecomment-338615895)
