### ISSUE TITLE
automaticallyAdjustsChildScrollViewInsets doesn't work

### ISSUE THREAD

**Issue by Xotab4ik** [uias/Tabman#167]
https://youtu.be/XHfql7-lCuU - video demonstration

**Comment by msaps** [comment]
@Xotab4ik are you by any chance using `UICollectionViewController`? 

Just released a new version which improves automatic insetting in a number of ways, so please check out [1.0.5](https://github.com/uias/Tabman/releases/tag/1.0.5) and let me know if it works for you 🙂

**Comment by Xotab4ik** [comment]
@msaps didn't help :(

**Comment by msaps** [comment]
@Xotab4ik can I ask what your view hierarchy is?

**Comment by Xotab4ik** [comment]
@msaps 

![2017-10-26 15 36 44](https://user-images.githubusercontent.com/16893175/32046019-a34c5a40-ba63-11e7-8d1d-bab34caf3621.png)

```
class CategoriesTabsViewController: TabmanViewController, PageboyViewControllerDataSource {

    
    override func viewDidLoad() {
        super.viewDidLoad()

        self.dataSource = self

        self.bar.items = [
            Item(title: "Категория 1"),
            Item(title: "Категория 2"),
            Item(title: "Категория 3"),
            Item(title: "Категория 4"),
            Item(title: "Категория 5"),
            Item(title: "Категория 6")
        ]
    }

    func numberOfViewControllers(in pageboyViewController: PageboyViewController) -> Int {
        return 6
    }
    
    func viewController(for pageboyViewController: PageboyViewController, at index: PageboyViewController.PageIndex) -> UIViewController? {
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "selectedCategoryVC") as! ProductsCollectionViewController
        
        return vc
    }
    
    func defaultPage(for pageboyViewController: PageboyViewController) -> PageboyViewController.Page? {
        return nil
    }

}
```


And ProductsCollectionViewController

```
extension ProductsCollectionViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let width = (self.collectionView?.frame.size.width)! / 2
        let height = width * 1.28
        return CGSize(width: width, height: height)
    }
}

class ProductsCollectionViewController: UICollectionViewController {
    
    // MARK: UICollectionViewDataSource

    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 5
    }

    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! ProductCollectionViewCell
        cell.layer.borderWidth = 0.3
        cell.layer.borderColor = UIColor.lightGray.cgColor
        
        cell.productImageView.backgroundColor = getRandomColor()
        cell.productNameLabel.text = "Имя продукта \(indexPath.row)"
        cell.productWeightLabel.text = "вес \(CGFloat(drand48())*2)"
        cell.inCartButton.setTitle("Заказать от \(CGFloat(drand48())*2) Р", for: .normal)
    
        return cell
    }
    
    func getRandomColor() -> UIColor {
        let randomRed: CGFloat = CGFloat(drand48())
        let randomGreen: CGFloat = CGFloat(drand48())
        let randomBlue: CGFloat = CGFloat(drand48())
        return UIColor(red: randomRed, green: randomGreen, blue: randomBlue, alpha: 1.0)
    }

}
```

**Comment by msaps** [comment]
@Xotab4ik I've just added a quick troubleshooting guide for automatic insetting, would you be able to check it out and see if it improves the situation? [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md#automatic-insetting)

Also make sure you are using [1.0.6](https://github.com/uias/Tabman/releases/tag/1.0.6) 👍

**Comment by zalogatomek** [comment]
@msaps Hi, I've other inset-related problem.

My view hierarchy: 
- Some `ViewController`, embeded in `UINavigationController` with `CustomView` on top, and `ContainerView` below
- `CustomView` is pinned to `SafeArea`'s on top, leading and traililng
- `ContainerView` is pinned to superview's bottom, leading and trailing and embeds `TabmanViewController`.
- `TabmanViewController` has few view controllers, all with only `UITableView`
- Table views are pinned to superview top, leading, bottom and trailing

Now, when I scroll cells are.. "squizing", like this:

![Before scroll](https://user-images.githubusercontent.com/19666393/33180443-fb324b9c-d06c-11e7-8cb1-138bf43e4de0.png)

![During scroll](https://user-images.githubusercontent.com/19666393/33180468-11e66bb6-d06d-11e7-8100-22aea94217cf.png)

I needed to hide some user elements, but I hope this hierarchy is understandable.

Also, when I pin `UITableView` top to `SafeArea`, cells are not squizing, but I have gap between tableView and `TabmanBar`, like this:

![Pinned to SafeArea](https://user-images.githubusercontent.com/19666393/33180706-e6b9bfd2-d06d-11e7-84a2-c89d767c3bd5.png)
