### ISSUE TITLE
Image above title

### ISSUE THREAD

**Issue by sregg** [uias/Tabman#169]
Is it possible to show the image above the title instead of on its left as it is by default?

**Comment by msaps** [comment]
Currently not, but will see if I can make it configurable in an update 👍

**Comment by sregg** [comment]
Thanks @msaps !
If I manage to add that config in my fork would you be interested in a PR?

**Comment by msaps** [comment]
@sregg yeah sure that would be great! 😄

**Comment by msaps** [comment]
@sregg going to close this -  TM 2 has much better (and simpler) support for custom button layouts and such 😄 🎉
