### ISSUE TITLE
Strange behavior with UITableViewController using Tabman 0.8.3 with swift 3

### ISSUE THREAD

**Issue by Mohammed-Eliass** [uias/Tabman#173]
I'm using two of UITablViewController in the storyboard to be each of them one tab and the data source will be downloaded from api for each of them separately.

The strange behavior will be in the next tab in my case `General News` then after going to the previous tab back and forth the strange behavior gone
see the gif please.

http://gph.is/2hg7fTV

**Comment by msaps** [comment]
@Mohammed-Eliass yeah this looks like issues with the auto-insetting system that Tabman uses. This has been updated recently to fully support iOS 11 and a lot of issues have been resolved, however these are only available in the latest versions of Tabman, which only support Swift 4 and above.

I recommend you update your project to use Swift 3.2 and use the newer versions of Tabman (`v1.0.5`) with Xcode 9.
