### ISSUE TITLE
different title font on selection

### ISSUE THREAD

**Issue by anneWe** [uias/Tabman#174]
Hi, thanks for this great library. I have a question according the appearance options. Is there a possibility to have a different font for the title on selection? I have only found the possibility to adjust the color value on selection.

**Comment by anneWe** [comment]
also it would be great to have the ability to change the accessibilityLabel and accessibilityTraits of the title buttons.

**Comment by msaps** [comment]
Hey!

In regards to the font question, this isn't possible due to not being able to transition nicely between different fonts, please see #51 for a more detailed explanation.

Will try and get some accessibility improvements in an update! 🙂

**Comment by msaps** [comment]
@anneWe the accessibility improvements are now available as of [1.1.0](https://github.com/uias/Tabman/releases/tag/1.1.0)
