### ISSUE TITLE
How to control preferredStatusBarStyle by view controller

### ISSUE THREAD

**Issue by annjawn** [uias/Tabman#175]
I have implemented Tabman with 4 child viewControllers. I want to have `preferredStatusBarStyle` for just the first VC with `.lightContent` but the other VCs I want the `preferredStatusBarStyle` to be default. However I am noticing that setting this

```
override var preferredStatusBarStyle: UIStatusBarStyle{
        return .lightContent
    }
```

in the first VC is partially working, as in, the status bar remains dark when the VC is loaded, once i change to a different VC (using the Tab Bar button) and go back in to first VC it appears white. I am confused by this behavior.  I don't want to set the `preferredStatusBarStyle` at the tabman VC level which changes the `preferredStatusBarStyle` for all the VCs. How do I manage this correctly?

**Comment by msaps** [comment]
@annjawn it sounds as though this is a bug somewhere in Pageboy, as this is what handles all the page view controller logic. I will investigate and see if I can find a fix. 

The desired behaviour would of course be that the `preferredStatusBarStyle` dictates the status bar appearance when that view controller is visible in the page view controller.

**Comment by annjawn** [comment]
@msaps thanks. Something similar I noticed but unrelated to status bar. My first vc has a UIView and a Scrollview stacked inside a stackview and the scrollview has a table view in it. The VC has some animation on it but I notice that when the VC first loads the top constraint is kind of offset by about -20 every time. It comes back to the correct constraints after I switch back and forth the child VCs. To isolate the issue I put my first VC elements in a ViewController in a project that doesn't have Tabman/Pageboy and the results are correct but somehow with Tabman/Pageboy something is going wrong with a combo of uiview and scrollview which is pushing the whole view up overlapping the status bar at first load. I am not entirely sure if it is pageboy or Tabman. Thankfully I have a first VC as a splash screen which is not handled by Pageboy and is embedded in a navigation controller and I push the Tabman VC on top after loading which seems to have fixed the issue. From what I understood that all the Tabman/Pageboy VCs are loaded at once when the app fires up, that is, the ViewDidLoad which is where it loads with the incorrect constraint offset. I saw the other offset issue here that was reported by others related to scrollview/tableview but that didn't help much.

**Comment by msaps** [comment]
@annjawn I've fixed the issues with status bar styling in the latest version of Pageboy, [2.0.3](https://github.com/uias/Pageboy/releases/tag/2.0.3) so please update your Pageboy dependency 👍 

The auto insetting behaviour is next on my list to look at, and will hopefully releasing an update to Tabman which fixes the issues with it shortly. 

Please let me know how you get on with the latest version of Pageboy. 😄
