### ISSUE TITLE
scrollIndicatorInsets off on iPhone X in landscape

### ISSUE THREAD

**Issue by mobru** [uias/Tabman#178]
I use Tabman (1.0.5) with some UITableViewControllers, and noticed that the scrollIndicator is cut off by the iPhone X's sensor bar if the device is in landscape orientation, as if it is ignoring the safeArea / layoutMargins:

![pasted image at 2017_11_07 04_08 pm](https://user-images.githubusercontent.com/2891994/32500643-2fb3f788-c3d6-11e7-89d6-1d115353477f.png)

**Comment by msaps** [comment]
@mobru okay will check it out and see if I can find a fix 👍

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
