### ISSUE TITLE
Very high CPU and Memory usage

### ISSUE THREAD

**Issue by annjawn** [uias/Tabman#179]
I might have to post the real numbers from my app in development for this. But, it seems that there is an extremely high CPU and Memory usage as a result of using Pageboy/Tabman. To think that there may be other issues in my code is fair. So I started looking at my API calls, and found that most of them are passive, non-polling calls and are made only on ocassional user interactions. As far as Graphics is concerned, 1 out of the 4 child ViewControllers has nominal graphics effect that too mostly user interaction based. My app has a total of only 6 VCs out of which 4 VCs are Tabman child VCs and the rest two are informational popups. At this setup, I am getting somewhere around 156 to 250MB plus memory usage at times and CPU usage to around 60% to 70%. 

To isolate the situation, i implemented a simple basic TabBarController and replaced the Tabman controller with it. Hooked up my 4 child VCs to the TabBarController and ran the app with similar setup with no other code changes whatsoever and noticed a drastic improvement in both CPU and memory. Memory hovered around 130 to 145 MB at completely idle situations and CPU was very low at about 5% with user interaction and about 0% with idle.

I also noticed that Tabman is extremely taxing on iOS 10. My iphone 6S plus had major battery drains while testing the app using Tabman. I will need to test it now with a normal TabBarController on the physical device. I will do a little more playing around to see what is going on especially with the Child VCs remaining in memory with Tabman and the effects of it. But I just wanted to get this out in the list.

**Comment by msaps** [comment]
@annjawn thanks for this, I will certainly investigate!

I just did a check on Pageboy (which handles all the View Controller management / page view controller stuff) and it is initializing / deinit'ing as expected with itself and it's child view controllers. So I will check out Tabman and see if anything suspicious is occurring internally that could be causing memory issues. 

Again, on my check with Pageboy (granted these are just example view controllers with not much content), the CPU usage / energy consumption was low and normal for a page view controller, even with hundreds of pages.

Will let you know if I find anything in Tabman. 👍

**Comment by annjawn** [comment]
Thanks for looking. Great work on fixing the issues. 👍

**Comment by annjawn** [comment]
**UPDATE:**

I tested the app with a regular TabBarController subclass on iPhone 6s, 6sPlus, and 7 and I am definitely noticing some very good overall improvements. I don't have an 8 or an X with me but I will have one of those phones in a few days, but I can't imagine it running any worse on any of those phones.

**Comment by msaps** [comment]
@annjawn okay cool. We shouldn't really be getting performance issues on any of those devices anyway. Another thing to test if possible, could you try updating your app to use a `PageboyViewController` rather than a `TabmanViewController` to isolate whether Tabman is causing the performance issues in some way?
