### ISSUE TITLE
IB Designable error

### ISSUE THREAD

**Issue by sasojadrovski** [uias/Tabman#182]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

The latest version of Tabman produced an IB Designable error with the following description:

> Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (ECl-5t-XGQ): dlopen(Tabman.framework, 1): Library not loaded: @rpath/Pageboy.framework/Pageboy
  Referenced from: Tabman.framework
  Reason: image not found

### Other useful things

/

Could you please take a look? This was not present in earlier versions of the library.

Cheers!

**Comment by msaps** [comment]
@sasojadrovski that is very strange! Considering there are no `IBDesignable` classes at all in either Tabman or Pageboy. Any of the recent Tabman updates shouldn't have anything to do with this (as they have nothing to render). 

A few things to try... 

- Quit Xcode (A restart doesn't hurt either)
- Delete your derived data
- run `pod deintegrate` (or delete your Carthage folder if you're using that).
- reinstall your dependencies - `pod install` etc.
- Open & Clean your project (Cmd + Shift + K)
- Attempt to build.. 

Let me know how you get on!

**Comment by sasojadrovski** [comment]
Hey @msaps,

I did all of the above and the issue seems to be resolved. I guess this is Xcode playing silly again. Thank you and sorry for bothering you.

Cheers!
