### ISSUE TITLE
Auto insetting is not working on iOS 10 for non scrolling view

### ISSUE THREAD

**Issue by sregg** [uias/Tabman#193]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Auto insetting is not working with iOS 10 when the child view controller's root view is not a `UISrollView` but just a regular `UIView`.
It's working fine on iOS 11.

I have a `TabmanViewController` with 2 tabs, the child view controller of the first one has a `UITableView` and the auto insetting is working fine. On both iOS 10 and 11.

The second tab is a regular `UIView` with a `UIStackView` pinned to the SafeArea. 
This one is working fine on iOS 11 but not on iOS 10.
I tried to pin to the Superview but then both iOS 11 and iOS 10 are not working.

Let me know if you need a sample project to show you the issue.

Simon.

**Comment by sregg** [comment]
Please find attach the sample project to reproduce the issue:
[SampleTabmanAutoInsetIssue.zip](https://github.com/uias/Tabman/files/1504262/SampleTabmanAutoInsetIssue.zip)

Also here's some screenshots:

On iOS 10, not working: 
![image](https://user-images.githubusercontent.com/1479283/33244886-2be725ac-d2b4-11e7-8654-d23f2a56b825.png)

On iOS 11, working:
![image](https://user-images.githubusercontent.com/1479283/33244923-28c25b98-d2b5-11e7-8494-8951d35734b5.png)

Hope this helped.

**Comment by msaps** [comment]
@sregg thanks for all the detail!

Unfortunately the auto-insetting behaviour in non-scroll views can only work in iOS 11. Apple didn't allow modification of any of the root view layout guides pre-iOS 11, and we can only now do it through `additionalSafeAreaInsets` (which doesn't function in iOS 10). 

I should probably make this clearer in the documentation, but there is unfortunately no clean way (other than a custom child view controller type) to provide this automatically without using scroll views when not running iOS 11. 😭

**Comment by sregg** [comment]
Thanks @msaps for the clarification!
What do you recommend me to do?
Should I pass the `requiredInsets` to the 2nd tab child controller `if #available(iOS 11, *)` ?

**Comment by msaps** [comment]
@sregg you could either adapt your view controller to use a scroll view (that isn't scrollable) which would then allow it to be automatically insetted, or as you said pass along the inset information to the child view controller in some form. 

I should probably have a look at the best way to do this, and make some things easier to access in the child VC's - will raise a separate issue. 😄

**Comment by sregg** [comment]
Thanks @msaps!
I really like Tabman and I'm very happy to see you're actively improving it.
Keep up the good work!
