### ISSUE TITLE
Tab bar title

### ISSUE THREAD

**Issue by shejis** [uias/Tabman#196]
Is it possible to show the tab bar title in two lines 
<img width="294" alt="screen shot 2017-11-29 at 10 06 27 am" src="https://user-images.githubusercontent.com/11069712/33358194-14b25916-d4ed-11e7-9393-a0d94adf25a2.png">

**Comment by msaps** [comment]
@shejis not currently with the built in layouts, but you could [create a custom bar](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md#creating-a-custom-tabmanbar) to achieve that layout...
