### ISSUE TITLE
iOS 11 Large titles

### ISSUE THREAD

**Issue by Mazorati** [uias/Tabman#198]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When using:
`self.navigationController?.navigationBar.prefersLargeTitles = true`
in TabViewController, and UITableViewControllers as viewControllers - everything OK, but navigation not collapsing when i scroll tableview.
How to connect scrolling with LargeNavigation?

Thank you

### Other useful things

Code: https://github.com/Mazorati/test8/blob/master/test8/ViewController.swift

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/3396425/33394699-37688dd8-d554-11e7-9255-61d1bef52009.gif)
![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/3396425/33394702-378ccd9c-d554-11e7-99e3-af9b5116b85d.gif)

**Comment by msaps** [comment]
@Mazorati this is more relatable in Pageboy, as that handles all the page view controller stuff. Will close and use uias/Pageboy#122 for discussion
