### ISSUE TITLE
Example Project won't run

### ISSUE THREAD

**Issue by Junaid6305** [uias/Tabman#199]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

I'm trying to run the example project (version 0.8) in Xcode 8.3.3 but I get the error "No such module 'Pageboy' " in 'TabmanBar+Protocols.swift' when I try build it even though I can see the framework in in the project. An issue like this was raided but then closed without any answer.

**Comment by msaps** [comment]
@Junaid6305 have you run ‘carthage bootstrap —platform iOS’ to install the dependencies?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Junaid6305** [comment]
Yes it did. I’m not exactly sure what the issue but I reinstalled Carthage, tried version 0.8.0 instead of 0.8.3 and it seems to be working now.

**Comment by msaps** [comment]
@Junaid6305 strange, but glad you got it sorted!
