### ISSUE TITLE
Step by step 

### ISSUE THREAD

**Issue by wesleyaoyama** [uias/Tabman#211]
Hi,

Do you have a step by step tutorial or a xcode project example to implement the tabman? With only the basics usage described in the main page is not working for me. I need a tab with two itens, and when I touch them it will show one view (uiView) or another uiView, I don't need to call another view controllers.

![tab](https://user-images.githubusercontent.com/34511213/33940198-36588294-dff5-11e7-91ef-e28f72d21c25.png)

Thanks,

Wesley

### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@wesleyaoyama Tabman only really supports transitioning between view controllers, it's not designed to swap between `UIView`s. What's your reason for not wanting to use multiple view controllers out of interest?

**Comment by wesleyaoyama** [comment]
@msaps, I can change my app to switch between VCs, but I tried in another test project using the code in the Code section and it didn't work, do you have a simple example of a project that it's working?

**Comment by msaps** [comment]
@wesleyaoyama what didn't work from the readme?? There is an example app available in the repo 😄
