### ISSUE TITLE
scrollsToTop not working with child scrollViews.

### ISSUE THREAD

**Issue by MichaelDanielTom** [uias/Tabman#216]
Hey guys,
I have a tableViewController as one of the children of a tabmanViewController, and have it scroll to the top when a user taps on the status bar, but something is preventing that from happening. I only have a single scrollView/tableView subclass in all of my child viewControllers to tabmanViewController, so I don't think that's the problem. I tried to manually set the tabmanViewController's pageViewController's scrollview's scrollsToTop to false, but this isn't working either.

Any help is appreciated!

**Comment by msaps** [comment]
@MichaelDanielTom apologies for taking so long to get back to you! Christmas and all that 😅 

That is very strange, as by default this behaviour does work in a basic Tabman implementation. You shouldn't have to mess with any properties. Are you doing anything with gestures in your child view controllers?

**Comment by MichaelDanielTom** [comment]
Thanks for the response! It actually magically started working again, not entirely what changed (besides iOS and xcode versions). Closing this since it's not reproducible anymore.
