### ISSUE TITLE
I want to make a custom indicator

### ISSUE THREAD

**Issue by Nicejinux** [uias/Tabman#223]
Hi.

I wanted to make a custom indicator like this, and I've almost done.
(scrollingButtonBar + custom indicator)

![tabbar_image](https://user-images.githubusercontent.com/806744/34684818-b8ec2784-f4e9-11e7-8848-1a8d363f80b0.png)

but, I can't change the color which is for selected tab button.
I set `state.color` and `state.selectedColor` but it doesn't work.

How can I change the selected button's text color?

### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@Nicejinux hey! Thanks for the PR's on the documentation 👍 

That's strange, how are you setting the appearance properties on your bar?

**Comment by Nicejinux** [comment]
First of all, Thanks for merging my PR.

I found the reason.

When I customize an **Indicator**, `TabmanItemColorCrossfadeTransition.self` should be returned in the `itemTransitionType` method, but _nil_ is returned.
So, I think you should test `CustomIndicator` and check PR #215.

Thanks.

**Comment by msaps** [comment]
@Nicejinux ah got you! I've merged it and will get it into a release ASAP 😄

**Comment by msaps** [comment]
@Nicejinux now available in [1.4.0](https://github.com/uias/Tabman/releases/tag/1.4.0) 🎉
