### ISSUE TITLE
Type 'UILayoutPriority' (aka 'Float') has no member 'required'

### ISSUE THREAD

**Issue by avivInmanage** [uias/Tabman#232]
### New Issue Checklist

- [1.4 ] Updated Tabman to the latest version
- [1.4 ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
in clas UIView+AutoLayout in functions: pinToSafeArea, pinToSuperviewEdges, pinToSuperviewEdge, pinEdge, match, set, alignToSuperviewAxis

i get the error on  UILayoutPriority = .required appears:
Type 'UILayoutPriority' (aka 'Float') has no member 'required'

**Comment by msaps** [comment]
@avivInmanage Hi, what version of Xcode and Swift does your project use?

**Comment by avivInmanage** [comment]
xcode 9.1 swift 5

**Comment by avivInmanage** [comment]
swift 4*

**Comment by msaps** [comment]
@avivInmanage hmm that's strange, it's not similar to [this issue](https://github.com/SnapKit/SnapKit/issues/454) that was experienced in SnapKit is it?

**Comment by avivInmanage** [comment]
= .required makes an error

**Comment by FrancoisObob** [comment]
same here !

**Comment by msaps** [comment]
@FrancoisObob @avivInmanage have you tried integrating with the latest version of CocoaPods (`1.4.0`)? This is supposed to have fixes for Swift language version support
