### ISSUE TITLE
Viewcontroller not show

### ISSUE THREAD

**Issue by JqyModi** [uias/Tabman#234]
### Issue Description
    private var viewControllers = [UIViewController]()

    
    var papers: [Paper] = [Paper]()
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        loadData()
        
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor.init(white: 0.96, alpha: 1.0)
        self.dataSource = self
       
    }
    
    private func initializeViewControllers(papers: [Paper]) {
        var viewControllers = [UIViewController]()
        var barItems = [Item]()
        
        for index in 0 ..< papers.count {
            let viewController = ExaminationViewController()
            viewController.paper = papers[index]
            barItems.append(Item(title: "Page No. \(index + 1)"))
            viewControllers.append(viewController)
        }
        
        bar.items = barItems
        self.viewControllers = viewControllers
    }
    
    private func loadData() {
        YMNetworkTool.shareNetworkTool.getPaper(paperId!){ [weak self](items) in
            self?.papers = items
            self?.initializeViewControllers(papers: (self?.papers)!)
            print("papers.count  = \(self!.papers.count)")
            if items.count>0 {
                print("题目条数：\(items.count)")
            }else{
                print("暂无内容")
            }
        }
    }

    
    func numberOfViewControllers(in pageboyViewController: PageboyViewController) -> Int {
        
        return self.viewControllers.count ?? 0
    }
    
    func viewController(for pageboyViewController: PageboyViewController, at index: PageboyViewController.PageIndex) -> UIViewController? {
        
        return self.viewControllers[index]
    }
    
    func defaultPage(for pageboyViewController: PageboyViewController) -> PageboyViewController.Page? {
        return nil
    }
}

### Other useful things
![image](https://user-images.githubusercontent.com/19703476/35143994-35139390-fd3e-11e7-975f-0c10bbf9e903.png)

**Comment by msaps** [comment]
@JqyModi you are setting the `dataSource` in `viewDidLoad` but the view controller initialisation does not take place until `viewWillAppear` so at the time the data source checks the view controller array is nil.

Try calling `reloadPages()` at the end of `initializeViewControllers()`
