### ISSUE TITLE
How to adjust the Bar Items Header spacing

### ISSUE THREAD

**Issue by sujalshrestha** [uias/Tabman#240]
### New Issue Checklist

- [☑️] Updated Tabman to the latest version
- [ ☑️] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ☑️] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I am not figuring out how to manage the spacing of the tab bar items when only one or two titles are present. I want only two tab bar items with their heading placed near the center but its alligned to the left side. I have also attached the image.
### Other useful things

<img width="319" alt="screen shot 2018-02-01 at 13 18 37" src="https://user-images.githubusercontent.com/15883973/35666715-2ac07ec0-0753-11e8-81ad-25c63919f7e3.png">

**Comment by msaps** [comment]
@sujalshrestha you might want to take a look at the [Layout Appearance docs](https://github.com/uias/Tabman/blob/master/Docs/APPEARANCE.md#layout) and set your custom appearance parameters like this:

```swift
bar.appearance = TabmanBar.Appearance({ (appearance) in
     // custom appearance here  
})
```

**Comment by sujalshrestha** [comment]
Thanks. I think i solved this issue. But i only need a validation before scrolling to next VCs. I have a form in each VCs and the user should be able to scroll to the next VCs only when all the form fields are filled. Is there any way to control the scrolling as well the clicking of bar items button

**Comment by sujalshrestha** [comment]
@junweimah 
You can check Layout Apperance docs :)

**Comment by luangs7** [comment]
How difficult is to explain what you did? @sujalshrestha
