### ISSUE TITLE
When scrolling to the next viewcontroller and coming back the viewDidLoad gets called again.

### ISSUE THREAD

**Issue by sujalshrestha** [uias/Tabman#241]
### New Issue Checklist

- [✔ ] Updated Tabman to the latest version
- [✔️] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [✔️] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When scrolling to the next viewcontroller and coming back the viewDidLoad gets called again. I have uitextfields in each VC and when going back and forth from the VCs the viewdidload gets called again and refreshes the uitextfield. Is there any solution for this?

**Comment by msaps** [comment]
@sujalshrestha how are you returning your view controllers? Are they being initialised every time they are called for in `viewController(for pageboyViewController: at index:)`?

**Comment by sujalshrestha** [comment]
Thanks. I think i solved this issue. But i only need a validation before scrolling to next VCs. I have a form in each VCs and the user should be able to scroll to the next VCs only when all the form fields are filled. Is there any way to control the scrolling as well the clicking of bar items button

**Comment by msaps** [comment]
@sujalshrestha other than entirely disabling scrolling with `isScrollEnabled` there is no way to disable scrolling for particular page transitions - apologies for the delay in response.
