### ISSUE TITLE
TabItem transition animations

### ISSUE THREAD

**Issue by otymartin** [uias/Tabman#244]
Hey @msaps 
This is to further discussion on the tabItem transitions that I opened in pageboy.
![nav](https://user-images.githubusercontent.com/2222881/35822513-88302edc-0a7a-11e8-9dbb-1e7a3f177046.gif)

I'm convinced you are performing quite abit of dark magic on your end as I couldn't really follow your code to find anywhere where you control the transition of the items relative to the scroll of the page.

I managed to get a tinybit of the behaviour I wanted by just spacing the items with 110 points inter-item spacing however I can't figure out if your code either manipulates the individual item positions or the entire bar itself. 

My hope is to add easing functions to the animation transitions to create a more fluid flow as seen above as opposed to the very static behaviour below.

![tabmandarkmagic](https://user-images.githubusercontent.com/2222881/35822486-6c4bf4e4-0a7a-11e8-962a-4ea7ebcedd4b.gif)

**Comment by msaps** [comment]
@otymartin are you using a custom bar here or manipulating one of the built in bars?

You can find the logic for the transitioning here: [TabmanBar Transitioning](https://github.com/uias/Tabman/tree/master/Sources/Tabman/TabmanBar/Transitioning)

This is all internal and not publicly visible - I'm currently on with rewriting how `TabmanBar` works to make it much better for a v2.0! 😅

My advice would be to definitely go the entirely custom route and maybe take inspiration from the item transitions included in Tabman.

**Comment by otymartin** [comment]
@msaps I actually couldn't figure out your code at all so resorted to attempt to figure it out with a basic UIView and UIButtons and leveraging the PageboyViewControllerDelegate to move them in a [playground project](https://github.com/otymartin/Tabman-SlideStyle.git). Haven't accomplished it yet since its freakishly hard behaviour to control but will see what I can do.

**Comment by otymartin** [comment]
@msaps I managed to achieve the behaviour i was looking for with a Basic UIView & UIButtons in this [example project](https://github.com/otymartin/Tabman-SlideStyle/tree/master/Tabman%20SlideStyle).
If it can spark some ideas for how TabBar 2.0 should function behave or be capable of that would be cool :)

**Comment by msaps** [comment]
@otymartin okay cool that's great! I'll take a look and see what I can do 🤓

**Comment by msaps** [comment]
@otymartin just revisiting old issues on here - from what I can tell this should be way easier in Tabman 2 and the [Tinderbar](https://github.com/uias/Tinderbar) project pretty much does it! 😄 

Going to close this, and if this is still a problem and I'm talking rubbish feel free to open a new issue! 🍺

**Comment by otymartin** [comment]
Thanks, @msaps really appreciate you coming through on this 🍺🍺. My only problem these days it appears the Pageboy, Tabman even TinderBar example projects simply don't run on my end. Perhaps I need to have Carthage or something(I use Cocoapods) no clue. But looking forward to creating some magic with it 🥇

**Comment by msaps** [comment]
@otymartin ah yeah you do need Carthage to build the projects locally - should document that 😁 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by otymartin** [comment]
@msaps Yep good idea. I don't think it's as common especially with new devs as Cocoapods is.

**Comment by sugitatestblue** [comment]
I wanna remove paging transitioning animation

**Comment by sugitatestblue** [comment]
```
 
        barView.layout.transitionStyle = .none
        barView.buttons.transitionStyle = .none
```

not work.
