### ISSUE TITLE
How implement the center align without shifting (static)

### ISSUE THREAD

**Issue by fmaxx** [uias/Tabman#245]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I have with  .centered:
https://www.dropbox.com/s/ubhaw7wqxbrmt03/2018-02-06%2022.03.26.png?dl=0

But I'd like to implement:
https://www.dropbox.com/s/62sozowf6ouynk3/LectureApp.sketch%202018-02-06%2022-04-26.png?dl=0

Could you explain?

**Comment by msaps** [comment]
@fmaxx using a `.buttonBar` style should give you the desired effect. Items are distributed equally in the bar rather than scrollable?
