### ISSUE TITLE
Auto insets incorrect after subsequent viewings

### ISSUE THREAD

**Issue by Vortec4800** [uias/Tabman#250]
This is on the latest version from Cocoapods. Basic layout is UINavigationController -> Tabman -> UIViewController subclass. Both the navigation controller and Tabman have opaque bars.

On the first display of each tab, the insets are correct and content appears below both bars. This is using all the default auto insetting logic. However when switching to a different tab and then returning to an already-shown tab, the insets are set incorrectly. Instead of being set to top inset of 41, it's set to zero and content is behind the Tabman bar. These are recycled view controllers, they are created once on initial load and the same controller is shown for that tab each time.

Digging into this, it appears this is happening because in the AutoInsetter class, on line 133, the insetter looks for a customTopInset value that matches the `scrollView.contentInset.top - previousContentInset.top` which in my case is `0.0 - 41.0 = --41.0` which is then added to the required content inset calculated already, which equals zero instead of the 41 I actually need.

When this works correctly, the previousContentInset isn't set yet because it's the first time around, and the math looks like `0.0 - 0.0 = 0.0` and the required inset isn't modified, so it's set correctly to 41.

Perhaps the issue is that our currentScrollViewInsets array thinks our scroll view's inset is already set to 41, but when it does the calculation the inset is actually set to zero. Do you know why our scroll view inset would have reset itself? Is there anything else I can provide to help track this down?

I've created a sample project that illustrates this issue on the iPhone 8 sim running 11.2.

[InsetTest.zip](https://github.com/uias/Tabman/files/1711793/InsetTest.zip)

**Comment by msaps** [comment]
@Vortec4800 just released AutoInsetter [1.2.1](https://github.com/uias/AutoInsetter/releases/tag/1.2.1) which should fix the issues you have been seeing! 🎉 

Run `pod update AutoInsetter` and fingers crossed all should be well 🤞

**Comment by Vortec4800** [comment]
Awesome, thank you so much for giving this a quick fix!

**Comment by perfectionaq** [comment]
Im still having this issue even after updating

**Comment by perfectionaq** [comment]
I noticed that if the view controllers were created before the viewController() method in the delegate, everything works fine and the insets are correct. But, if the view controllers are created in the viewController() method, then the insets are wrong after scroll to another page.
