### ISSUE TITLE
How to Update Tabbar Item title dynamic 

### ISSUE THREAD

**Issue by aman198** [uias/Tabman#252]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@aman198 this might work, but needs some investigation - It wasn't a use case I envisaged.
