### ISSUE TITLE
In parent vc, when i am in child 1, how to I programmatically go to child 2?

### ISSUE THREAD

**Issue by junweimah** [uias/Tabman#253]
Let's say my design is like this : 

Parent > Child 1, child 2

And I am currently at parent's child1, how do I go to child 2 on a button click (lets say) from child 1?

**Comment by msaps** [comment]
The following should work:

```swift
self.parentPageboyViewController?.scrollToPage(.next, animated: true)
```

There is also an optional completion closure if required (Pageboy handles all the 'paging' logic) 🙂.

**Comment by junweimah** [comment]
Yes thank you

Solved
