### ISSUE TITLE
Tabman fails build with Carthage

### ISSUE THREAD

**Issue by OskarGroth** [uias/Tabman#254]
```
Checkouts/Tabman/Sources/Tabman/TabmanBar/TabmanBar+Insets.swift:10:8: error: no such module 'AutoInsetter'
import AutoInsetter
       ^
```

**Comment by msaps** [comment]
@OskarGroth are you correctly integrating the AutoInsetter framework into your project? It became a dependency of Tabman in 1.5.

**Comment by OskarGroth** [comment]
This is a carthage error when running `carthage update` of a project that includes Tabman in it's cartfile. It seems like AutoInsetter is not being included in the Tabman framework, like it does with Pageboy.

**Comment by msaps** [comment]
@OskarGroth  I'm no expert at Carthage at all, so it could probably be an error on this end, but it seems to work when building for me: 

<img width="967" alt="screen shot 2018-02-14 at 10 28 21" src="https://user-images.githubusercontent.com/3515448/36197092-18799286-1173-11e8-8771-0156605ce521.png">

Example project:
[TabmanCarthageTest.zip](https://github.com/uias/Tabman/files/1723371/TabmanCarthageTest.zip)

Any pointers would be much appreciated 😄

**Comment by OskarGroth** [comment]
Works now 👍 It was just an error on my end!
