### ISSUE TITLE
How to check when user slides to next VC? (Add listener or call an action when user slides to next VC)

### ISSUE THREAD

**Issue by sujalshrestha** [uias/Tabman#255]
### New Issue Checklist

- [✔️] Updated Tabman to the latest version
- [✔️] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [✔️] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I have different forms in each VC and i want to validate the form when user slides to the next VC. How can i know when user slides or begins sliding to the next VC? Is there any listener method or any functions i can call when user slides to next vc?

**Comment by msaps** [comment]
@sujalshrestha all of the Pageboy delegate enhancements are available in `TabmanViewController` as it inherits from `PageboyViewController` - check out the docs [here](https://github.com/uias/Pageboy#delegation)
