### ISSUE TITLE
Unable to run the demo project with `pod try`

### ISSUE THREAD

**Issue by richardtop** [uias/Tabman#256]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Unable to run the demo project with `pod try`

Steps to reproduce:

1. Run `pod try` in the terminal
2. Try to build target `Tabman-Example`
3. Build fails
![image](https://user-images.githubusercontent.com/8013017/36309241-84ef71d2-132c-11e8-9e1b-cdf1e2d95525.png)

**Comment by OskarGroth** [comment]
`pod try` just opens the demo project, no? Maybe you should try running `pod install` first, as hinted by your error.

**Comment by richardtop** [comment]
@OskarGroth in most other libraries `pod try` works fine. I.e. I can run the project without running `pod install`. So, it's definitely a bug.

**Comment by OskarGroth** [comment]
@richardtop This library relies on external dependencies. They do not belong inside this repo, and as such must first be installed with `pod  install`. This is common practice. The issue you describe is a shortcoming of https://github.com/CocoaPods/cocoapods-try and not this library.

**Comment by msaps** [comment]
@OskarGroth @richardtop having looked into it, it probably is something with Tabman. I don't think `pod try` likes the different targets that Tabman has (because of Carthage support 🙃) - I'll try and investigate and see what I can do to fix it.
