### ISSUE TITLE
Different font on first item

### ISSUE THREAD

**Issue by sbravotalero** [uias/Tabman#257]
### Issue Description

The first item appears with a different font than the others on iOS 11. This is how the appereance is being configured:

bar.appearance = TabmanBar.Appearance({ (appearance) in
            appearance.style.background = .solid(color: .grey38)
            appearance.state.color = .grey142
            appearance.state.selectedColor = .signatureYellow
            appearance.text.font = UIFont.Geograph.medium.ofSize(16.8)
            appearance.indicator.isProgressive = false
            appearance.indicator.color = .clear
        })

<img width="398" alt="screen shot 2018-02-16 at 11 21 10 am" src="https://user-images.githubusercontent.com/34518418/36317608-887c8c3e-130b-11e8-988b-4e3f4406eb9b.png">

**Comment by msaps** [comment]
@sbravotalero I believe that is due to the fact that Tabman has `adjustsFontSizeToFitWidth` enabled on the bar buttons. Would it be useful to make this behaviour configurable?

**Comment by msaps** [comment]
@sbravotalero just released [Tabman 2](https://uias.github.io/Tabman/master/going-custom.html#custom-bar-buttons) which should have resolved this issue and in general is hopefully a lot better! 😄
