### ISSUE TITLE
How to update Tabbar items title dynamically if come into focus.

### ISSUE THREAD

**Issue by aman198** [uias/Tabman#258]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
Assume this is a duplicate of #252
