### ISSUE TITLE
Cocoapod error

### ISSUE THREAD

**Issue by nuk3dene** [uias/Tabman#26]
pod install shows this error, when i try to install
[!] Unable to find a specification for `Tabman`

**Comment by msaps** [comment]
Hi @nuk3dene, can you try running `pod repo update` and then retry `pod install`?

**Comment by DoubleJ87** [comment]
did not work after 'pod repo update' and then retry 'pod install'
How can I use Tabman?

**Comment by msaps** [comment]
Hi @DoubleJ87 what do you have in your Podfile?

**Comment by DoubleJ87** [comment]
I have below list

pod 'Tabman'
pod 'AKSideMenu'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

**Comment by iAKM** [comment]
There are only pre-release versions available satisfying the following requirements:

	'Tabman', '>= 0'

You should explicitly specify the version in order to install a pre-release version

Pls help.

**Comment by msaps** [comment]
@iAKM @DoubleJ87, is your target platform iOS 8? Tabman only supports iOS 9 and above.
