### ISSUE TITLE
When I embed the tab bar, the bar buttons are not responsive anymore?

### ISSUE THREAD

**Issue by jessicae5** [uias/Tabman#260]
### New Issue Checklist

- [ x] Updated Tabman to the latest version
- [x ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I'm embedding my tab bar, but the tab buttons themselves seem to be not responsive anymore (they are only responsive when I click in the small space below the tab text). Is there a way to increase the button target size (so when you click anywhere around it, the view will switch?)

**Comment by msaps** [comment]
@jessicae5 that's really strange. Does the encompassing view have a correct layout? I.e. is the frame big enough for the bar, as this could impede any touches?

**Comment by jessicae5** [comment]
I'm embedding the tabar in a view that is pushed onto a Navigation View. Visually, the tab bar looks fine (proper placement and positioning and size etc), just the buttons aren't responding. Perhaps there is a way I can modify the target area of the button click?

**Comment by msaps** [comment]
@jessicae5 it seems strange though, as the buttons have a pretty decent touch area, and there shouldn't be anything impeding it. Do you have any gesture recognisers or anything that could be obstructing the touches? 

Would you be able to take a look at the layout inspector and just see if there is anything in the way that you can see?

**Comment by jessicae5** [comment]
I figured it out - the navigation controller was somehow stealing all the touches! Thanks!
