### ISSUE TITLE
Swipe Back feature not working 

### ISSUE THREAD

**Issue by shejis** [uias/Tabman#266]
How to enable the swipe back feature in Tabman.I'm not able to go back to previous viewcontroller from the tabman view using swipeback feature , how i can enable that in tabman

**Comment by msaps** [comment]
@shejis not sure I fully understand, what swipe back feature do you mean? The page view controller should operate like a normal `UIPageViewController`.

**Comment by shejis** [comment]
Hello @msaps  what i mean is How to enable default iOS back swipe gesture, not between two view controllers inside the tab .

**Comment by msaps** [comment]
@shejis Tabman doesn't do anything to affect the operation of the `UINavigationController` gestures. Have you got any custom gestures that could be interfering?

**Comment by shejis** [comment]
I see . But i haven't added any custom gestures to block this feature .

**Comment by shejis** [comment]
@otymartin thanks a lot , right now it is working well  , @msaps  thanks for this wonderful library.

**Comment by SreelekhN** [comment]
to fix this make scroll view fail to gesture when on start position,

private func gestureFirstResponder() {
        if let pageViewController = self.children.first as? UIPageViewController {
            let scrollViews = self.findAllScrollViews(in: pageViewController.view)
            for scrollView in scrollViews {
                scrollView.panGestureRecognizer.require(toFail: navigationController?.interactivePopGestureRecognizer ?? UIGestureRecognizer())
            }
        }
    }
    
    private func findAllScrollViews(in view: UIView) -> [UIScrollView] {
        var scrollViews: [UIScrollView] = []
        for subview in view.subviews {
            if let scrollView = subview as? UIScrollView {
                scrollViews.append(scrollView)
            }
            scrollViews.append(contentsOf: self.findAllScrollViews(in: subview))
        }
        return scrollViews
    }

use this in viewDidLoad
