### ISSUE TITLE
'currentScrollViewInsets' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by orkenserik** [uias/Tabman#267]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@orkenserik any context as to why you think/need this to be public?
