### ISSUE TITLE
Tabman's Auto Insets Don't work on IOS 9.3.5

### ISSUE THREAD

**Issue by hughesyadaddy** [uias/Tabman#271]
### Issue Description
Tabman insets work great on my iphone and simulator, but on my ipad mini, I'm the child views are behind the tabman navigation bar.

**Comment by msaps** [comment]
@hughesyadaddy would you be able to share your view hierarchy?? Also are you on the latest versions of Tabman & AutoInsetter?

**Comment by hughesyadaddy** [comment]
Thanks for the quick response. I'm using the latest version but just read another post where if your using a UIView as the child view controller it doesn't work past ios 10.

**Comment by msaps** [comment]
@hughesyadaddy ah I believe this may be due to the fact that in iOS 11 you can provide custom layout margins, which Tabman uses to inset any non-scrollviews, this does not work on iOS 10 and below.

**Comment by hughesyadaddy** [comment]
Thank you! Figured it out with using a scroll view as suggested. Great job. My last issue is when I switch between View Controllers, there is a flash on the tabman navbar. Is this a typical issue. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25060966/39328392-3a30e11c-4969-11e8-9a44-6386ec9b0c79.gif)

**Comment by msaps** [comment]
@hughesyadaddy haven't seen that before, I'll check it out!
