### ISSUE TITLE
All TabmanBar items initially have the same font when both .font and .selectedFont are set

### ISSUE THREAD

**Issue by sasojadrovski** [uias/Tabman#273]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When using both `TabmanBar.Appearance.Text` properties for `.font` and `.selectedFont`, by default, the `selectedFont` is used for all items until all `TabmanBar` items are tapped at least once. I believe that the expected behavior should be applying the `selectedFont` only for the currently selected tab, even when presenting the items for the first time.

I really hope that this is an easy fix for you and that you will release an update soon :)

Keep up the great work!

Cheers,
Sasho

**Comment by msaps** [comment]
@sasojadrovski this should now be resolved as of [1.8.1](https://github.com/uias/Tabman/releases/tag/1.8.1) 😄

**Comment by sasojadrovski** [comment]
@msaps Indeed, it is resolved 😄 Thank you for looking into it so fast! I really love the improvements for switching back and forth between `.font` and `.selectedFont` during the interactive transitioning. Well done! 👏 

Cheers,
Sasho
