### ISSUE TITLE
'shouldHideWhenSingleItem' is deprecated: Use Behavior.AutoHiding instead

### ISSUE THREAD

**Issue by ahmedsafadii** [uias/Tabman#278]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by ahmedsafadii** [comment]
'bottomSeparatorColor' is deprecated: Use appearance.bottomSeparator.color

**Comment by msaps** [comment]
@ahmedsafadii is this referring the the warnings within the project?

**Comment by ahmedsafadii** [comment]
yeah it's !?

**Comment by ahmedsafadii** [comment]
let hideWhenSingleItem = appearance.state.shouldHideWhenSingleItem ?? defaultAppearance.state.shouldHideWhenSingleItem!


            state.shouldHideWhenSingleItem = false

**Comment by msaps** [comment]
@ahmedsafadii yeah unfortunately I can't remove the usage of the deprecated properties while they are in the project. They will get removed in a future version 👍

**Comment by Jacolack** [comment]
I am still getting this warning with Tabman 2.2. Is there any way to fix it?

**Comment by msaps** [comment]
@Jacolack not sure why, that property has been completely removed in Tabman 2.x. The `appearance` API in general is completely different. 🤔

**Comment by Jacolack** [comment]
My bad, wasn't updated in cocoapods.
