### ISSUE TITLE
Tab selection issue

### ISSUE THREAD

**Issue by andreyoshev** [uias/Tabman#280]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Is it possible to get informed about tab selection, for expample, as at tableView: didSelectItemAtIndexPath?

I found method: 
`func bar(_ bar: TabmanBar,
             didSelectItemAt index: Int,
             completion: (() -> Void)?)`

 but I have an error:

> Overriding non-@obcj declarations from extensions is not supported

**Comment by msaps** [comment]
@andreyoshev you could use `bar(shouldSelectItemAt index: Int) -> Bool` available in `TabmanBarDelegate` as this is called when the bar view is selected? Either that or the Pageboy delegate method for `willScrollToPageAt`?

**Comment by patniemeyer** [comment]
I'm seeing `bar(shouldSelectItemAt index: Int)` being called multiple times with the same index for each tab selection.  Is that expected?

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
