### ISSUE TITLE
Easiest way to set the line type indicator to a custom thickness/height?

### ISSUE THREAD

**Issue by patniemeyer** [uias/Tabman#281]
I see that it's restricted to an enum LineWeight currently.   If I want a custom line weight / thickness should I create a new Indicator impl?  Thanks.

EDIT:

So I just created a new indicator type like this:

```
class MyLineIndicator: TabmanIndicator {
    override public var intrinsicContentSize: CGSize {
        return CGSize(width: 0.0, height: 32.0)
    }    
    public override func constructIndicator() {    }
}
```

and set it:

```
        let appearance = bar.appearance
        appearance?.indicator.preferredStyle = TabmanIndicator.Style.custom(type: MyLineIndicator.self)
        bar.appearance = appearance
```

Might be worth considering adding a ".custom" type to the LineWeight just as you have it for SeparatorHeight.  Perhaps I can submit a tiny PR for this later.

**Comment by msaps** [comment]
@patniemeyer will try and get this implemented 😄

**Comment by msaps** [comment]
Now available in Tabman 2 (Appreciate it's a little late 😅)
