### ISSUE TITLE
Set width of indicator bar equal to text width

### ISSUE THREAD

**Issue by Ankit8946** [uias/Tabman#284]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Is it possible to set width of indicator bar equal to text width..?
I am using the **.buttonBar** type

### Other useful things

Is it possible to set width of indicator bar equal to text width..?

**Comment by OrientPankaj** [comment]
Is it possible to set width of indicator bar equal to text width..?
case .buttonBar:
            appearance.indicator.lineWeight = .thin
            appearance.indicator.compresses = true
            appearance.layout.edgeInset = 8.0
            appearance.layout.interItemSpacing = 0.0
            appearance.layout.minimumItemWidth = 20.0

set  - > appearance.layout.minimumItemWidth = 0.0 ,it's work for me

**Comment by Ankit8946** [comment]
@OrientPankaj your answer doesn't help.. I am looking to achieve the same indicator width as shown when the bar style is .scrollingButtonBar and the width of the indicator is same as the text width.

**Comment by msaps** [comment]
I know its a little late, but this is now the default behaviour in Tabman 2 🙂
