### ISSUE TITLE
RTL Button bar direction

### ISSUE THREAD

**Issue by ahmedsafadii** [uias/Tabman#287]
### New Issue Checklist

- [*] Updated Tabman to the latest version
- [*] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [*] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When the app in RTL mode when i click on the button in the bar the direction of the animation is wrong

**Comment by ahmedsafadii** [comment]
Try to be in RTL Mode and click on the tabs to see the screen direction goes from left to right while in swipe it's work perfect

i attach video for that issue

https://www.youtube.com/watch?v=lY5v9kTjvt8

@msaps

**Comment by ahmedsafadii** [comment]
@msaps :(

**Comment by msaps** [comment]
@ahmedsafadii sorry been busy working on Tabman 2! 😄 

Will try and get this fixed ASAP and patched in a 1.x release.

**Comment by ahmedsafadii** [comment]
thank you very much sir !

i'm waiting that <3
