### ISSUE TITLE
Make self.bar.items part of dataSource

### ISSUE THREAD

**Issue by frogg** [uias/Tabman#288]
I think that the titles of the tabs should be part of the dataSource as well.

instead of
```
self.bar.items = [Item(title: "Page 1"),
                          Item(title: "Page 2")]
```

make it something like
```
func titleForPageAtIndex(index)…
```

**Comment by msaps** [comment]
@frogg going to do a major redesign of Tabman in the near future for 2.0 so will bear this in mind! 😄

**Comment by frogg** [comment]
@msaps cool sounds good 👍 
I have to say I already like the architecture and ease of use of your project a lot! I am using it for my iOS app Processing to display multiple classes of source code next to each other:
![img_3676](https://user-images.githubusercontent.com/5204169/40223076-1be94256-5a82-11e8-9a60-7fb13f3b6293.PNG)

Viele Grüße aus Berlin nach Berlin ;)

**Comment by msaps** [comment]
@frogg just released [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) with a much improved data source mechanism 😄

**Comment by frogg** [comment]
Very nice, thanks for letting me know! I'm quite busy right now with my other app, but I'll put that on my list for 2019 :)
