### ISSUE TITLE
How to make bar userInteraction disabled?

### ISSUE THREAD

**Issue by Jacolack** [uias/Tabman#289]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
The only option for `self.bar.appearance?.interaction.` is `isScrollEnabled`, how would I go about making the bar itself have disabled user interaction?

**Comment by pselok** [comment]
You can try embed bar in a view and disable interaction for this view?

**Comment by msaps** [comment]
@Jacolack there is no prebuilt solution available currently, but @pselok solution should work 👍

**Comment by Jacolack** [comment]
If anyone wants a better work around, I solved this by adding an Override to the`update(forAppearance appearance: Appearance, defaultAppearance: Appearance)` function in the `TabmanFixedButtonBar` class.
