### ISSUE TITLE
Add Fill Item Distribution for Scrolling Button Bar

### ISSUE THREAD

**Issue by rzulkoski** [uias/Tabman#291]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Would like to add fill item distribution for scrollingButtonBar style.

In practice, this would mean that if the items in a scrolling button bar do not use up the available space, the extra space would be divided equally among the items by increasing their width. Otherwise it would behave normally.

### Other useful things

How two tabs are laid out with the current default item distribution of left :
<img src="https://user-images.githubusercontent.com/3171325/40669379-6f89ecbe-632c-11e8-9f73-8cfa0f907b45.png" width="30%" height="30%">

How two, three, and four tabs would be laid out with the proposed item distribution fill:
<img src="https://user-images.githubusercontent.com/3171325/40669440-96bf06fc-632c-11e8-971d-e5d526156f2e.png" width="30%" height="30%"> <img src="https://user-images.githubusercontent.com/3171325/40669860-88e0880c-632d-11e8-96f7-e7aec71b4ebe.png" width="30%" height="30%"> <img src="https://user-images.githubusercontent.com/3171325/40669865-8be62354-632d-11e8-9421-cb9104339b3f.png" width="30%" height="30%">

**Comment by rzulkoski** [comment]
Added in PR #292 .

**Comment by Ankit8946** [comment]
@rzulkoski How is this different from .buttonBar behaviour..?

**Comment by rzulkoski** [comment]
@Ankit8946 In theory, it should behave exactly the same. The difference is that with a button bar when your tabs take up too much space it starts to compress them and then eventually stops rendering if you exceed 5 tabs. With Fill it will seamlessly transition from behaving like a non-scrollable buttonBar to a scrollingButtonBar. This is especially useful if a particular page has a dynamic number of tabs depending on the content or if the user has a smaller device like an SE and you don’t want it compressed for legibility reasons.

We are looking at adopting TabMan for the Hayneedle app to replace XLPagerTabStrip and this is a missing piece of functionality for us.

Let me know if you have any other questions or concerns.

**Comment by msaps** [comment]
@rzulkoski this is now available in [1.9.0](https://github.com/uias/Tabman/releases/tag/1.9.0) 🍾

**Comment by ckalolass** [comment]
I am moving my project to Swift 4.2. I have updated Tabman to 2.4.3 (from 1.9.2) and can't find the way to implement this behavior. Is any way to do it?

**Comment by rzulkoski** [comment]
Hi @ckalolass, we no longer use tabs in the Hayneedle app and subsequently removed Tabman, so I haven't had a reason to port this functionality to newer versions. My understanding is that it should be easier to implement in the newer version that it was in the older version. Do you want to take a stab at it and open a pull request?

**Comment by ckalolass** [comment]
@rzulkoski Thanks for reply. For now we need to keep transition as simple as possible. Just wanted to know that I didn’t miss something. But if I will implement this I will definitely post a PR.

**Comment by nikeshakya** [comment]
I want to implement this behavior but cannot find any options. @msaps
