### ISSUE TITLE
How to add space between indicator and bottomSeparator

### ISSUE THREAD

**Issue by yeziahehe** [uias/Tabman#293]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

How to add space between indicator and bottomSeparator

### Other useful things

like this 

<img width="490" alt="2018-05-30 11 59 42" src="https://user-images.githubusercontent.com/8090437/40732283-8f7f335a-6465-11e8-940a-4b7082d105cd.png">

**Comment by msaps** [comment]
Now available in Tabman 2 with `.contentInset` (Appreciate it's a little late 😅)
