### ISSUE TITLE
Visual glitch when scrolling between items using different fonts

### ISSUE THREAD

**Issue by rzulkoski** [uias/Tabman#295]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

There is a visual glitch in the scrollingButtonBar when scrolling between items in the case where the normal font is different from the selected font. This is due to the width required to render the title text in the two fonts being different.

To correct this, I adjust the minimumWidthConstraints to be the the greater of the two width constraints or the minimum width supplied by the user if that is greater than both of them.

### Other useful things

Before fix:

![broken](https://user-images.githubusercontent.com/3171325/41051572-1ef6f372-697c-11e8-8f0f-febee46b5308.gif)

After fix:

![fixed](https://user-images.githubusercontent.com/3171325/41051399-a6311daa-697b-11e8-9015-76670e28fb3e.gif)

**Comment by rzulkoski** [comment]
Fixed in PR #296.

**Comment by msaps** [comment]
Merged and available in [1.9.1](https://github.com/uias/Tabman/releases/tag/1.9.1) 🎉
