### ISSUE TITLE
Crash using Tabman

### ISSUE THREAD

**Issue by Ankit8946** [uias/Tabman#297]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Crash using Tabman. Exact steps not available as I only have crash logs from crashlytics.
Please see the Below stack trace.

### Other useful things

Fatal Exception: NSInternalInconsistencyException
Invalid parameter not satisfying: [views count] == 3

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x184fb6d8c __exceptionPreprocess
1  libobjc.A.dylib                0x1841705ec objc_exception_throw
2  CoreFoundation                 0x184fb6bf8 +[NSException raise:format:]
3  Foundation                     0x1859a6fa0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x18f63b63c -[_UIQueuingScrollView _replaceViews:updatingContents:adjustContentInsets:animated:]
5  UIKit                          0x18f63eb08 -[_UIQueuingScrollView _didScrollWithAnimation:force:]
6  UIKit                          0x18f63a818 -[_UIQueuingScrollView _scrollViewAnimationEnded:finished:]
7  UIKit                          0x18ee439bc -[UIAnimator stopAnimation:]
8  UIKit                          0x18ee43410 -[UIAnimator _advanceAnimationsOfType:withTimestamp:]
9  QuartzCore                     0x1890163c0 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
10 IOKit                          0x18521f8a0 IODispatchCalloutFromCFMessage
11 CoreFoundation                 0x184f44b20 __CFMachPortPerform
12 CoreFoundation                 0x184f5fae8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
13 CoreFoundation                 0x184f5f230 __CFRunLoopDoSource1
14 CoreFoundation                 0x184f5cc80 __CFRunLoopRun
15 CoreFoundation                 0x184e7cda8 CFRunLoopRunSpecific
16 GraphicsServices               0x186e5f020 GSEventRunModal
17 UIKit                          0x18ee5d78c UIApplicationMain
18 ixigo                          0x100e8b81c main (DualLabelSelectionControl.swift:16)
19 libdyld.dylib                  0x18490dfc0 start

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
