### ISSUE TITLE
Cann't select items programatically 

### ISSUE THREAD

**Issue by NermeenMohamed** [uias/Tabman#298]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Is it possible to Select a tab by code ?

**Comment by msaps** [comment]
@NermeenMohamed you can use the Pageboy scroll functions to move to pages programmatically. See the [README](https://github.com/uias/Pageboy#%EF%B8%8F-extras)
