### ISSUE TITLE
Concate Two array when we change index

### ISSUE THREAD

**Issue by cjbhojani** [uias/Tabman#299]
Hello There,
I am current working on one app and i used padman in my app.
I have one array which value change when index is changed.
i am able to merge string from array but now when i am change the index than my old array becomes nil.
i  want to merge all the selected string from all the index.
If any one have solution than please help me i am stuck in this problem.

Thank you :)

**Comment by msaps** [comment]
@cjbhojani not really sure how this relates to Tabman?

**Comment by cjbhojani** [comment]
its solved sir.
Thank you for your response.
