### ISSUE TITLE
Add tab bar style TabmanBar

### ISSUE THREAD

**Issue by msaps** [uias/Tabman#3]
Add a `TabmanBar` style which mirrors the appearance of UITabBar. It should offer a similar appearance, but offer enhanced transitions between items (progressive rather than snap). Should also probably be limited to 5 items.

**Comment by otymartin** [comment]
@msaps 
On this - Is there any way to make systemBar added to the bottom of **TabmanViewController** to behave like a UITabBar when a VC is pushed on top of the navigationController Stack?

Eg. I have the following view hierarchy (Below). When I tap a button on the VC, I push another VC onto the Nav stack. However, my NavBar appears above my pushed VC which is unexpected. The bottom TabBar appears above the pushed VC as expected. The transition animation is a bit sketchy, isn't as smooth as the regular "navigationController?.push(VC, animated: true)". 

Is there a formal setup to achieve this natural behavior or it's not supported?

**TabmanViewController** 
****--->NavController(VC1)**
**--->NavController(VC2)**
**--->NavController(VC3)****
