### ISSUE TITLE
1.9.1 failing with `Value of type 'String' has no member 'width'`

### ISSUE THREAD

**Issue by ricardopereira** [uias/Tabman#302]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Updated to the latest version (1.9.1) using CocoaPods but the compilation fails with `Value of type 'String' has no member 'width'` in `Tabman/TabmanBar/Styles/TabmanScrollingButtonBar.swift:162:35`.

### Other useful things

I think the `String+SizeCalculation.swift` is missing in the umbrella header.

**Comment by msaps** [comment]
@ricardopereira it seems to build fine in a fresh project? Maybe try the usual tricks of deleting derived data and installing pods again?

(Demo just for clarification)
[Tabman-PodsTest.zip](https://github.com/uias/Tabman/files/2123714/Tabman-PodsTest.zip)

**Comment by ricardopereira** [comment]
It's working. Thanks!
