### ISSUE TITLE
Use bar by itself

### ISSUE THREAD

**Issue by Vortec4800** [uias/Tabman#305]
While you're working on version 2.0 I'd like to put in a feature request. There have been a few times where I want to use a Tabman bar like a segmented control where it doesn't necessarily change a view controller page, but just makes an adjustment to current view controller settings/content. In the current version it's basically impossible to create and use a Tabman bar without the entire stack and page controller because many parts of the bar are internal to the framework and not accessible. If you're updating these classes anyway, it would be great to have a supported way of creating a Tab bar and showing it in my own view hierarchy.

**Comment by msaps** [comment]
@Vortec4800 yeah this is definitely one of the goals of 2.0, I'm redesigning the whole API so that the bar is exposed better and everything is a bit more flexible 🎉

**Comment by Vortec4800** [comment]
That sounds great. Looking forward to it!

**Comment by msaps** [comment]
@Vortec4800 [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) now available, hopefully this is a bit more useful! 😄
