### ISSUE TITLE
Crash when tabBar items number is zero 

### ISSUE THREAD

**Issue by mojtaba-almoussawi** [uias/Tabman#306]
When the view controller start to load the model will be empty at first ,
i'am initializing the tab bar items and the view controller in the numberOfViewControllers dataSource method , 
So when the `numberOfViewControllers(in pageboyViewController: PageboyViewController) -> Int  `method called and the model is empty the crash occur when assigning the **empty items** to the bar.items 
`bar.items = barItems`

**Comment by msaps** [comment]
Closing due to [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not please open a new issue. 🙂
