### ISSUE TITLE
viewWillAppear / viewDidAppear not being called for first tab...?

### ISSUE THREAD

**Issue by patniemeyer** [uias/Tabman#310]
I'm seeing an issue where my first displayed tab's viewDidAppear() method is not being called.  If I switch to another tab and back then it is called, but not on first appearance.

I will try to isolate and post an example.  Has anyone else seen this behavior?

**Comment by msaps** [comment]
@patniemeyer strange 🤔 - I will have a look as well and see what I can find, but in theory Tabman/Pageboy shouldn't be affecting the standard `UIPageViewController` lifecycle. Haven't seen it mentioned before.

**Comment by WingedDoom** [comment]
I know it sounds dumb..
I had a similar issue (`loadView` was not being called on PageViewController's children), but then I realized I was returning `nil` for the 0th index in `viewController(for pageboyViewController: PageboyViewController, at index: PageboyViewController.PageIndex) -> UIViewController?`.

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
