### ISSUE TITLE
scrollToTop not correct

### ISSUE THREAD

**Issue by yeziahehe** [uias/Tabman#311]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

setting with Troubleshooting Guide, but scrollToTop not correct.

### Other useful things

correct img & not correct img
![simulator screen shot - iphone x - 2018-07-24 at 11 52 35](https://user-images.githubusercontent.com/8090437/43115948-21875794-8f38-11e8-96c4-4ec3ac37d656.png)
![simulator screen shot - iphone x - 2018-07-24 at 11 52 31](https://user-images.githubusercontent.com/8090437/43115950-25ab619e-8f38-11e8-8f1b-7fa3832f3d14.png)

**Comment by msaps** [comment]
@yeziahehe can you please try using AutoInsetter [1.2.6](https://github.com/uias/AutoInsetter/releases/tag/1.2.6) and see if that resolves the issue. Seems similar to #308
