### ISSUE TITLE
Swipe child viewcontroller in index 1-> 0 or pre-last -> last not correct

### ISSUE THREAD

**Issue by thetoanptit** [uias/Tabman#313]
**Tabman ver: 1.1.2**
**Link bug code:** https://github.com/thetoanptit/DemoTabman

**Issue description:**
When I swipe child viewcontroller from pre-last to last, it not work correctly. It swipe to last then swipe back pre-last. I don't know that problem.
I hope you fix it or give to me your solution. Thank you very much!

**Comment by msaps** [comment]
@thetoanptit can you try updating to the latest versions of Tabman and other dependencies and see if the issue still exists? A video/gif would also be useful 🙂

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
