### ISSUE TITLE
Scrolling Button Bar does not re-layout on rotation for .fill Item Distribution

### ISSUE THREAD

**Issue by rzulkoski** [uias/Tabman#314]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When using the .fill item distribution, the scrolling button bar should re-layout the items and reload the indicator when the bar's bounds changes. This currently doesn't happen due to .fill being implemented in `update(forAppearance:defaultAppearance:)`.

This has been fixed by moving its implementation to `updateForCurrentPosition(bounds:)`.

### Other useful things

I also added a stepper to the demo project to allow the user to set the number of pages on the fly.

<img src="https://user-images.githubusercontent.com/3171325/43277305-487c6d1c-90cd-11e8-8fe3-ca417e79dbe2.png" width="30%" height="30%">

**Comment by rzulkoski** [comment]
Fixed in PR #315 .

**Comment by msaps** [comment]
@rzulkosk Commented & merged. Thanks again 💯
