### ISSUE TITLE
ScrollingTabBar Not Loading Properly

### ISSUE THREAD

**Issue by Pilot1000** [uias/Tabman#319]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I'm trying to run an RSS feed with an XML Parser in a TableViewController that has different categories (different websites, and Tabman is used to get to the different categories). The RSS function in the TableViewController is simple:
  
```
func loadData() {
        url = URL(string: AppState.shared.feedURL!)
        print("Loaded data with: \(AppState.shared.feedURL)")
        loadRss(url);
    }
    
    func loadRss(_ data: URL) {
        // News_XMLParser instance/object/variable
        let myParser : News_XMLParser = News_XMLParser().initWithURL(data) as! News_XMLParser
        
        // Put feed in array
        feedImgs = myParser.img as [AnyObject]
        feedAuthors = myParser.fauthor as [AnyObject]
        recentImg = myParser.imgFull as [AnyObject]
        myFeed = myParser.feeds
        tableView!.reloadData()
    }
```

And loadData() is called in viewDidLoad for the TableViewController.

So then I have it set up in the TabmanController:

```
    // Only works on pressing, dragging causes issues
    override func pageboyViewController(_ pageboyViewController: PageboyViewController, willScrollToPageAt index: Int, direction: PageboyViewController.NavigationDirection, animated: Bool) {
        switch index {
        case 1:
            print("1")
            AppState.shared.feedURL = "feedURL/category1"
        case 2:
            print("2")
            AppState.shared.feedURL = "feedURL/category2"
        case 3:
            print("3")
            AppState.shared.feedURL = "feedURL/category3"
        default:
            print("0")
            AppState.shared.feedURL = "feedURL/category0"
        }
    }
```

(The URL's work don't worry about that, I just changed them to something else for the sake of this issue.)

Anyways, when I press on the Tabman Item everything works, although if I try dragging/scrolling it doesn't load properly. Maybe this isn't really an issue with Tabman and more of an issue on when things are called? I'm not sure, any help would be greatly appreciated.

**Comment by msaps** [comment]
@Pilot1000 I would probably not use `willScrollToPageAt` for updating this kind of data, it is not really an intended use case for this delegate function. 

As the Urls are hardcoded per `TableViewController`, would it not make sense to set the url either in an initialiser for the view controller or set as a property when the view controller is initialised (if using storyboards).

**Comment by Pilot1000** [comment]
I tried doing that in a way. I guess the question I've been trying to solve is: How do I get what tabman item I'm in, and where do I need to then load the url. willScrollToPageAt made sense, although when dragging it doesn't pick up on the second item in the index for some reason.

**Comment by msaps** [comment]
@Pilot1000 you shouldn't really need to rely on the positional data of the page view controller to know what Url you need to load though - as the urls are static within the child view controllers when initialised? 

Something like this would probably work much better:

```swift
class TabViewController: TabmanViewController {

    var viewControllers: [UIViewController] = {
        var collection = [UIViewController]()
        for index in 0 ..< 4 {
            let url = URL(string: "feedURL/category\(index)")!
            collection.append(TableViewController(url: url))
        }
        return collection
    }()
}

class TableViewController: UITableViewController {

    let url: URL

    init(url: URL) {
        self.url = url
    }
}
```

The use of the detached `AppState.shared.` singleton object is not necessary and is prone to encountering state issues with UI.

Hope this helps!
