### ISSUE TITLE
Insets are incorrect when using tab buttons to switch

### ISSUE THREAD

**Issue by Vortec4800** [uias/Tabman#320]
### Issue Description

This is a weird one. I think it may be in the AutoInsetter, but I'm not well-versed enough in how it all operates to know which part is causing this bug.

When you switch between tabs using a horizontal scroll gesture, everything works properly. When you switch tabs by tapping on one of the other tab buttons, the page view controller's inset is set improperly, and the top of the content is covered. You can also see the top of the table's scroll indicator is covered as well. Interestingly, when the top is covered, if you scroll briefly it fixes itself.

I've included a basic sample project that illustrates this issue. A quick stroll through the sample project should show the issue immediately.

### Other useful things

Sample project
[InsetTest.zip](https://github.com/uias/Tabman/files/2306871/InsetTest.zip)

Change by scrolling
![simulator screen shot - iphone 8 - 2018-08-21 at 10 04 44](https://user-images.githubusercontent.com/396122/44410290-b2fd7f80-a529-11e8-8d34-ddbb16c22619.png)

Change by tapping
![simulator screen shot - iphone 8 - 2018-08-21 at 10 04 51](https://user-images.githubusercontent.com/396122/44410303-b8f36080-a529-11e8-928a-a7e026037efd.png)

**Comment by msaps** [comment]
@Vortec4800 thanks for all the detail! Will get on this ASAP.

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
