### ISSUE TITLE
TabmanBar how set defaults appearance, it is possible?

### ISSUE THREAD

**Issue by StasanTelnov** [uias/Tabman#322]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I can config bar appearance in specific view controllers. But default Appearance is nil, and I should init this everytime.
Is there any possibility set global appearance. How for default Apple UI elements.
For example, I can setup global tabbar tint color in AppDelegate:
`UITabBar.appearance().tintColor = .red`
I can do and how I can do the same thing for  TabmanBar?

**Comment by msaps** [comment]
@StasanTelnov unfortunately Tabman 1.x doesn't support `UIAppearance` 😢 

But Tabman 2 will be much improved and provide better support for this! So unfortunately for now, the answer is sadly no. Also apologies for the slow reply.

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
