### ISSUE TITLE
Tabman/Pageboy Carthage build failing with Xcode 10 GM Seed

### ISSUE THREAD

**Issue by rzulkoski** [uias/Tabman#323]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Unable to build Tabman with Carthage using the Xcode 10 GM Seed.

I've attached the build log below:
[carthage-xcodebuild.WrfZ7h.log](https://github.com/uias/Tabman/files/2380460/carthage-xcodebuild.WrfZ7h.log)

**Comment by bennichols** [comment]
I was able to resolve this by updating to the latest version of Swiftlint.

**Comment by rzulkoski** [comment]
I can confirm that was the issue and updating has solved the issue for me. Thanks!
