### ISSUE TITLE
can't init bar items

### ISSUE THREAD

**Issue by ovyan** [uias/Tabman#328]
### New Issue Checklist

- [+ ] Updated Tabman to the latest version
- [ + ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ + ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Crash:
```
let barItems = [Item(title: "Лекарства"), Item(title: "Симптомы")]
bar.items = barItems
```
OK:
```
var barItems = [Item].init(repeating: BaseViewController.Item(title: "2"), count: 2)
        barItems[0] = Item(title: "Лекарства")
        barItems[1] = Item(title: "Симптомы")
        
        bar.items = barItems
```

Why????

### Other useful things

Xcode 10, iOS 12

Stack:

![image](https://user-images.githubusercontent.com/23217571/46248224-6b6aed00-c41f-11e8-8dbf-01d7cc081061.png)

![image](https://user-images.githubusercontent.com/23217571/46248226-76258200-c41f-11e8-8c57-dc963503c1b5.png)

![image](https://user-images.githubusercontent.com/23217571/46248223-6443df00-c41f-11e8-846e-49fa12fe442f.png)

Sincerely, 
Mike Ovyan

**Comment by msaps** [comment]
@ovyan wow that is strange, I can't seem to reproduce at all. Have a demo project attached which seems to have no issue with a very similar configuration to yours.

Would you be able to take a look and maybe provide something that makes this reproducible?

[Tabman-Test.zip](https://github.com/uias/Tabman/files/2441563/Tabman-Test.zip)

Thanks!!

**Comment by msaps** [comment]
@ovyan as mentioned in [#333](https://github.com/uias/Tabman/issues/333#issuecomment-427081074) is your project updated to use Swift 4.2? This crash only seems to happen under Swift 4 an Tabman 1.10.x (there are no new features in 1.10.x, simply a support release for Swift 4.2).

Tabman 2 is almost ready so Tabman 1.x is pretty much in maintenance mode only right now 😄
