### ISSUE TITLE
Tab Disappear when I set `bar.style`or `bar.behavior`

### ISSUE THREAD

**Issue by CHOIMINSEOK** [uias/Tabman#330]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
Whenever I set `bar.style` any value except `.scrollingButtonBar`, tab view disappear.
```
self.bar.style = .bar
```
It's same on `bar.behavior`
```
self.bar.behaviors = [.autoHide(.always)]
```

I can't figure it out why this happen. Anybody help? 

### Other useful things

I'm using `ReSwift`. Initiate `ViewControllers` & `reloadPages` on `newState`.
```
func newState(state: [State]) {
        guard state.count > 0 else {
            return
        }
        
       // Bind Data on Tab
      // Initialize ViewControllers

        self.reloadPages()
        if indexOfToday == 0 {
            self.reloadPages()
        } else {
            scrollToPage(Page.at(index: indexOfToday), animated: true)
        }
    }
```
The layout is broken at first, so I call `reloadPages()` twice. It is strange also.

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
