### ISSUE TITLE
Is it possible to layer the indicator and separator lines instead of having the indicator on top?

### ISSUE THREAD

**Issue by bennichols** [uias/Tabman#337]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Tabman is working great for me, but the designer is asking for a layered effect with the lines. I've include an image below. Is this possible with Tabman? If not, how hard would it be for me to customize it for this look? Thanks!

### Other useful things

<img width="323" alt="screen shot 2018-10-13 at 4 49 18 pm" src="https://user-images.githubusercontent.com/610384/46911140-fa8c0080-cf07-11e8-96b6-74d3a69aec21.png">

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂

**Comment by nthtrung09it** [comment]
@bennichols Did you solve this problem?
