### ISSUE TITLE
Feature Request - Show / Hide Bar explicitly

### ISSUE THREAD

**Issue by ChristianSteffens** [uias/Tabman#338]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Hi, we're looking for a way to show / hide the Tabman bar explicitly, i.e. programmatically.

Our usecase is to show the bar after any user interaction (touches) and after a short time interval we'd like to hide the bar. Furthermore this show / hide process should be animated, ideally using a constraint that will increase / decrease the bar views hight.

We're using tabman to show the titles of several pages we're displaying using pageboy. But we don't want the bar / titles to be visible all the time, as this is not important or wanted by the user (the screen should be as clean as possible while reading).

### Other useful things

We already have the logic to detect touches and a timer to trigger the tabman's potential show / hide methods. So what we effectively need is just a way to either call a show / hide method on the tabman controller or alternatively a constraint we can manipulate to our needs.

I just forked your project, but saw that there's already a tabman 2 in the making, so I wanted to hear your opinion first, maybe you're already working on such a feature? If not you're going to?

**Comment by msaps** [comment]
@LordNali Sounds like a great idea! I don't think that this should probably live in the main 'bar' logic as this kind of thing is so subjective depending on animations / design / how the app wants it to work...

But yes Tabman 2 is almost ready, and I actually think this will be really easy to achieve with the new API's.

I think we will be able to create a 'wrapper bar' which will embed any bar and provide the layout & hide/show animations. I've already done this in Tabman 2 with the [TMSystemBar](https://github.com/uias/Tabman/blob/tabman2/Sources/Tabman/Bar/SystemBar/TMSystemBar.swift) - which basically mimics the appearance of a `UINavigationBar` / `UITabBar` (Extending beyond safe areas etc.) and allows you to embed a 'content' bar. 

I was thinking of maybe creating a `Tabman+Extras` repo which could contain features like this which don't really need to be in the core repo?

I have no exact timescale for when I'll be releasing 2.0, other than 'soon' - but I think it will be worth the wait.

You could also potentially do this in 1.x by embedding the bar in a custom container view which handles all the show/hide logic, but you would lose things such as auto insetting. 

Let me know what you think 😄

**Comment by LordNali** [comment]
That sounds great - so I'll wait (patiently) for Tabman 2.0.

**Comment by ChristianSteffens** [comment]
Are there any news in regard to a potential show / hide (animated) of the Tabman's bar? I saw the Tabman2 branch is updated frequently.

**Comment by msaps** [comment]
@ChristianSteffens I just released [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - this unfortunately didn't quite make it in.

However everything is a lot more extendable and exposed now, so this should be quite a bit easier. I also hope to get this in natively in Tabman 2.1 or so.

**Comment by ChristianSteffens** [comment]
So should I wait for 2.1 or should I implement it using the current version / 2.0.
This feature is not urgent for us, especially if it's on your release plan anyhow,
but if not, I'm certainly willing to help out during the holidays ;-)

**Comment by msaps** [comment]
@ChristianSteffens if you are in no rush then maybe wait for the update (probably not 2.1 as I've just released that with some more urgent improvements 😄). I was thinking of the following features:

- Hide bar after a given time duration.
- Hide bar on upward scroll of a child scroll view.
- Ability to show bar on any interaction with paging (swipe left right).
- Ability to show bar on a tap gesture.
- Ability to show bar on downward scroll of child scroll view.

Some are trivial to do (hide after duration / show on tap gesture), but the scrolling ones might be a bit more involved.. 

So my recommendation (also @blurtime) if you need this quickly, it will probably be quite trivial to implement in your own scenarios, but if you want a bit more of a flexible implementation and have time then wait for the TM version 🚀

**Comment by blurtime** [comment]
@msaps I've been recently tackling a problem but couldn't solve it, neither with Tabman nor with a PageboyViewController. I think it is somewhat related to this issue, therefore I'll provide a description of the problems and ideas I had: 

I would like my first ViewController (tab and page 1) to present general information (e.g. a user's profile) and on the following pages (all of them belonging to a single tab, namely tab 2), if there are any, media (e.g. images, videos, etc. covering the entire screen) associated with this user. 
Accordingly, the button-system bar (with accessory views and at the top in my case) should only be permanently visible in the first page/tab. In the following pages I would like it to be hidden and shown only when the user swipes dow, hidden again after a swipe up gesture or simply after a couple of seconds - preferably, without affecting the layout below, hence, not moving the media up and down. 
A cool animation from tab/page 1 (`index = 0`) to tab 2 with pages 2, 3, 4, etc. would be if the bar disappeared according to the x position of the second page (the farther the user scrolls to tab 2 from 1, the more the bar is hidden). 

I first tried solving this problem by using Tabman and then putting a PageboyViewController in the second tab but encountered some issues with the paging (i.a. one cause was that both were horizontal, unfortunately pretty important they both page horizontally). As this didn't work, I tried using Pageboy and a navigation bar instead but encountered even more issues with the layout always moving the media in all of my view controllers up and down _while_ or even - in some of my attempts - _after_ scrolling as well as the navigation bar's hiding animation bugging in many cases. 

If you, first of all, like the idea and and believe it would be possible without costing you too much time, I'd love to hear your opinion. I really tried to make it work and would have liked to contribute something but couldn't figure it out, guess I've still got a lot to learn. 😔
If anything remains unclear, please let me know. 😃

**Comment by g7tianyi** [comment]
😃Same requirement here, looking forward to the new release.

**Comment by ChristianSteffens** [comment]
So it's planned for the upcoming release?

**Comment by msaps** [comment]
@ChristianSteffens yeah planned for 2.3 - there is a branch open now (`feature/autohide`). It's just quite a complex thing to achieve 😄

**Comment by blurtime** [comment]
Hi @msaps, has there been any progress on this lately? If not, do you have an idea as to how I could work around it for the time being? I provided an (I know rather lengthy) description of what I'd like to achieve and as you said you believed it would probably be quite trivial to achieve in our specific cases in the comment above, I was wondering if you could maybe tell me how you would proceed, i.e. small instructions for my case? I'm kind of lost, I feel - especially when I haven't coded in a while and already tried out a couple of things which, unfortunately, didn't work the way I wanted them to... Really nothing long, a small step-by-step instruction would be greatly appreciated! 😃
I seriously don't want to pressure you in any way. Feel free to answer whenever you have time

**Comment by msaps** [comment]
@blurtime hoping to get some time to work on it this weekend and get a new release out next week with this feature - watch this space 😄

**Comment by msaps** [comment]
Now available in [2.4.0](https://github.com/uias/Tabman/releases/tag/2.4.0) with `TMHidingBar`.  🎉 

Checkout the [TMHidingBar docs](https://uias.github.io/Tabman/master/Classes/TMHidingBar.html) for usage. 🍻 

cc @blurtime @ChristianSteffens

**Comment by Dfmarulanda** [comment]
Hiding the bar is not moving the viewControllers up. Its something bad in my implementation?
