### ISSUE TITLE
How could I center the indicator with the tab item in titleView

### ISSUE THREAD

**Issue by wakaryry** [uias/Tabman#339]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
I embed my tab into navigationItem's titleView. And set the style `.buttonBar`.
The problem is that the indicator is not centered with the title.
As shown:

![image](https://user-images.githubusercontent.com/7576559/47333579-01f49c00-d6b6-11e8-82bb-08951de25ed1.png)

How could I make it center.

**Comment by azshahuray** [comment]
Hi. I had the same problem, but I solved it by adding the following sources.

```
appearance.layout.interItemSpacing = 0.0
appearance.layout.edgeInset = 0.0
```

**Comment by azsha** [comment]
Hi. I had the same problem, but I solved it by adding the following sources.

```
appearance.layout.interItemSpacing = 0.0
appearance.layout.edgeInset = 0.0
```

**Comment by wakaryry** [comment]
@azsha Thanks for your reply. Finally I know how to change its default.
