### ISSUE TITLE
Xcode 10 Build Error

### ISSUE THREAD

**Issue by masuhara** [uias/Tabman#342]
・Xcode10

```
1.	While running pass #1 SILModuleTransform "PerformanceSILLinker".
2.	While deserializing SIL vtable for 'Item' in module 'Tabman'
error: Abort trap: 6
```

**Comment by suhaa18** [comment]
Please build using swift 4.
Then you can archive without above issue.

**Comment by msaps** [comment]
@masuhara are you building with Swift 4.2? Tabman 1.10 and above require Swift 4.2

**Comment by masuhara** [comment]
@suhaa18 @msaps 

Thanks for your reply.
That project using Swift3.x, so 4.x is OK for me(Resolved). Thanks.

But, what is this error meaning? I want to study why this error occurs.
If you know about this, can you explain why this error occurs (what is this error)?

**Comment by wangjianqi** [comment]
swift 4.0 build Error for Xcode 10.1

**Comment by wmanriques** [comment]
I have the same for the version 1.10.2 and Swift 4.2
1.	While running pass #1 SILModuleTransform "PerformanceSILLinker".
2.	While deserializing SIL vtable for 'Item' in module 'Tabman'
error: Abort trap: 6

But when I change to Swift 4 and the method didMoveToSuperview, i can archive the workspace.

**Comment by WingedDoom** [comment]
Same issue with 4.2 :(
@wmanriques @suhaa18 thank you guys for the solutions, you saved me a lot of time!

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
