### ISSUE TITLE
Cannot assign to property: 'requiredInsets' setter is inaccessible

### ISSUE THREAD

**Issue by anilios** [uias/Tabman#343]
### New Issue Checklist

- [x] Updated Tabman to the latest version
Yes
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
Yes
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)
Yes

### Issue Description
![screenshot 2018-10-27 at 6 12 55 pm](https://user-images.githubusercontent.com/694814/47604231-10bfb380-da14-11e8-8e1b-9c1f4e348154.png)

**Comment by msaps** [comment]
@anilios the `requiredInsets` value is designed to provide the values required to layout content underneath the bar correctly - what are you trying to change it for?

**Comment by msaps** [comment]
Closing due to the release of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - which should have resolved this issue. 🎉 

If not, please open a new issue. 🙂
