### ISSUE TITLE
Is there a way to disable the fading tab text color when transitioning?

### ISSUE THREAD

**Issue by rkittinger** [uias/Tabman#344]
When the text color of the tab label is different from the selected text color the color changes with a fade effect. This can especially be seen when swiping slowly between tab views. Is there a way to disable the text color fading?

**Comment by msaps** [comment]
This is available as a feature in [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) via `.transitionStyle` 🍺

**Comment by sugitatestblue** [comment]
`barView.layout.transitionStyle = .none`?
 not work!
