### ISSUE TITLE
How can I customize the bar's Y position?

### ISSUE THREAD

**Issue by beatman423** [uias/Tabman#345]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

How can I customize the bar's Y position? 
Or how to set the bar's preferred Y position?
Thanks for the helps in advance.

**Comment by rkittinger** [comment]
I am also needing to do this to start the bar's Y-pos under another subview....

**Comment by msaps** [comment]
@beatman423 @rkittinger you can achieve this by embedding the bar in a custom container bar view - [see here](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md#embedding-tabmanbar-in-an-external-view)

**Comment by rkittinger** [comment]
@msaps thanks a lot that worked :)
