### ISSUE TITLE
How to assign custom functionality to tabs

### ISSUE THREAD

**Issue by rkittinger** [uias/Tabman#347]
### New Issue Checklist

- [ ] Updated Tabman to the latest version (we haven't updated to Swift 4.2 yet....)
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

How can I assign, for example, a double click gesture or other functionality to the tabs to communicate with the view controller to scroll to top?

**Comment by msaps** [comment]
@rkittinger check out [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) - should be a lot more customisable and extensible 😄 🎉
