### ISSUE TITLE
Change Pageboy version to 3.0

### ISSUE THREAD

**Issue by blurtime** [uias/Tabman#350]
Love both pods! Would really appreciate if you could change the number to the newest version of Pageboy since I'd love to start working with the new Pageboy features. Keep up the great work!

**Comment by msaps** [comment]
@blurtime currently working on Tabman 2 which is what Pageboy 3 was built for! 😄 Beta versions are currently available ([Beta 3](https://github.com/uias/Tabman/releases/tag/2.0.0.beta.3)) - and I'm hoping to get the stable release out ASAP.

**Comment by blurtime** [comment]
Sounds awesome! No need to hurry though... just wanted to remember you in case you forgot this pod :D Thank you for constantly improving the pods!

**Comment by msaps** [comment]
@blurtime [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) is now available 🎉

**Comment by huyduc** [comment]
I couldn't install `2.0.0` due to conflicting dependencies specs

```
Could not pick a version for github "uias/AutoInsetter", due to mutually incompatible requirements:
	== 1.3.0
	~> 1.4.0 (github "uias/Tabman")
```
