### ISSUE TITLE
SeparatorView AutoLayout Issue 

### ISSUE THREAD

**Issue by fmousalou** [uias/Tabman#352]
Hi dude. I am @farshadmb. 
I think you missed some one. 

Could you please answer my question about SeperatorView Constraints 
```
 // MARK: Layout
    
    func addAsSubview(to parent: UIView) {
        
        parent.addSubview(self)
        pinToSuperviewEdge(.bottom)
        leftPinConstraint = pinToSuperviewEdge(.leading)
        rightPinConstraint = pinToSuperviewEdge(.right)
    }
```

you totaly missed width for iOS 10.2

should you refactor to ``` rightPinConstraint = pinToSuperviewEdge(.trailing)``` or not?

Thanks

**Comment by msaps** [comment]
@fmousalou apologies this took so long, this issue should be resolved as of [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) so please migrate to the latest release 👍 

If this is still a problem in 2.0, please create a new issue.
