### ISSUE TITLE
custom

### ISSUE THREAD

**Issue by Amelia1992** [uias/Tabman#359]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@Amelia1992 not really sure what you mean by this? Closing...
