### ISSUE TITLE
RTL Indicator Animation

### ISSUE THREAD

**Issue by Sushhi** [uias/Tabman#366]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

In RTL mode, the indicator seems wrong after few switches. Is something wrong with my implementation ?

> Pageboy (3.0.1)
> Tabman (2.1.2)

Thanks in advance!

### Other useful things

![tabman](https://user-images.githubusercontent.com/5255069/50822566-4ea15800-1332-11e9-8813-ac5ff98d891c.gif)
![image](https://user-images.githubusercontent.com/5255069/50822413-f9654680-1331-11e9-8f6c-43a50d8c9ca1.png)
![image](https://user-images.githubusercontent.com/5255069/50822438-03874500-1332-11e9-937e-71835a4b5861.png)

**Comment by msaps** [comment]
@Sushhi looks like a bug! Will get on it 👍

**Comment by msaps** [comment]
Fixed in [2.1.3](https://github.com/uias/Tabman/releases/tag/2.1.3) 🎉

**Comment by Sushhi** [comment]
Thanks guys! :D
