### ISSUE TITLE
Unable to simultaneously satisfy constraints in navigationItem.titleView

### ISSUE THREAD

**Issue by wakaryry** [uias/Tabman#370]
### New Issue Checklist

- [✓ ] Updated Tabman to the latest version
- [✓] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [✓] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
My usage:

```swift
import UIKit
import Tabman
import Pageboy
import SnapKit

class TabsTitleView: UIView {
    override var intrinsicContentSize: CGSize {
        return UIView.layoutFittingExpandedSize
    }
}

class ViewController: TabmanViewController {
    
    let titleView = TabsTitleView()
    let tabsView = UIView()
    
    private var viewControllers = [UIViewController(), UIViewController()]
    
    lazy private var leftItem: UIButton = {
        let bt = UIButton(type: .custom)
        //let url = URL(string: "")!
        bt.setTitle("Left", for: .normal)
        return bt
    }()
    
    lazy private var rightItem: UIButton = {
        let bt = UIButton(type: .custom)
        bt.setTitle("Right", for: .normal)
        return bt
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        buildPages()
    }
    
    private func buildPages() {
        // default is true
        // self.automaticallyAdjustsChildInsets = true
        self.dataSource = self
        let bar = TMBar.ButtonBar()
        //bar.transitionStyle = .snap
        bar.buttons.customize { (bt) in
            bt.selectedTintColor = .red
            bt.tintColor = .black
            bt.font = UIFont.systemFont(ofSize: 18)
            bt.selectedFont = UIFont.systemFont(ofSize: 18)
        }
        bar.indicator.tintColor = .yellow
        bar.indicator.cornerStyle = .eliptical
        bar.indicator.overscrollBehavior = .compress
        //bar.indicator.weight = .custom(value: 4)
        
        //bar.backgroundColor = .red
        bar.backgroundView.style = .clear
        
        bar.layout.contentMode = .fit
        // bar.layout.contentInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
        self.addBar(bar, dataSource: self, at: .custom(view: self.tabsView, layout: nil))
        
        self.configureBar()
    }
    
    private func configureBar() {
        
        self.titleView.addSubview(self.tabsView)
        
        self.titleView.addSubview(self.leftItem)
        self.titleView.addSubview(self.rightItem)
        
        self.navigationItem.titleView = self.titleView
        
        self.tabsView.snp.makeConstraints { (make) in
            make.left.equalToSuperview().offset(60)
            make.right.equalToSuperview().offset(-60)
            make.top.bottom.equalToSuperview()
        }
        
        self.leftItem.snp.makeConstraints { (make) in
            make.left.equalToSuperview().offset(8)
            make.width.height.equalTo(36)
            make.centerY.equalToSuperview()
        }
        
        self.rightItem.snp.makeConstraints { (make) in
            make.right.equalToSuperview().offset(-8)
            make.width.equalTo(30)
            make.top.bottom.equalToSuperview()
        }
    }

}

extension ViewController: PageboyViewControllerDataSource, TMBarDataSource {
    func barItem(for bar: TMBar, at index: Int) -> TMBarItemable {
        let title = "Page \(index)"
        return TMBarItem(title: title)
    }
    
    
    func numberOfViewControllers(in pageboyViewController: PageboyViewController) -> Int {
        return viewControllers.count
    }
    
    func viewController(for pageboyViewController: PageboyViewController,
                        at index: PageboyViewController.PageIndex) -> UIViewController? {
        return viewControllers[index]
    }
    
    func defaultPage(for pageboyViewController: PageboyViewController) -> PageboyViewController.Page? {
        return nil
    }
}

```

And the `ViewController` is embedded into a `UINavigationController`.

The issue is that:
TabManTest[17745:607298] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x280478b90 Tabman.TMLineBarIndicator:0x101b0a3c0.height == 4   (active)>",
    "<NSLayoutConstraint:0x280479cc0 V:|-(0)-[Tabman.TMLineBarIndicator:0x101b0a3c0]   (active, names: '|':_TtGC6Tabman23TMBarIndicatorContainerCS_18TMLineBarIndicator_:0x101b1c5f0 )>",
    "<NSLayoutConstraint:0x280479d10 Tabman.TMLineBarIndicator:0x101b0a3c0.bottom == _TtGC6Tabman23TMBarIndicatorContainerCS_18TMLineBarIndicator_:0x101b1c5f0.bottom   (active)>",
    "<NSLayoutConstraint:0x280479590 V:|-(0)-[UIStackView:0x101b1bff0]   (active, names: '|':Tabman.TMBarViewLayoutGrid:0x101b1be00 )>",
    "<NSLayoutConstraint:0x280479630 UIStackView:0x101b1bff0.bottom == Tabman.TMBarViewLayoutGrid:0x101b1be00.bottom   (active)>",
    "<NSLayoutConstraint:0x280479810 Tabman.TMBarViewLayoutGrid:0x101b1be00.height == UIStackView:0x101c147a0.height   (active)>",
    "<NSLayoutConstraint:0x280479130 V:|-(0)-[UIStackView:0x101c147a0]   (active, names: '|':_TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x101c144f0 )>",
    "<NSLayoutConstraint:0x280479180 V:[UIStackView:0x101c147a0]-(0)-|   (active, names: '|':_TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x101c144f0 )>",
    "<NSLayoutConstraint:0x280479e50 V:|-(0)-[_TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x101c144f0]   (active, names: '|':UIView:0x101b104b0 )>",
    "<NSLayoutConstraint:0x280479ef0 _TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x101c144f0.bottom == UIView:0x101b104b0.bottom   (active)>",
    "<NSLayoutConstraint:0x280479fe0 '_UITemporaryLayoutHeight' UIView:0x101b104b0.height == 0   (active)>",
    "<NSLayoutConstraint:0x28047a1c0 'UISV-canvas-connection' UIStackView:0x101b1bff0.top == UIStackView:0x101b1c1f0.top   (active)>",
    "<NSLayoutConstraint:0x28047a210 'UISV-canvas-connection' V:[_TtGC6Tabman23TMBarIndicatorContainerCS_18TMLineBarIndicator_:0x101b1c5f0]-(0)-|   (active, names: '|':UIStackView:0x101b1bff0 )>",
    "<NSLayoutConstraint:0x28047a260 'UISV-spacing' V:[UIStackView:0x101b1c1f0]-(0)-[_TtGC6Tabman23TMBarIndicatorContainerCS_18TMLineBarIndicator_:0x101b1c5f0]   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280478b90 Tabman.TMLineBarIndicator:0x101b0a3c0.height == 4   (active)>

And also the page title in titleView is hidden by some.

Just as another issue says:
https://github.com/uias/Tabman/issues/353

**Comment by wakaryry** [comment]
@msaps Thanks. Nice framework. Hope `navigationItem.titleView` will be supported soon.

**Comment by msaps** [comment]
Moving to #321
