### ISSUE TITLE
When adding bar to a custom view, tabbar covers all view, no room left for view controllers.

### ISSUE THREAD

**Issue by yigitserin** [uias/Tabman#372]
I have some views in my view controller and I wanted to add tabs below these views. So I added a empty UIView to add tabs to it. However, tabs are taking whole screen now, and there is no room for view controllers. How to solve this?

![This is how it looks](https://i.imgur.com/GZExxSg.png)

This is my current code:

```swift
        self.dataSource = self
        //self.isScrollEnabled = false
        // Create bar
        let bar = TMBar.ButtonBar()
       
        bar.layout.interButtonSpacing = 24.0
        bar.indicator.weight = .light
        bar.layout.contentMode = .fit
        
        bar.buttons.customize { (button) in
            button.font = UIFont.systemFont(ofSize: 14, weight: .semibold)
        }
        
        addBar(bar, dataSource: self, at: .custom(view: tabsArea, layout: nil))
```

**Comment by yigitserin** [comment]
Yes it is constrained to the bottom of the superview. What is the correct way to setup the layout closure?

**Comment by msaps** [comment]
@yigitserin you don't need it constrained to the bottom of the superview, it will intrinsically size with the bar 🙂
