### ISSUE TITLE
transitionStyle' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by TamerEzzat** [uias/Tabman#375]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@TamerEzzat this is intentional, the property is instead publicly available within `TMBarLayout`.

The following types support `transitionStyle` properties:
- `TMBarLayout`
- `TMBarButton`
- `TMBarIndicator`

Hope this helps!
