### ISSUE TITLE
Keyboard overlapping textfields in UITableViewController

### ISSUE THREAD

**Issue by romangish** [uias/Tabman#377]
UITableViewController automaticly manages textfield editing: scrolling to editable content, changing insets to display textfield and keyboard on screen simultaneously without keyboard overlapping. It's very cool feature because i don't need to write a lot of code to calculate new insets, scroll to content, check if deviceOrientation changed or keyboard hidden and so on.

But that feature fails when we are using Tabman. Example https://youtu.be/PU2aE7TfHWs

**Comment by msaps** [comment]
@romangish this is probably due to the way Tabman handles insetting (using [AutoInsetter](https://github.com/uias/AutoInsetter)) which disables all UIKit automatic insetting. Will try and get it fixed!

**Comment by msaps** [comment]
@romangish closing and moved to new ticket in AutoInsetter 👍
