### ISSUE TITLE
willScrollToPage causing inset problems - Bug

### ISSUE THREAD

**Issue by hemo87** [uias/Tabman#382]
### Issue Description

Tested with PageBoy on its own and this only happens with Tabman, when using willScrollToPage it causes a strange inset type problem. Ive created an example project that shows the issue. 

This only happens when using willScrollToPage and not the other delegates such as didScrollToPage

The demo project loads 5 tabs all from the same ViewController a plain tableView with a view added above to simply highlight the problem easier.

Tab One displays correctly
![simulator screen shot - iphone 6 - 2019-02-03 at 20 39 42](https://user-images.githubusercontent.com/9624935/52182341-0e7bab00-27f4-11e9-8d50-26134ee26fda.png)

All other tabs display like so
![simulator screen shot - iphone 6 - 2019-02-03 at 20 39 46](https://user-images.githubusercontent.com/9624935/52182347-1d625d80-27f4-11e9-9a38-ceddb6d320e2.png)

As Ive already said commenting out the willScrollToPage fun returns normal functionality.

It'd be great if someone could share an interim fix until its updated.

### Other useful things

Demo Project - 
https://github.com/hemo87/ExampleTabmanBug/archive/master.zip

**Comment by msaps** [comment]
@hemo87 had a quick look at your example, it looks like you are missing a `super` call? `willScrollToPage` is a `PageboyViewControllerDelegate` function that you are overriding - adding the `super` call fixes it 🙂

**Comment by hemo87** [comment]
Thanks for the clarification.
