### ISSUE TITLE
White spaces above child controllers on iOS 10.3.1

### ISSUE THREAD

**Issue by yybot1** [uias/Tabman#383]
This bug is only seen on iOS 10 (you can use Xcode iOS 10.3.1 Simulator). The first time I land on the parent vc, there is white spaces between the child and parent vc. If I change pages, the white spaces disappear. 

Inspired by #264, I fix this bug by adding automaticallyAdjustsScrollViewInsets = false before setting dataSource. 

But this bug should be fixed in future version of Tabman.

Tabman 2.1.3
AutoInsetter 1.4.1

**Comment by msaps** [comment]
@yybot1 will check it out 👍

**Comment by msaps** [comment]
Fixed in [2.1.4](https://github.com/uias/Tabman/releases/tag/2.1.4) 🎉
