### ISSUE TITLE
'transitionStyle' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by o-zaporozhchenko** [uias/Tabman#384]
// Create bar
        let bar = TMBar.ButtonBar()
        bar.transitionStyle = .snap // Customize

gives error: 
'transitionStyle' is inaccessible due to 'internal' protection level

**Comment by msaps** [comment]
See #375 - `transitionStyle` is set in the child areas of the bar:

```swift
TMBarView.layout.transitionStyle
TMBarView.buttons.transitionStyle
TMBarView.indicator.transitionStyle
```

**Comment by o-zaporozhchenko** [comment]
Please, look what u write in Readme, thats just a quote from it: 
https://github.com/uias/Tabman#the-basics

but this doesn't work if somebody gonna try it.

**Comment by msaps** [comment]
@o-zaporozhchenko ah my bad! Updated it, thanks for noticing 😄

**Comment by o-zaporozhchenko** [comment]
@msaps look also there: https://github.com/uias/Tabman#tmbarview 
didnt tried it, but think could be the same.
