### ISSUE TITLE
Child view controller custom inset

### ISSUE THREAD

**Issue by jonaszmclaren** [uias/Tabman#385]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I added bar to a custom view, because I needed another view above bar. The documentation says that auto insetting does not work for bars that are added to custom views. But how can I achieve insetting of child view controller in this case?

**Comment by msaps** [comment]
@jonaszmclaren you have to calculate the inset values you require and then adjust `contentInset` or the `additionalSafeAreaInsets` (if you can) of your views to be below your custom bar container. 

The reason Tabman doesn't support this is it would be nigh on impossible to get it right for custom layouts 😄
