### ISSUE TITLE
Header above TM ButtonBar

### ISSUE THREAD

**Issue by v1ruben** [uias/Tabman#386]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
I am posting here after spending the day fiddling around with this! I'd like to place a dynamic header sizing with the scrolling of a child view controller. Eventually, I came across [this project](https://github.com/yutu/TwitterProfileExample) which uses storyboards and (I believe) an earlier version of Tabman/Pageboy in conjunction with [MXParallaxHeader](https://github.com/maxep/MXParallaxHeader).

I was hoping for some help on how to port it to the latest version programmatically. (I started out this way after being taught to avoid storyboards).

My code so far:
```Swift
class TabbedController: TabmanViewController {
    
    private var controllers = [UIViewController(), UIViewController()]
    private var bar = TMBar.ButtonBar()
    
    init() {
        super.init(nibName: nil, bundle: nil)
        self.dataSource = self
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        bar.layout.contentMode = .fit
        bar.layout.transitionStyle = .progressive
        
        addBar(bar, dataSource: self, at: .top)
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

extension SourceController: PageboyViewControllerDataSource, TMBarDataSource {
    
    func numberOfViewControllers(in pageboyViewController: PageboyViewController) -> Int {
        return controllers.count
    }
    
    func viewController(for pageboyViewController: PageboyViewController, at index: PageboyViewController.PageIndex) -> UIViewController? {
        return controllers[index]
    }
    
    func defaultPage(for pageboyViewController: PageboyViewController) -> PageboyViewController.Page? {
        return nil
    }
    
    func barItem(for bar: TMBar, at index: Int) -> TMBarItemable {
        return TMBarItem(title: "Page \(index)")
    }
}
```

P.S. incredible library - the flexibility is awesome 😄

**Comment by msaps** [comment]
@v1ruben ah nice, I did want to try and build a library that uses Tabman and makes this easier, but haven't quite got round to it just yet! 

Your code looks good, other than the location of the bar. You will need to add it to a custom container view (which is located underneath your parallax header) - should look something like this:

```swift
addBar(bar, dataSource: self, at: .custom(view: myCustomContainer)
```

You would then have to handle any of the insetting of the child view controller contents manually, as Tabman can't automatically inset contents with custom bar views. 👍

**Comment by v1ruben** [comment]
That worked well and I managed to get away with the default tab bar. Again, thank you so much for such a great library!
