### ISSUE TITLE
Add ability to show badge on `TMBarButton`

### ISSUE THREAD

**Issue by msaps** [uias/Tabman#387]
Add the ability to show a badge with value on `TMBarButton`. Interaction should maybe be possible via `TMBarItem`? 

#294 #238 #381

**Comment by msaps** [comment]
Now available in [2.2.0](https://github.com/uias/Tabman/releases/tag/2.2.0) 🎉 

![badge](https://user-images.githubusercontent.com/3515448/54035470-bef51a00-41b9-11e9-8df0-7b85e6bb7781.gif)

**Comment by RiyanFransen** [comment]
> Now available in [2.2.0](https://github.com/uias/Tabman/releases/tag/2.2.0) 🎉
> 
> ![badge](https://user-images.githubusercontent.com/3515448/54035470-bef51a00-41b9-11e9-8df0-7b85e6bb7781.gif)

Can you show an example on how you update the badgeValue in your GIF?
Thanks in advance

**Comment by msaps** [comment]
@RiyanFransen it's described in the docs here: [TMBadgeView](https://uias.github.io/Tabman/master/Classes/TMBadgeView.html)

I should maybe link that somewhere in the README 👍
