### ISSUE TITLE
I can't add UIImage 

### ISSUE THREAD

**Issue by jamalalayq** [uias/Tabman#389]
### Issue Description

When i try to set images in tabs not appeared, but text appeared and i can't change title color
![screen shot 2019-02-23 at 10 03 20 pm](https://user-images.githubusercontent.com/16099227/53291134-05f50f80-37b7-11e9-8a99-6f8f37587998.png)
![screen shot 2019-02-23 at 10 05 15 pm](https://user-images.githubusercontent.com/16099227/53291138-1e652a00-37b7-11e9-978f-297d0e97985a.png)

**Comment by msaps** [comment]
@jamalalayq strange - it looks as though the images are sizing correctly (as the buttons aren't zero frame) - could it be a tinting issue?

**Comment by jamalalayq** [comment]
Maybe but after it doesn't work as I want I removed it.
 but i will back.
 i was rendered the images as template.
 maybe this is the problem if was chosen tint color white.

**Comment by msaps** [comment]
@jamalalayq the `tintColor` will have been the issue.
