### ISSUE TITLE
I can't load any ViewControllers (UI controls). But I can change View Background

### ISSUE THREAD

**Issue by TomSambala** [uias/Tabman#390]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@TomSambala not sure what you mean?? More details are needed

**Comment by TomSambala** [comment]
When I pass an array of [viewControllers] in MyViewController unexpectedly nothing is shown in the Tabs. I can't see no UI controls (from the passed viewControllers) although I can change their background colors and whenever I try to access a control property in the one of the viewControllers it raises an error '**Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value**'. I'm sorry I'm kind of new to iOS, a help will be highly appreciated.
