### ISSUE TITLE
Auto Insetting does not seem to turn off

### ISSUE THREAD

**Issue by WingedDoom** [uias/Tabman#391]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues) 

### Issue Description

In the documentation it is said that Tabman does not handle insets automatically in cases when bar is embedded into other views. I am embedding my bar in a custom view, which mimics a navigation bar view, but provides custom behavior I need. I also manually calculate and set `contentInset` and `scrollIndicatorInsets` for root scroll view in each of my child view controllers. Initially everything is fine, but when I start scrolling (horizontally) to the next page, the next page's `contentOffset` is being changed to -20 (i.e. status bar height), which is incorrect for my case.

### Other useful things

I don't see how passing `.custom(view)` to `addBar` affects auto insetting behavior in code. Neither I see any changes in behavior when I set `automaticallyAdjustsChildInsets` to false in my `TabmanViewController` subclass' `loadView`: it will enable insetter when `true` and do nothing when `false`, and in `AutoInsetter`'s `_isEnabled` property is `true` by default, and there is no way to set it to `false`.

I attached a stack trace screenshot of what is happening, when I start scrolling to the next page (a breakpoint stops execution when `UIScrollView's` `contentOffset` changes):
<img width="517" alt="2019-03-03 3 37 00" src="https://user-images.githubusercontent.com/6613809/53689395-f7ce6280-3d65-11e9-8e76-cae94f7be8e3.png">

**Comment by WingedDoom** [comment]
In my case I couldn't find a way to prevent TabmanViewController from setting its pages' `contentOffset` on Pageboy's `willScrollToPage` delegate method without modifying its sources.

But I actually love the way that TabmanViewController knows when it needs to update the insets during its lifecycle, I just wanted to customize the calculation of the insets inside, so that they will reflect my custom view's (which a tab bar is embedded into) size. So I created a [fork](https://github.com/WingedDoom/Tabman/tree/feature/custom-auto-insetting) and added `open func calculateRequiredInsets() -> Insets` method, which by default returns `Insets.for(tabmanViewController: self)`. I also made TabmanViewController to use this method in `setNeedsInsetUpdate(to:)`. 

As a result, my modification allows for easier customization when embedding a tab bar into custom views, while not breaking any current behavior / APIs. If you like it, I would love to make a pull request. Its just, I have never contributed to any public library before, and I'm not really sure which branch should I set as a destination.

**Comment by msaps** [comment]
@WingedDoom the `AutoInsetter` always being enabled bug should be fixed in [1.5.1](https://github.com/uias/AutoInsetter/releases/tag/1.5.1) 🎉 

The PR sounds great - please make it against the `2.2.0` branch, which I'm hoping to release soon. Thanks for all the detail/input! 💯

**Comment by WingedDoom** [comment]
Oh, didn't receive an email notification for your reply. I'm going to file a PR right away then. Thanks!
