### ISSUE TITLE
Extend tabman under status bar

### ISSUE THREAD

**Issue by nachkar** [uias/Tabman#394]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by nachkar** [comment]
Dears how can I extend tabman under the status bar I integrate it in my view but white space is placed on top of the control how can I fix it ?

**Comment by msaps** [comment]
@nachkar are you using `TMSystemBar`? When adding a bar to the view controller you can use this to make it act like a system navigation bar/tab bar:

```swift
let bar = TMBar.ButtonBar()
addBar(bar.systemBar(), dataSource: self, at: .top)
```

**Comment by nachkar** [comment]
@msaps When I use TMSystemBar the background view disappears it become blurry !! but it fixed stretching under the status bar but how can I add the background view I need ?

**Comment by Jacolack** [comment]
I used:
 `let bar = TMBarView<TMConstrainedHorizontalBarLayout, TMTabItemBarButton, TMLineBarIndicator>()
addBar(bar.systemBar(), dataSource: self, at: .top)` 
but the bar still doesn't extend under the status bar, and still leaves white space. Is there something I'm doing wrong?

**Comment by msaps** [comment]
@Jacolack strange - could you share your view hierarchy?

**Comment by Jacolack** [comment]
@msaps I don't have much of one... my `TabmanViewController` is my `rootViewController` and I have one regular `UIViewController` in it.
