### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by iv-mexx** [uias/Tabman#399]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I'm wondering, have the accessibility improvements from https://github.com/uias/Tabman/pull/189 been lost with 2.0?

I'm trying to set Accessibility Labels for Tabs but can not figure out how to do this.

**Comment by msaps** [comment]
@iv-mexx looks like it was - will try and improve it in the next release. 

You do also have access to the raw button views with `TMBarView.buttons` - so you could use that to set labels on the tab buttons for now. But will look at improving some sort of access via the items 👍

**Comment by iv-mexx** [comment]
I'm taking a look at this currently. Re-instating the changes from #189 seems to be straight forward, but I think we can do even better

**Comment by msaps** [comment]
@iv-mexx @Patrick-Remy now available in [2.4.0](https://github.com/uias/Tabman/releases/tag/2.4.0)
