### ISSUE TITLE
Strange top space appears when scrolling to a page first time

### ISSUE THREAD

**Issue by nthtrung09it** [uias/Tabman#405]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Hi,
I have an application using Tabman. It contains 4 tabs.
When scrolling to 3rd and 4th page, it shows a strange top space then this space disappears quickly.
Please take a look at it.
Thank you very much.

### Other useful things
This is image for this issue:
<img width="383" alt="Top space appears when scrolling to a page first time" src="https://user-images.githubusercontent.com/7716509/54534606-4c591b00-49bf-11e9-8799-f6ddc66aa278.png">

This is video for this issue:
https://1drv.ms/v/s!ApC4rbpXqNSghKoB-WRTjtQPZeJR1A

This is source code:
[TestUICollectionHeight.zip](https://github.com/uias/Tabman/files/2978414/TestUICollectionHeight.zip)

**Comment by Jacolack** [comment]
I found a solution.
Although it is temporary, it works for me for a `UITableview` and a scrolling `UITextView`, both in a `UIViewController`, and both had the old problem.

How to fix:

1. Go to your Main.storyboard > your view controller > set simulated metrics "Top Bar" to none.

<img width="256" alt="Screen Shot 2019-03-26 at 10 07 01 PM" src="https://user-images.githubusercontent.com/20653966/55051697-85bf0580-5013-11e9-9c83-b15125d5a877.png">


2. Go to your View Controller > make all top constraints for your `UITableview` or `UIScrollView` relate directly to the top of your `UIViewController`.

<img width="333" alt="Screen Shot 2019-03-26 at 10 05 43 PM" src="https://user-images.githubusercontent.com/20653966/55051746-b0a95980-5013-11e9-8f98-bea686beb50d.png">

**Comment by nthtrung09it** [comment]
@Jacolack Thanks for your answer. It works perfectly.

Another solution I found:

1) Uncomment line 32 in my file `UIViewController.swift`:
`        self.automaticallyAdjustsChildInsets = false`

2) Add vertical space between first view and safe area (about 47) in Child View (`UInProgressTabViewController.swift`)

<img width="881" alt="Screen Shot 2019-04-06 at 3 44 36 PM" src="https://user-images.githubusercontent.com/7716509/55667207-78134680-5883-11e9-82db-c4dd4c84c30d.png">

**Comment by msaps** [comment]
@Jacolack @nthtrung09it this is described in the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md) - I should probably document it a bit better! Will also investigate whether the AutoInsetting feature can be improved
