### ISSUE TITLE
Example Project Fails

### ISSUE THREAD

**Issue by Jacolack** [uias/Tabman#408]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
After downloading the example, I run `carthage update`, but get the error in the Xcode log: 
`error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'BLTNBoard')`

**Comment by msaps** [comment]
@Jacolack need to update Tabman to support Xcode 10.2 / Swift 5 properly - will be on it ASAP..

**Comment by mohsinka** [comment]
I have a pod related issue as well. Cannot configure Example.

**Comment by msaps** [comment]
@Jacolack @mohsinka should be resolved with [2.3.0](https://github.com/uias/Tabman/releases/tag/2.3.0) - adds full Swift 5 / Xcode 10.2 compatibility 🎉
