### ISSUE TITLE
pod not working

### ISSUE THREAD

**Issue by pprevalon** [uias/Tabman#41]
i try using 
pod 'Tabman' and
pod 'Tabman', '~> 0.4'

but both are not installing i get error using cocoapod installer
Analyzing dependencies
[!] Unable to find a specification for `Tabman (~> 0.4)`

**Comment by msaps** [comment]
@pprevalon is your iOS version target 9.0 or above? `Tabman` only supports iOS 9 and newer. If so, please try running `pod repo update` and then run `pod install` again.

**Comment by pprevalon** [comment]
After running pod update and then install everything work. Thanks for this pod, I’ve been looking for something like this for a while. :)

**Comment by msaps** [comment]
@pprevalon glad to help! 😄
