### ISSUE TITLE
How to indicate that tabbar can be scrolled ?

### ISSUE THREAD

**Issue by qwsdxcqwsdxc** [uias/Tabman#411]
Is there any way that I can indicate that there are more the visible tab bar items ?. There is no way to indicate that the tabman tabbar can be scrolled .

**Comment by halgatewood** [comment]
Perhaps you could use `bar.fadesContentEdges = true` which ads a fade to the edge, letting the user know there is more. You can play with the `bar.layout.interButtonSpacing = 24.0` to space between the items to make them go off the edge your desired locations.

**Comment by msaps** [comment]
@qwsdxcqwsdxc yeah the only current built-in effect is the `fadesContentEdges` as described by @halgatewood. Not sure what else we can do, but open to suggestions if you have any...
