### ISSUE TITLE
dyld: Library not loaded: @rpath/Tabman.framework/Tabman

### ISSUE THREAD

**Issue by kanishk0008** [uias/Tabman#415]
### New Issue Checklist

- [x] Updated Tabman to the 1.10.2 version
- [x] Added library through carthage version 0.32.0

### Issue Description

I have to clean the project every time before running, if not it throws error Library not loaded.
Reason: image not found

**Comment by msaps** [comment]
@kanishk0008 try using Carthage `0.33.x` - they fixed a lot of Xcode 10.2 stuff

**Comment by kanishk0008** [comment]
The issue is still there ... I updated it to latest version ... still i have to clean it every single time to run

**Comment by msaps** [comment]
@kanishk0008 is your project correctly configured for Carthage? `carthage-copy-frameworks` etc.

**Comment by kanishk0008** [comment]
Yes ... I am not just using Tabman, I have 10 other dependencies like Alamofire, SwiftDate as well.
