### ISSUE TITLE
Change the title of page on Longpress

### ISSUE THREAD

**Issue by iosdroid** [uias/Tabman#416]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I need to update the page name value on runtime. when user longpress the particular page name its make up as editable and change the value at runtime

**Comment by msaps** [comment]
@iosdroid you could probably do this with a [custom bar button](https://uias.github.io/Tabman/master/going-custom.html#custom-bar-buttons). You also have access to the button views via `bar.buttons.all` to add gesture recognisers.
