### ISSUE TITLE
Not autolayout when change height contentView

### ISSUE THREAD

**Issue by btluan** [uias/Tabman#417]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
Tabman 2.3.0
<img width="445" alt="Screen Shot 2019-04-07 at 9 40 36 AM" src="https://user-images.githubusercontent.com/14282819/55677828-3e8d1a80-5919-11e9-8261-540a6dc33f46.png">

I use container view load tabman, when i update height container view then tabman not autolayout and i can't next or previous view

**Comment by msaps** [comment]
@btluan are you doing any custom layout with the `TMBar` in your view?

Try enabling `clipsToBounds` on the container and see if the bar is visible - if not then the container isn't constrained properly to the bar
