### ISSUE TITLE
Using Tabman, 2.3.0, and I am still getting warning that I have to convert Tabman to Swift 5 

### ISSUE THREAD

**Issue by h36ahmed** [uias/Tabman#418]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Using Tabman, 2.3.0, and I am still getting warning that I have to convert Tabman to Swift 5. I have posted a screenshot.

### Other useful things

![image](https://user-images.githubusercontent.com/13081913/55730034-529e4e00-59e5-11e9-8c7f-e1f58fa21a2a.png)

**Comment by msaps** [comment]
@h36ahmed yeah unfortunately I don't think there is anything we can do about the warnings - we maintain compatibility with Swift 4 currently so have to set the project's Swift version to `4.0`.
