### ISSUE TITLE
Update the Doc for New Users

### ISSUE THREAD

**Issue by yungdbo** [uias/Tabman#419]
### New Issue Checklist

- [X ] Updated Tabman to the latest version
- [ X] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ X] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I'm not one to complain when it comes to open source libraries or libraries that make rapid development easier for developers that want to make a compelling product. When it comes to documentation though, you need to prioritize that especially for users that weren't apart of your version 2 changes. 

As a new user trying to integrate your library into my app it is extremely confusing when you are working with legacy documentation that hasn't been updated since it was created. The fact I look at the main page and it is referencing changes that were done months ago amazes me. I mean you literally changed the whole architecture on how a tab bar is created. Where is the support? I understand you guys don't do this full time, but for the new users and believers in the product, please prioritize updating your documentation for the sake your product.

**Comment by msaps** [comment]
@yungdbo what legacy documentation are you referring to?

We also put quite a lot of effort into documentation for Tabman 2, including the [Documentation Website](https://uias.github.io/Tabman/master/). Any actual concrete feedback or pointers to what is wrong would be much appreciated.

Also please try and make things remotely constructive, being an arse doesn't help anybody. 🙂
