### ISSUE TITLE
view controllers are behind tabbar and navigationbar

### ISSUE THREAD

**Issue by pprevalon** [uias/Tabman#42]
Im using navigation controller for the tabbar my viewcontroller and UITableviews, my tableview controller table item are at the top hidden by the tabbar controller how can i have an inset to put it below.

**Comment by msaps** [comment]
@pprevalon this is an issue in the latest version, well kind of...

There is a property available in `TabmanBarConfig` (`self.bar`) called `requiredContentInset` which ideally should provide the required insets needed to present underneath the bar. This is currently broken and returning incorrect values. So I'll get that fixed ASAP.

This also leads onto another issue, where really the insetting of child controllers should automatically be handled internally. So I'll raise another issue for automatic insetting, and get that in the next version too. 

For now, you might have to manually inset the content. Setting a `contentInset.top` of around 44pt should give a temporary fix.

**Comment by pprevalon** [comment]
Great im looking forward to the update. 





Pierre Prevalon
407-600-0251
pprevalon@gmail.com
/// Online Resume
www.pierreprevalon.com

**Comment by emadd** [comment]
Where exactly would you want to set contentInset.top?

**Comment by pprevalon** [comment]
Where can I access contentInset.top I couldn't locate it anywhere

**Comment by msaps** [comment]
@pprevalon @emadd apologies maybe I wasn't clear. To get the table view / collection view to display correctly underneath the `TabmanBar` you currently need to set the `contentInset` of the `UIScrollView` manually. 

If you integrate `Tabman` from the develop branch you can use the `requiredContentInset` property on `TabmanViewController.bar` to get the exact values that are required for the `contentInset`. This is currently broken in the latest release. Fix is [here](https://github.com/uias/Tabman/pull/44).

**Comment by msaps** [comment]
I've just released [0.4.4](https://github.com/uias/Tabman/releases/tag/0.4.4) which fixes the issues with the `requiredContentInset` property available on `TabmanViewController.bar`.

This property will provide you with the required `contentInset` that any child view controller will need to use if it wants to be displayed correctly underneath the `TabmanBar`

**Comment by pprevalon** [comment]
I update  this is how my code look but the inset does not work


 




override func viewWillAppear(_ animated: Bool) {
        self.title = "Messages"
        self.bar.requiredContentInset.top = 200.0
        self.bar.appearance = TabmanBar.Appearance({ (appearance) in
            // customise appearance here
            appearance.indicator.bounces = true
            appearance.interaction.isScrollEnabled = true

        })
    }



It look like this should work but the top inset does not work. The views are still below. I even cleaned the project but nothing changed.

**Comment by msaps** [comment]
@pprevalon the `requiredContentInset` property is not settable, it provides you with the `contentInset` that is required to display a view controller's contents correctly underneath the bar. 

You currently must manually set this `contentInset` on your child view controller's contents. Also ensure you're on 0.4.4.

**Comment by pprevalon** [comment]
Got it thanks.

**Comment by msaps** [comment]
Just released [0.5.0 Beta 1](https://github.com/uias/Tabman/releases/tag/0.5.0.beta.1) which features the automatic insetting behaviour. Would really appreciate giving it a try and providing any feedback.

I'm going to close off this issue, please see the [Automatic Insetting issue](https://github.com/uias/Tabman/issues/43) for further discussion! 😄

**Comment by annjawn** [comment]
Does this apply if the tabman bar is at the `.bottom`, because the same issue exists with bottom too. I am using a bottom tabman bar and my tableviews are kind of hidden behind it (well atleast the last row or parts of the last row gets hidden behind it). How do we fix that?
