### ISSUE TITLE
How to custom indicator width

### ISSUE THREAD

**Issue by yeziahehe** [uias/Tabman#420]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I use version 2.3.0, and use bar.indicator.size, but it only works on height, not works on width

**Comment by msaps** [comment]
@yeziahehe which indicator type are you using?

**Comment by yeziahehe** [comment]
TMLineBarIndicator

**Comment by msaps** [comment]
@yeziahehe currently `TMLineBarIndicator` is only able to be the width of the button it is indicating the position of. 

Will create another issue for an enhancement to allow this. You can of course create a custom indicator for now 🚀
