### ISSUE TITLE
tab bar how to set back button 

### ISSUE THREAD

**Issue by hemanth210** [uias/Tabman#422]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
@hemanth210 unsure what you mean by the back button? Tabman shouldn't affect back buttons or navigation.
