### ISSUE TITLE
Unable to set tint color and selected tint color on custom TMBarView

### ISSUE THREAD

**Issue by eirikvaa** [uias/Tabman#426]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I have a custom `TMBar` of type `TMBarView<TMConstrainedHorizontalBarLayout, TMTabItemBarButton, TMLineBarIndicator>`, but am unable to customise the `tintColor` and `selectedTintColor`. In other words, the following have no effect;

```swift
bar.buttons.customize {
    // The following works, just as an example.
    $0.shrinksImageWhenUnselected = false
    // The following does not work, colours just as an example.
    $0.selectedTintColor = .blue
    $0.tintColor = .red
}
```

Selected buttons have a slightly darker gray tint colour, and un-selected buttons have a slightly lighter gray tint colour. None of the colour changes in the code snippet work.

**Comment by msaps** [comment]
@eirikvaa hmm I can't seem to reproduce this - tested in the example and a demo project (attached) using your configuration and it all seems to work as intended. 

Could you maybe take a look and see if you can reproduce it in that? 😄

[Tabman ColorTest.zip](https://github.com/uias/Tabman/files/3101014/Tabman.ColorTest.zip)

**Comment by eirikvaa** [comment]
Thanks so much for helping me debug this, really appreciate it. I'm not able to reproduce it. In your project I can see that your `barItem(for:at:)` returns a `TMBarItem(title:)` instance, but in my case, I return a `TMBarItem(image:)` instance. If I use your implementation I see the correct colours (I changed the colours), as shown in the image below:

<img width="330" alt="Skjermbilde 2019-04-24 15 02 49" src="https://user-images.githubusercontent.com/6376002/56661522-30255980-66a2-11e9-93a9-7087586ec6a1.png">

With my intended implementation, using images, this is what I see:

<img width="330" alt="Skjermbilde 2019-04-24 15 05 59" src="https://user-images.githubusercontent.com/6376002/56661638-7a0e3f80-66a2-11e9-977a-082effce6523.png">

That is *just* by changing the type of `TMBarItem` in `barItem(for:at:)`.

I would expect to see the images also change colours, because that worked totally fine before upgrading to version 2.

**Comment by msaps** [comment]
@eirikvaa hmm, even with that still seems to work for me. Is your image set to render as a template? Assume so if it worked in v1...

<img width="261" alt="Screenshot 2019-04-28 at 13 14 58" src="https://user-images.githubusercontent.com/3515448/56863539-adf5a780-69b7-11e9-98e0-35e981f454ab.png">

**Comment by eirikvaa** [comment]
They are set to render as `Default`, I'm not sure if that's `Original Image` or `Template Image`.

**Comment by msaps** [comment]
@eirikvaa try setting them to be template images - I think that will fix the issue. I should also add an improvement to Tabman so that this happens by default

**Comment by eirikvaa** [comment]
It worked, thank you so much! That was literally the last piece in the puzzle 😄
