### ISSUE TITLE
Crash [Tabman.TabmanScrollingButtonBar safeAreaLayoutGuide]: unrecognized selector

### ISSUE THREAD

**Issue by nicholausadi** [uias/Tabman#431]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I got crash in Firebase Crashlytics like this
-[Tabman.TabmanScrollingButtonBar safeAreaLayoutGuide]: unrecognized selector sent to instance 0x16fe7010

It happens in iOS 11 and 12.
Around 55% Jailbroken devices

Can someone help me with this?

**Comment by msaps** [comment]
@nicholausadi ah this could be related to #438.. 

Does anyone know why this happens?? @nghiaphunguyen maybe?
