### ISSUE TITLE
I can't run Tinderbar .

### ISSUE THREAD

**Issue by FallacyWalker** [uias/Tabman#439]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I can't run Tinderbar , and see the screenshot .
![Screen Shot 2019-07-07 at 17 35 47](https://user-images.githubusercontent.com/20806018/60766594-5a51b980-a0de-11e9-8a91-4c4bc5e2cb98.png)

**Comment by msaps** [comment]
@FallacyWalker hmm maybe something is wrong with the Carthage config - will check it out. Assume it works fine on the simulator?
