### ISSUE TITLE
bar and viewcontrolers can not be put together 

### ISSUE THREAD

**Issue by FallacyWalker** [uias/Tabman#441]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I put a bar into a custom uiview ,but I got this , maybe there's something missing , but I can't figure it out .

### Other useful things

Code:

    override func viewDidLoad() {
        super.viewDidLoad()
        let vc1 = UIViewController()
        let vc2 = UIViewController()
        viewControllers = [vc1,vc2]
        self.dataSource = self
        addViews()
        let bar = TMBar.ButtonBar()
        bar.height(50)
        bar.layout.transitionStyle = .snap
        bar.layout.interButtonSpacing = K.SCREEN.WIDTH * 0.3
        bar.layout.contentInset = UIEdgeInsets(top: 0.0, left: 100.0, bottom: 0.0, right: 50.0)
        bar.indicator.weight = .custom(value: 2.0)
        bar.buttons.customize { (button) in
            button.font = UIFont.systemFont(ofSize: 14)
        }
        addBar(bar, dataSource: self, at: .custom(view: container, layout: nil))
    }
    func addViews() {
        view.addSubview(line1)
        view.addSubview(container)
        line1.topToSuperview(offset: 100)
        line1.leftToSuperview()
        line1.rightToSuperview()
        line1.height(20)
        container.topToBottom(of: line1)
        container.leftToSuperview()
        container.rightToSuperview()
        container.bottomToSuperview()
        
    }

The green part(line1) is another UIView , the gray part(container) is the custom UIView .

Screenshot:

![Simulator Screen Shot - iPhone 6s - 2019-07-07 at 23 58 31](https://user-images.githubusercontent.com/20806018/60770995-e8946280-a113-11e9-83ac-b6eeb8f501f9.png)

**Comment by msaps** [comment]
@FallacyWalker it looks like the constraints with your `container` are maybe a little funky and pinned to the top and bottom of the superview?

**Comment by sugitatestblue** [comment]
`bar.height(50)` not works.
