### ISSUE TITLE
Unable to Run Example Program

### ISSUE THREAD

**Issue by SwarajMeetIOSDeveloper** [uias/Tabman#442]
### New Issue Checklist

- [ ] Missing Frameworks

### Issue Description

 I downloaded the example project but there missing files for frameworks 
BLTNBoard

**Comment by msaps** [comment]
@SwarajMeetIOSDeveloper take a look [here](https://github.com/uias/Tabman/blob/master/CONTRIBUTING.md#setting-up-the-project-for-development)

**Comment by g20000** [comment]
Same problem(
