### ISSUE TITLE
Spelling error in the documentation

### ISSUE THREAD

**Issue by hellaandrew** [uias/Tabman#447]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

This is a simple one. I was looking at the [directions](https://github.com/uias/Tabman/blob/master/CONTRIBUTING.md#setting-up-the-project-for-development) on how to clone your project for testing, and I found a spelling error under **Setting up the project for development**:

`Run carthage bootstrap --plaftorm ios `

The spelling error is in the word platform. Please change it to

`Run carthage bootstrap --platform ios`

**Comment by msaps** [comment]
@hellaandrew - thanks, fixed 👍
