### ISSUE TITLE
TMBarButton fails to resize when selected font is larger than font

### ISSUE THREAD

**Issue by sinataghva** [uias/Tabman#448]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When customizing the appearance of TMBarButton like this:

```
bar.buttons.customize { (button) in
	button.font = UIFont.systemFont(ofSize: 14)
        button.selectedFont = UIFont.systemFont(ofSize: 14, weight: .bold)
}
```

If the `selectedFont` is larger than `font` or as we see in the example, it's just a bold font of same size and takes more space, the button fails to resize correctly to the new text size when selected and we see the text is truncated after selecting the second tab.

![image](https://user-images.githubusercontent.com/20970283/62605595-c9e3e000-b8fa-11e9-8d30-5f5147c2e1d3.jpeg)

![image](https://user-images.githubusercontent.com/20970283/62605655-d9632900-b8fa-11e9-8f9f-8a62858c92c8.jpeg)

It also happens for the initially selected button 

![image](https://user-images.githubusercontent.com/20970283/62606732-1defc400-b8fd-11e9-947e-f20d6352e6f9.jpeg)

### Other useful things

I found out a work around by implementing these two methods that force the button to be updated whenever tapped on or scrolled to. However I don't know if it's the best way to fix this or if it can be fixed in the TabMan internal mechanism instead.

```
override func bar(_ bar: TMBar, didRequestScrollTo index: PageboyViewController.PageIndex) {
        super.bar(bar, didRequestScrollTo: index)
        bars.first?.items?[index].setNeedsUpdate()
}
    
override func pageboyViewController(_ pageboyViewController: PageboyViewController, didScrollToPageAt index: TabmanViewController.PageIndex, direction: PageboyViewController.NavigationDirection, animated: Bool) {
        super.pageboyViewController(pageboyViewController, didScrollToPageAt: index, direction: direction, animated: animated)

        bars.first?.items?[index].setNeedsUpdate()
}
```

This time it won't be truncated:

![image](https://user-images.githubusercontent.com/20970283/62606212-02d08480-b8fc-11e9-944f-23ceb7cd72a0.jpeg)

Also in order to fix it for the first and initially selected button, we should force it to update after adding the bar:

```
addBar(bar, dataSource: self, at: .custom(view: tabBarContainerView, layout: nil))        
bar.items?.first?.setNeedsUpdate()
```

The result will be like this:

![image](https://user-images.githubusercontent.com/20970283/62608041-68724000-b8ff-11e9-8465-f6c5276f11f6.jpeg)

**Comment by jiao808813** [comment]
+1

**Comment by msaps** [comment]
@sinataghva apologies this took so long 😰

**Comment by sinataghva** [comment]
> @sinataghva apologies this took so long 😰

No problem. Thanks.
