### ISSUE TITLE
Crash in TabmanViewController.calculateRequiredInsets()

### ISSUE THREAD

**Issue by sasojadrovski** [uias/Tabman#449]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Hi @msaps,

Once again, thank you for this great library and for continuing your great work on it, which also includes exceptional support. Keep it up! 🎉 

Recently I've noticed a lot of crashes that seem to have something to do with the `calculateRequiredInsets` method. From the crash logs it also seems like it invokes an indefinite loop of some sort. I can also say that 100% of the crashes happened on an iPhone X, 99% of which happen on iOS 11 and 1% on iOS 12. Also, 25% of the devices are Jailbroken. 

It looks like that calling `tabmanViewController.view.layoutIfNeeded()` in the `for(tabmanViewController:)` method might cause the indefinite cycle.

I would appreciate if you could take a look into this. Unfortunately, except for the crashlogs, I am unable to provide a sample app that demonstrates the crash, since I cannot seem to reproduce it on my end.
 
### Other useful things
[Stack trace](https://github.com/uias/Tabman/files/3477362/issue_crash_a4edf99c441a4f2eb183710f6f5f9252_DNE_0_v2.txt)

I have attached a raw text file of the stack trace. Hope it helps.

Looking forward to hearing from you.

Cheers!

**Comment by sasojadrovski** [comment]
Just to add, a similar crash has been noticed on iPhone XS Max, 100% on iOS 12, all devices are non jailbroken.

This time, the crash happens in `TabmanViewController` on line `376` inside `setNeedsInsetsUpdate(to:)`, and once again, an indefinite cycle occurs. 

I hope this feedback helps. :)

**Comment by msaps** [comment]
@sasojadrovski thanks for all the info - will try and get this fixed ASAP

**Comment by sasojadrovski** [comment]
> @sasojadrovski thanks for all the info - will take a look and try and get this fixed 👍

You are welcome! Thank you very much for looking into this and please feel free to let me know if you need anything else or if there's something I could do to help :)
