### ISSUE TITLE
Removing PureLayout Dependency

### ISSUE THREAD

**Issue by soheilbm** [uias/Tabman#45]
I would like to propose of removing PureLayout framework from this project. 
I can make a pull request for changing to normal constraint without using PureLayout.

**Comment by msaps** [comment]
@soheilbm I agree, haven't yet done it due to just wanting to get the project out there, but I'd definitely prefer to not have an additional dependency.

**Comment by AFcgi** [comment]
@soheilbm Please make a pull request. I think it make sense to remove an additional dependency.

**Comment by msaps** [comment]
Going to park this for now. As much as I can see the advantage of removing another dependency, the work involved is pretty substantial and doesn't offer much benefit. 

If anyone wants to have a go and do a PR, more than appreciated. 👍
