### ISSUE TITLE
Update Package.swift to swift-tools-version:5.1

### ISSUE THREAD

**Issue by alexito4** [uias/Tabman#453]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Tabman can't be used in Xcode 11 SPM support because the Package.swift is using the old version 3.1. 
SPM support should be updated to use the most recent version of the tools so it can be used in the upcoming Xcode version.

### Other useful things

<img width="645" alt="Screenshot 2019-08-21 at 08 55 50" src="https://user-images.githubusercontent.com/750912/63409448-7d67cc80-c3f1-11e9-9203-523d6d6edd71.png">

**Comment by msaps** [comment]
@alexito4 cheers - will get it sorted 👍

**Comment by msaps** [comment]
@alexito4 now available on `master` and will be in the `2.6.0` release 🚀
