### ISSUE TITLE
how to custom indicator to be image

### ISSUE THREAD

**Issue by ahmedsafadii** [uias/Tabman#454]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/6974081/63431160-f1709780-c426-11e9-9d05-4dbe5406f30b.png

use image like this ?

**Comment by msaps** [comment]
@ahmedsafadii this could be achieved by creating a custom `TMBarIndicator` - see here: https://uias.github.io/Tabman/master/going-custom.html#custom-bar-indicator
