### ISSUE TITLE
How to detect click on bar item?

### ISSUE THREAD

**Issue by Harshjain2094** [uias/Tabman#463]
Hi, I am working on a project which need to detect whether there has been a click on the bar button item with respective index. how to achieve that with some delegate property of Tabman.

Thanks in advance.

**Comment by dgenyk-techmagic** [comment]
@Harshjain2094 please check PageboyViewControllerDelegate methods for this.

**Comment by Harshjain2094** [comment]
I have checked but click on the tab button is not there/provided in delegate.

**Comment by dgenyk-techmagic** [comment]
@Harshjain2094 First you should conform PageboyViewControllerDelegate protocol in your class, then become to be responsible for delegate methods (`self.delegate = self`)
and last implement delegate methods 
e.g. `func pageboyViewController(_ pageboyViewController: PageboyViewController,                                 
 willScrollToPageAt index: TabmanViewController.PageIndex, direction: PageboyViewController.NavigationDirection, animated: Bool)`

**Comment by msaps** [comment]
@Harshjain2094 - @dgenyk-techmagic is correct, you can use the `PageboyViewControllerDelegate` functions to detect this. 

`willScrollToPageAt` will be called as soon as the page view controller is about to move to another page, if you want to exclusively detect animated transitions (when the user has pressed a tab button) you can use the `animated` flag.

However you should not reassign the `delegate` of the `TabmanViewController` - instead make a subclass of `TabmanViewController` and override the function.
