### ISSUE TITLE
Centered Alignment Not Working As Intended

### ISSUE THREAD

**Issue by townsendeb** [uias/Tabman#467]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

The implementation of the "centered alignment" does not match what it previously was in older versions. Currently when you select centered, and depending on how many buttons you have, the first few are centered but the last two are not. 

In previous versions, all buttons would be centered no matter the number of buttons. How can I accomplish this same functionality with the new versions?

### Other useful things

Example of the first one being centered:
![Simulator Screen Shot - iPhone 11 - 2019-10-01 at 11 13 32](https://user-images.githubusercontent.com/16887846/65980348-91650c00-e43c-11e9-9707-3d36c22bc24e.png)

Example of the last one not being centered:
![Simulator Screen Shot - iPhone 11 - 2019-10-01 at 11 13 36](https://user-images.githubusercontent.com/16887846/65980377-a17ceb80-e43c-11e9-8681-6ffe01273666.png)

**Comment by msaps** [comment]
@townsendeb now available in [2.6.2](https://github.com/uias/Tabman/releases/tag/2.6.2) 🎉
