### ISSUE TITLE
Header above TabBar?

### ISSUE THREAD

**Issue by Urkman** [uias/Tabman#47]
Is there a chance to add a header above TabBar?
Like here:
https://github.com/noties/Scrollable

**Comment by msaps** [comment]
@Urkman this is certainly possible, though it isn't directly available in `Tabman` out of the box. 

You could achieve it by either embedding or attaching a `TabmanBar` externally. Please see the Advanced Customisation documentation for more info on how to do this: [Advanced Customisation](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md).

The bar would be located in an external header view that is within the parent `TabmanViewController`; this would then be updated via scroll events that are passed up from the child view controllers.

```
Parent View Controller (TabmanViewController)
     -> Header View (with embedded / attached TabmanBar)
          ^ scroll view updates (update constraints)
     -> [Child View Controllers]
```

**Comment by Urkman** [comment]
Thanks for your answer :)
I will give it a try... Perhaps you can add an example for this ;)

**Comment by msaps** [comment]
Maybe when I get a bit of free time... 😄
