### ISSUE TITLE
Can't interact with View Controller in Tab

### ISSUE THREAD

**Issue by asikand** [uias/Tabman#471]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
Can't interact with contents of Tab 

As you can see in the image I have a sole UIButton in the ViewController referred to by the first tab. I cannot interact with the button despite user interaction being enabled. Is it something to do with setting a delegate or something?

### Other useful things
<img width="402" alt="Screen Shot 2019-10-20 at 11 20 36 PM" src="https://user-images.githubusercontent.com/47344576/67174533-59dce600-f390-11e9-9b6e-fa8f034bff99.png">

**Comment by saltyskip** [comment]
What was the solution to this?
