### ISSUE TITLE
Tablayout constraints

### ISSUE THREAD

**Issue by SupranJowti** [uias/Tabman#474]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
Warning 

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x282f59590 V:[UIStackView:0x105c16920]-(0)-|   (active, names: '|':_TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x105c16640 )>",
    "<NSLayoutConstraint:0x282f59540 V:|-(8)-[UIStackView:0x105c16920]   (active, names: '|':_TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x105c16640 )>",
    "<NSLayoutConstraint:0x282f5a6c0 '_UITemporaryLayoutHeight' UIStackView:0x105c1ca60.height == 0   (active)>",
    "<NSLayoutConstraint:0x282f5afd0 'UISV-canvas-connection' UIStackView:0x105c1ca60.top == _TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x105c16640.top   (active)>",
    "<NSLayoutConstraint:0x282f5b070 'UISV-canvas-connection' V:[_TtGC6Tabman9TMBarViewCS_21TMHorizontalBarLayoutCS_16TMLabelBarButtonCS_18TMLineBarIndicator_:0x105c16640]-(0)-|   (active, names: '|':UIStackView:0x105c1ca60 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x281f57070 Tabman.TMBarViewLayoutGrid:0x119f1ea10.height == UIStackView:0x119f1d850.height   (active)>

**Comment by akaakoz** [comment]
@SupranJowti 
How did you solve this issue?
I had the same warning because I set `button.layout.contentInset` before chaing font size or color such as `button.font`, `button.tintColor`.

**Comment by SupranJowti** [comment]
I do not remember the solution but can you give me your implementation.
