### ISSUE TITLE
状态栏隐藏与否设置失败

### ISSUE THREAD

**Issue by liuxiaozhi88** [uias/Tabman#475]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by msaps** [comment]
??
