### ISSUE TITLE
Broken layout - tableviews get under bar after selecting a different tab

### ISSUE THREAD

**Issue by janandre** [uias/Tabman#478]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I have a top bar with tag like buttons.
```
        self.dataSource = self
        self.delegate = self
        self.isScrollEnabled = false
                
        // Create bar
        let bar = TMBarView<TMHorizontalBarLayout, TMLabelBarButton, TMBarIndicator.None>()
        bar.backgroundView.style = .flat(color: UIColor.systemBackground)
        bar.layout.contentInset = UIEdgeInsetsMake(16, 8, 16, 8)
        
        bar.buttons.customize { (button) in
            button.contentInset = UIEdgeInsetsMake(16, 16, 16, 16)
            button.layer.cornerRadius = 5
            button.clipsToBounds = true
            button.font = UIFont.systemFont(ofSize: 13, weight: UIFont.Weight.heavy)
            button.backgroundColor = .systemFill
            button.tintColor = UIColor.tertiaryLabel
            button.selectedTintColor = .label
        }
        
        // Add to view
        addBar(bar, dataSource: self, at: .top)
```

The default / first tab ist loaded fine. After selecting a different one, the tableviews get under the bar. I guess the insets are wrong.

### Issue Workaround
Maybe it's the root cause but I expect Tabman to handle it.

The tabman controller holds an array of objects. (not view controllers)
```
func viewController(for pageboyViewController: PageboyViewController,
                        at index: PageboyViewController.PageIndex) -> UIViewController?
```
Within that function these objects return a view controller created from scratch.
Which seems to be a problem for tabman.

I solved it by mapping all view controllers into an array and use them directly.
So there is an issue with dynamically instantiated ones.

**Comment by msaps** [comment]
@janandre think this is related to UIKit lifecycle stuff (when they are dynamically instantiated inside the `viewController(for:)` function. Will check it out
