### ISSUE TITLE
How to customize Tabbar indicator

### ISSUE THREAD

**Issue by SrikanthRaju** [uias/Tabman#479]
<img width="363" alt="Screenshot 2019-11-29 at 9 06 23 PM" src="https://user-images.githubusercontent.com/3455018/69879219-e1e9d000-12ec-11ea-86cb-0165ba506deb.png">

How to customize Tabbar indicator?

**Comment by msaps** [comment]
@SrikanthRaju the properties that can be customised are unique to the type of indicator class you are using - check out the [Indicator docs](https://uias.github.io/Tabman/master/Indicator.html) which gives an overview of all the types and their public properties.

If you require a custom solution this can also be achieved with a [custom indicator](https://uias.github.io/Tabman/master/going-custom.html#custom-bar-indicator) 👍
