### ISSUE TITLE
Hight of Tabman & unselected tabs line color

### ISSUE THREAD

**Issue by pingusNikalex** [uias/Tabman#480]
how to set custom height for TMBar.ButtonBar()?
how to set unselected tabs line color. I attached image for [example[](url)](url
<img width="356" alt="Screenshot 2019-12-10 at 19 13 05" src="https://user-images.githubusercontent.com/6975259/70552021-46285180-1b81-11ea-85af-7d1c8aa37ede.png">
)

**Comment by msaps** [comment]
@pingusNikalex the bar will autosize itself via its required `intrinsicContentSize`. You could force it to fit to a custom height by embedding it in a custom view which is constrained to a specific height (see [Adding a bar](https://uias.github.io/Tabman/master/adding-a-bar.html))

The unselected tabs do not feature an indicator.
