### ISSUE TITLE
bar.scrollMode is invalid

### ISSUE THREAD

**Issue by jiao808813** [uias/Tabman#482]
When I set bar.scrollMode = .none, nothing is different. 
IphoneX,iOS 13.3,Tabman 2.6

**Comment by msaps** [comment]
@jiao808813 setting it to `none` should disable a user from manually swiping the bar / between pages. What are you seeing when setting this?

**Comment by jiao808813** [comment]
> @jiao808813 setting it to `none` should disable a user from manually swiping the bar / between pages. What are you seeing when setting this?

I want to disable page's swipe gesture, but failed.

**Comment by msaps** [comment]
@jiao808813 this can be set with `isScrollEnabled = false` on the `TabmanViewController` - `bar.scrollMode` only affects the bar, not the view controller.
