### ISSUE TITLE
How change color when button change state ? 

### ISSUE THREAD

**Issue by Tawfikk** [uias/Tabman#486]
This my code for bar configure, but when I tapped button, color not change. What am I doing wrong ? 

```
   func topBarConfigure() {
        let bar = TMBar.ButtonBar()
        bar.indicator.isHidden = true
        bar.layout.contentInset = UIEdgeInsets(top: 10, left: 16.0, bottom: 0, right: 16.0)
       
        bar.buttons.customize { button in
            button.layer.cornerRadius = 4
            button.selectedTintColor = .white
            button.layer.masksToBounds  = true
            button.contentInset = UIEdgeInsets(top: 12, left: 16.0, bottom: 12, right: 16.0)
            button.selectedTintColor = .white
            
            
            switch button.selectionState {
            case .unselected:
                button.tintColor = .white
                button.backgroundColor = .gray
            case .partial(_):
                button.tintColor = .white
                button.backgroundColor = .mainGreen
            case .selected:
                button.tintColor = .white
                button.backgroundColor = .mainGreen
            }
        }
        
        addBar(bar, dataSource: self, at: .top)
    }
```

**Comment by Tawfikk** [comment]
@msaps

**Comment by msaps** [comment]
@Tawfikk what color property are you wanting to change? Note that `customize()` is not called when the bar position updates so your switch statement would only ever execute on the initial pass and set the properties according to the state at that time.

Also apologies for the slow response!

**Comment by Tawfikk** [comment]
I want to update color for background color on pager buttons.

Like this

<img width="725" alt="Screenshot 2020-01-12 at 20 02 49" src="https://user-images.githubusercontent.com/28268405/72221709-857a0180-3576-11ea-8ed4-17cd6f1cdc48.png">

**Comment by antoinepemeja** [comment]
Hello @msaps  and thank you for this library!
I have to implement the same logic, the background of `TMBarButton` has to change when it is selected. You confirm that it's not possible currently, we can just customize the `tintColor` with `selectedTintColor` and `tintColor`? Maybe we can send you a PR to add 2 properties: `backgroundColor` and `selectedBackgroundColor`? Thank you

**Comment by Gurungboi** [comment]
Hello @msaps,

**Comment by Gurungboi** [comment]
Hi @Tawfikk , 
Did u manage to alcomplish it?

**Comment by Tawfikk** [comment]
@Gurungboi no, this no actually for me. I solved my problem by using other library

**Comment by Gurungboi** [comment]
@Tawfikk  i am still trying but which library are you using?

**Comment by Gurungboi** [comment]
@Tawfikk I manage to change its state using pageboyViewController.

**Comment by sugitatestblue** [comment]
WHY don't you write how to resolve it?
I waste a lot of time. 
not need `PageboyViewController`

I wrote it 
```
class TabPagerButton: Tabman.TMLabelBarButton {
    override func update(for selectionState: TMBarButton.SelectionState) {
        switch selectionState {
        case .selected:
            backgroundColor = .red
        default:
            backgroundColor = .clear
        }

        super.update(for: selectionState)
    }
}
```

and replaced  `TMLabelBarButton` to `TabPagerButton`
```
`let barView = TMBarView<TMHorizontalBarLayout, TabPagerButton, TMBarIndicator.None>()`
```
