### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by shitoexe** [uias/Tabman#49]
Hello. I have found retain cycle between TabmanViewController and TabmanBarConfig. They keep each other in loadView method. This cycle is similar one as in your Pageboy project in which i had created issue few minutes ago. Could you make delegate property in TabmanBarConfig as weak? Thank you.

```
open override func loadView() {
        super.loadView()
        
        self.delegate = self
        self.bar.delegate = self
        
        // add bar to view
        self.reloadBar(withStyle: self.bar.style)
        self.updateBar(withLocation: self.bar.location)
    }
```

**Comment by msaps** [comment]
@shitoexe thanks again for pointing this out, resolved and updated in [0.4.5](https://github.com/uias/Tabman/releases/tag/0.4.5).
