### ISSUE TITLE
Swift Package Error

### ISSUE THREAD

**Issue by alexjameslittle** [uias/Tabman#501]
### New Issue Checklist

- [ ✅] Updated Tabman to the latest version
- [ ✅] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ ✅] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When archiving the project which has catalyst support I receive this error which causes the archive to fail

`target at '/Users/vagrant/Library/Developer/Xcode/DerivedData/Onin-gbjohfmkfxrqoccycrhymazxcvvk/SourcePackages/checkouts/Tabman' contains mixed language source files; feature not supported`

**Comment by alexjameslittle** [comment]
This has become an issue since Xcode 11.4

**Comment by filiplazov** [comment]
I can confirm I have the same issue.

**Comment by filiplazov** [comment]
And the issue does not happen on archiving only, it does on any build.

**Comment by alexjameslittle** [comment]
Yep only noticed it as my CI on bitrise was using xcode 11.4 before I was locally. You cannot add the package as a dependency at all

**Comment by msaps** [comment]
This is now fixed as of [2.8.1](https://github.com/uias/Tabman/releases/tag/2.8.1) - apologies for the delay!! 🎉
