### ISSUE TITLE
More State options

### ISSUE THREAD

**Issue by james-ff** [uias/Tabman#51]
Have migrated from MSSTabbedPageViewController. Would like the ability, additional to setting colours, to set the font of the selected item and consequently of unselected items too (could do this previously). Great library by the way! I love it!

**Comment by msaps** [comment]
@james-ff thanks, glad you're enjoying it! 👍 

Still pretty early on so there are a few little problems and omissions.. You can specify a custom font for bar items currently with the `.text.font` property on `TabmanBar.Appearance`. However there is currently a bug which means this doesn't always get applied to all styles. It gets applied fine on the `.scrollingButtonBar` style, but other styles not so well. I'll get this fixed and into the next release. 

With the selected item font it's a little more interesting. I'd like to be able to support progressive animation consistently with bar items during transitions (similar to how the item colour fades from unselected to selected as you scroll). Having two separate fonts makes this impossible to interpolate between; however this could be done using font weights.
 
Would the option of a `.text.selectedFontWeight` appearance property be of use? So you could use a custom font for all items and then specify a bold weight for selected items?

**Comment by james-ff** [comment]
Yeah that would be a good compromise!

**Comment by msaps** [comment]
Closing due to the issues mentioned in #54
