### ISSUE TITLE
How to change color when button change state in TMLabelBarButton?

### ISSUE THREAD

**Issue by Gurungboi** [uias/Tabman#515]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
 func setupTabBar() {
        self.bar.backgroundView.style = .clear
        self.bar.backgroundColor = .red
        self.bar.layout.interButtonSpacing = 0.0
        self.bar.indicator.weight = .custom(value: 0.0)
        self.bar.layout.contentMode = .fit
        self.bar.buttons.customize { (button) in
            button.font = .sofiaProSemiBold(16)
            button.tintColor = .charcoal()
            button.selectedTintColor = .black
            button.roundCorners(.topLeftTopRight, radius: 21)
            switch button.selectionState {
            case .unselected:
                button.backgroundColor = .lightGrey
            case .selected:
                button.backgroundColor = .white
            case .partial:
                button.backgroundColor = .white
            }
        }
        self.addBar(bar, dataSource: self, at: .custom(view: self.customContainer, layout: { (bar) in
            bar.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                bar.leadingAnchor.constraint(equalTo: self.customContainer.leadingAnchor),
                bar.trailingAnchor.constraint(equalTo: self.customContainer.trailingAnchor),
                bar.topAnchor.constraint(equalTo: self.customContainer.topAnchor),
                bar.bottomAnchor.constraint(equalTo: self.customContainer.bottomAnchor)
            ])
        }))

    }

**Comment by sugitatestblue** [comment]
@Gurungboi 
resolved?

**Comment by sugitatestblue** [comment]
How change color when button change state ? #486
