### ISSUE TITLE
setting png Image as BarItem doesn't work

### ISSUE THREAD

**Issue by BellaGuala** [uias/Tabman#516]
I'm trying to set a png Image as a tabBar Item as shown below but it doesn't show the image. 
I tried with or without the rendering mode method but nothing changes.

public func barItem(for bar: TMBar, at index: Int) -> TMBarItemable {
        
        return TMBarItem(image: #imageLiteral(resourceName: "like").withRenderingMode(.alwaysTemplate))
    }

**Comment by msaps** [comment]
@BellaGuala can you try debugging your view hierarchy to see whether the images are being shown in the bar and are just not visible (due to color etc)?

**Comment by BellaGuala** [comment]
@msaps I actually solved it it was only a matter of color settings, anyway thanks for the feedback!
