### ISSUE TITLE
Pod update

### ISSUE THREAD

**Issue by shitoexe** [uias/Tabman#52]
Could you update podspec and set Pageboy dependency version as 1.0.1. You have fixed retain cycle in both of them but Tabman uses old version of Pageboy

**Comment by msaps** [comment]
@shitoexe yeah sorry I noticed this last night, just after pushing 0.4.5! 😢 Released [0.4.6](https://github.com/uias/Tabman/releases/tag/0.4.6) this morning which has the latest updates for `Tabman` and `Pageboy`.
