### ISSUE TITLE
Cannot get Tabman to build from master

### ISSUE THREAD

**Issue by mergesort** [uias/Tabman#531]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I've tried running `carthage bootstrap --platform ios` and `carthage update`, but both of them lead to this log/error.

```
*** Fetching SnapKit
*** Fetching Pageboy
*** Fetching Randient
*** Fetching BulletinBoard
*** Fetching ios-snapshot-test-case
*** Checking out BulletinBoard at "3.0.0"
*** Checking out ios-snapshot-test-case at "4.0.1"
*** Checking out Randient at "1.3.1"
*** Checking out Pageboy at "3.6.1"
*** Checking out SnapKit at "4.2.0"
*** xcodebuild output can be found in /var/folders/6f/33x2jwhd4p34v3d4vgqvvvz40000gn/T/carthage-xcodebuild.MY7EXk.log
*** Building scheme "FBSnapshotTestCase iOS" in FBSnapshotTestCase.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/mergesort/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/ios-snapshot-test-case/4.0.1/Build/Intermediates.noindex/ArchiveIntermediates/FBSnapshotTestCase\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/FBSnapshotTestCase.framework/FBSnapshotTestCase /Users/mergesort/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/ios-snapshot-test-case/4.0.1/Build/Products/Release-iphonesimulator/FBSnapshotTestCase.framework/FBSnapshotTestCase -output /Users/mergesort/Desktop/Tabman/Carthage/Build/iOS/FBSnapshotTestCase.framework/FBSnapshotTestCase

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6f/33x2jwhd4p34v3d4vgqvvvz40000gn/T/carthage-xcodebuild.MY7EXk.log
```

### Other useful things

I tried both pulling down the latest master in a zip and cloning, neither of which seemed to correct the issue. I also tried running both the Example xcodeproj and the xcworkspace at the root, but both of them also didn't have the Tabman framework built, as expected.

Please let me know if there's any more information I can provide, or if I can be helpful in any other way.

Thanks a lot!

**Comment by msaps** [comment]
@mergesort looks like this will be related to this Carthage issue with Xcode 12: Carthage/Carthage#3019...

I'm hoping to be able to give Tabman some attention shortly and remove the need for Carthage / simplify the Example project etc.

**Comment by mergesort** [comment]
@msaps Ah, that makes sense. I do agree that removing the need for Carthage is a good idea, but I ended up building a small example project this week so I could play with it myself, so no rush on that.

Thanks again for the hard work!

**Comment by msaps** [comment]
@mergesort updated Example project to use Swift PM so building `master` should be good now 👍
