### ISSUE TITLE
'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0

### ISSUE THREAD

**Issue by ahmedsafadii** [uias/Tabman#532]
'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use UIScrollView's contentInsetAdjustmentBehavior instead

    
```
    private func _enable(for viewController: UIViewController?) {
        _isEnabled = true
        viewController?.automaticallyAdjustsScrollViewInsets = false
    }
```

**Comment by msaps** [comment]
@ahmedsafadii currently we provide support for iOS 9 and above, which is why we still have to use this property. Hopefully will be updating the minimum deployment target to 11 shortly 👍
