### ISSUE TITLE
set the tab titles to fill the entire width of the phone screen

### ISSUE THREAD

**Issue by javadmahmoodi** [uias/Tabman#534]
Hello.  How can I set the tab titles to fill the entire width of the phone screen and the tab titles to be read completely.  I am unable to do this and I ask you for help.  Thank you
🙏🏻🙏🏻🌹

![image](https://user-images.githubusercontent.com/11042152/93686305-9b0ed600-faca-11ea-92e4-c489746569b0.jpeg)

**Comment by msaps** [comment]
@javadmahmoodi you can use the `contentMode` on `TMBarLayout` to achieve this...

```
bar.layout.contentMode = .fit
```

![Simulator Screen Shot - iPhone 12 Pro - 2020-11-12 at 08 09 19](https://user-images.githubusercontent.com/3515448/98907009-6877cd00-24be-11eb-8506-0910922c37cc.png)
