### ISSUE TITLE
Switch to the next tab programatically

### ISSUE THREAD

**Issue by phracek** [uias/Tabman#535]
First of all, thanks for the Tabman.

I have an app and I would like to switch to the next tab as soon as the user clicks on a button.

Any idea, how to do it?

**Comment by msaps** [comment]
@phracek sure! You can do this by calling functions on the `TabmanViewController` (which inherits from `PageboyViewController`) - take a look at the docs here: [Navigation](https://github.com/uias/Pageboy#navigation)
