### ISSUE TITLE
iPhone X bottom margin how to FILL

### ISSUE THREAD

**Issue by alyfreym** [uias/Tabman#550]
### New Issue Checklist

- [+] Updated Tabman to the latest version
- [+] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/Troubleshooting.md)
- [+] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I add bottom bar using this code 

`let bar                    = TMBar.TabBar()`
`bar.backgroundView.style   = .blur(style: .dark)`
`bar.layout.transitionStyle = .none`
`addBar(bar, dataSource: self, at: .bottom)`

![IMG_0360](https://user-images.githubusercontent.com/29518174/101727691-c9eb8580-3ad6-11eb-8f65-fdca9f789546.jpg)

You can see that it does not fill bottom extra margin. how to make it fill?

**Comment by msaps** [comment]
@alyfreym try using the `TMSystemBar` wrapper (by default the bar background doesn’t extend beyond the safe area)

```
addBar(bar.systemBar(), dataSource: self, at: .bottom)
```

**Comment by alyfreym** [comment]
Thanks it works.
