### ISSUE TITLE
how to change the bar height?

### ISSUE THREAD

**Issue by AgungLaksana** [uias/Tabman#559]
Hi,

I want to change the height of the bar. I have tried to find in the issues section, but I have no solution

from here https://github.com/uias/Tabman/issues/440 
it is said by changing the constraint, but how to do that?

or from here https://github.com/uias/Tabman/issues/480
it is said that the bar will autosize itself via its required intrinsicContentSize

I try to change the text font size to be 8, like this

        bar.buttons.customize { (button) in
            button.font = UIFont(name: "HelveticaNeue-Thin", size: 8)!
        }

but the height of bar (that brown bar) still the same like this in this image: https://i.stack.imgur.com/2Ate0.png

I expect the bar height will be smaller if change the font size to be smaller (8)

so how to change the bar height?

**Comment by msaps** [comment]
@AgungLaksana looks as though this is related to the default `contentInset` values that are applied on a `TMLabelBarButton` which sets `top` and `bottom` insets of `12.0`.

Try this:
```swift
bar.buttons.customize { (button) in
    button.font = UIFont(name: "HelveticaNeue-Thin", size: 8)!
    button.contentInset = .zero
}
```

<img width="568" alt="Screenshot 2021-03-08 at 08 46 35" src="https://user-images.githubusercontent.com/3515448/110290213-cccd1800-7fea-11eb-85c4-d49f29191aa7.png">
