### ISSUE TITLE
is it possible to embed the tabman to an UIView?

### ISSUE THREAD

**Issue by hanxianlong** [uias/Tabman#56]
Hi, is it possible to embed the Tabman into a UIView, which is the element of the UIViewController?
 if possible , how can I do that?

**Comment by msaps** [comment]
@hanxianlong this is certainly possible, via the `embedBar()` function that is available in `TabmanViewController`. Please see the Advanced Customisation documentation [here](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md#embedding-tabmanbar-in-an-external-view)

**Comment by hanxianlong** [comment]
@msaps thank you for your reply!
I tried your solution with a simple project,  create a viewcontroller(let's call it the Main View Controller), extends TabmanViewController and implements PageboyViewControllerDataSource.
the Tabman will show two viewControllers, which are LoginPageViewController and RegisterPageViewConroller.

On the storyboard of the Main View Controller , I placed two UIView, the first is header ui view, will show some images or other controls in the future, and the other one is the container of the tabman,  container of tabman will show the two pages, 


 and then call the method:
   self.embedBar(inView: self.tabmanContainer)


here is the code of Main ViewContorller:
`
import UIKit
import Tabman
import Pageboy

class ViewController: TabmanViewController,PageboyViewControllerDataSource{

    @IBOutlet weak var tabmanContainer: UIView!
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.dataSource = self
        self.embedBar(inView: self.tabmanContainer)
        
        self.bar.appearance = TabmanBar.Appearance({ (appearance) in
            // customise appearance here
//            appearance.indicator.isProgressive = true
            
            appearance.style.bottomSeparatorColor = UIColor.orange
            appearance.state.selectedColor = UIColor.brown
            appearance.indicator.color = UIColor.red
        })
    }
    
    func viewControllers(forPageboyViewController pageboyViewController: PageboyViewController) -> [UIViewController]? {
        
        let loginVC = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "login")
        let registerVC = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "register")
        
        let viewControllers = [loginVC, registerVC]
        
        // configure the bar
        self.bar.items = [TabmanBarItem(title: "Login"),
                          TabmanBarItem(title: "Register")]
        
        return viewControllers
    }
    
    func defaultPageIndex(forPageboyViewController pageboyViewController: PageboyViewController) -> PageboyViewController.PageIndex? {
        // use default index
        return nil
    }

}

`

but when I run the project, it doesn't work as what I want.  could you please help me out?
this is what I want(UI):
https://github.com/hanxianlong/tabmanTest/blob/master/ui.jpg

this is the project of my project, 
https://github.com/hanxianlong/tabmanTest

Many thanks for your kind and warm help!

**Comment by msaps** [comment]
@hanxianlong I've found the problem, and created a PR into your repo with the fix.

Basically, the view you were embedding the `TabmanBar` into was constrained to be pinned to the bottom of the view controller. When you embed the bar, it pins itself to all 4 edges of the superview, which resulted in the stretched appearance you could see. To rectify this, I've updated the bottom pin constraint to be removed at runtime, which allows the bar and the embed view to autosize themselves.

Let me know if you need any more help!

**Comment by hanxianlong** [comment]
@msaps Thank you so much for your quick reply 👍 
It seems to solve the problem when you help me last time. However, I found anther problem, which is when I embed a UITableViewController into the tabman, it doesn't works as I expected. 
as you can see the image:
https://github.com/hanxianlong/tabmanTest/blob/master/uitableview_problem.png

This label is the first cell of the 
UITableViewController, and Label2-Label6 are also
the cells of the UITableViewController, but they are covered by the Slider label.

My expected result is: UITableViewController(and also the other
two viewcontrollers) equal the height to the 
_tabmanContainer_, not the the viewController.view, and also the Slider View should not response to the Swipe Guesture, which means, when I swiped on the SliderView, the three pages should not switched to another.

I pushed the demostration to my project: https://github.com/hanxianlong/tabmanTest 
could you please checkout and run the project and see what the problem is, Many Many Thanks again for your help.

**Comment by msaps** [comment]
@hanxianlong this is an issue with the `contentInset` of the `UITableView`, which needs to be set so that the content appears underneath the header view and `TabmanBar`. There is an open issue #42 which discusses how to access the appropriate variables for calculating this inset.

I am also currently adding behaviour so that Tabman will automatically handle this in the future, open as an issue #43

**Comment by hanxianlong** [comment]
@msaps I got i, thank you sooooo much, hope new version 👍

**Comment by hanxianlong** [comment]
@msaps  I got it, thank you sooooo much, hope new version 👍
