### ISSUE TITLE
Add a selected image state for TMTabItemBarButton

### ISSUE THREAD

**Issue by divyeshmakwana96** [uias/Tabman#579]
### New Issue Checklist

- [✓] Updated Tabman to the latest version
- [✓] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [✓] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

It would be great to have a built in support for a different image on selected state. Possibly two different `UIImageView`s stacked on each other and update alpha based on the progress.

### Other useful things
N/A

**Comment by divyeshmakwana96** [comment]
Please checkout PR #580. I also added a fix for auto layout warnings in `TMTabItemBarButton`.

**Comment by msaps** [comment]
Available in 2.12.0 🎉
