### ISSUE TITLE
Type 'TabmanViewController' does not conform to protocol 'PageboyViewControllerDelegate'

### ISSUE THREAD

**Issue by GabrielAraujo** [uias/Tabman#58]
After installing trough pod file this issue started to appear a long with 'atIndex' is deprecated: Use at(index: Int) in TabmanViewController.swift

Using Pageboy (1.0.4)
Using Tabman (0.4.7)

**Comment by msaps** [comment]
@GabrielAraujo sorry about that, recently did some API changes to `Pageboy` and `Tabman` wasn't tied down correctly to the appropriate version. 

This is now rectified in [0.4.8](https://github.com/uias/Tabman/releases/tag/0.4.8), so please update. I've made the necessary Pods changes to ensure this doesn't happen again. Cheers!
