### ISSUE TITLE
When swiped through pages, tab goes under bar view.

### ISSUE THREAD

**Issue by hakan-toptal** [uias/Tabman#590]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
When swiped through pages, `viewController` goes under `barView`.
However when tapped on `barView`, there is no layout issue.

### Testing
1. Swipe right or left on pager
2. Observe tableView goes under barView.
3. Often tableView finds correct place but after a delay.

### Other useful things
https://user-images.githubusercontent.com/92502233/141703428-dfe5afac-01f1-4f44-8c6b-f5080c1f7e45.mov

**Comment by MussaCharles** [comment]
Hi, @hakan-toptal did you fix the mentioned issue?

**Comment by hakan-toptal** [comment]
> Hi, @hakan-toptal did you fix the mentioned issue?

Yes, I have resolved the issue as following:

```
func viewController(for pageboyViewController: PageboyViewController, at index: PageboyViewController.PageIndex) -> UIViewController? {
    pageboyViewController.view.layoutIfNeeded()
    pageboyViewController.view.setNeedsLayout()
    let myViewController = MyViewController()
    myViewController.additionalSafeAreaInsets.top = barView.bounds.height
    return myViewController
  }
```
