### ISSUE TITLE
Unable to install Tabman 2.12.0 from CocoaPods

### ISSUE THREAD

**Issue by betat** [uias/Tabman#593]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I can't install Tabman `2.12.0` from CocoaPods.

I specified `2.12.0` in Podfile 
```ruby
  pod 'Tabman', '2.12.0'
```
and ran 
```sh
$ bundle exec pod install --repo-update
```
and got the following results

```
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Tabman":
  In Podfile:
    Tabman (= 2.12.0)

None of your spec sources contain a spec satisfying the dependency: `Tabman (= 2.12.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

### Other useful things

In the [Tabman.podspec](https://github.com/uias/Tabman/blob/main/Tabman.podspec#L11) file, I confirmed that it is `2.12.0`.

However, when I checked at the [Tabman on CocoaPods.org](https://cocoapods.org/pods/Tabman), Tabman was still at `2.11.x`.

Do you have any solutions? Thank you.

**Comment by anshul-infobeans** [comment]
Same for me:
`Update all pods
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Tabman":
  In Podfile:
    Tabman (~> 2.12.0)

None of your spec sources contain a spec satisfying the dependency: `Tabman (~> 2.12.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by betat** [comment]
@anshul-infobeans 

I solved this issue by writing the following in `Podfile`

```ruby
pod 'Tabman', :git => 'https://github.com/uias/Tabman.git', :tag => '2.12.0'
```

**Comment by msaps** [comment]
@betat apologies - had an issue with the token. Should be solved now 👍 

<img width="1584" alt="Screenshot 2022-03-16 at 08 24 16 1" src="https://user-images.githubusercontent.com/3515448/158537737-a4fab7e3-0b82-4ceb-80db-c20f1375ee56.png">
