### ISSUE TITLE
It is possible set  current page (selectedIndex ) programmatically?

### ISSUE THREAD

**Issue by maestrovsmaster** [uias/Tabman#599]
### New Issue Checklist

- [ ] Updated Tabman to the latest version
- [ ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [ ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

**Comment by sugitatestblue** [comment]
Yes it is possible.
