### ISSUE TITLE
[Feature] non transition style

### ISSUE THREAD

**Issue by sugitatestblue** [uias/Tabman#600]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [o] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [o] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Transition should set only them.
I don't want any animation.

```
        public enum Style: String {
            case push
            case fade
            case moveIn
            case reveal
        }
```

### Other useful things

add none
```
        public enum Style: String {
            case none
            case push
            case fade
            case moveIn
            case reveal
        }

**Comment by msaps** [comment]
@sugitatestblue calling `scrollToPage({page}, animated: false}` will result in a non-animated transition
