### ISSUE TITLE
Xcode 14 - Carthage build failing

### ISSUE THREAD

**Issue by BlueVirusX** [uias/Tabman#602]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Starting with Xcode 14 I am no longer able to build the Tabman framework via Carthage.
I'm guessing that the problem is that the current minimum deployment platform is iOS 9 for Pageboy and Tabman, but Xcode 14 supports only iOS 11+

**Comment by msaps** [comment]
@BlueVirusX this should now be resolved as of [3.0.0](https://github.com/uias/Tabman/releases/tag/3.0.0) 👍
