### ISSUE TITLE
Tab's background view style isn't displayed in 3.0.0 

### ISSUE THREAD

**Issue by martin-muller** [uias/Tabman#605]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

When updating Tabman to 3.0.0 I've noticed that the background view of a tab isn't visible in our setup. Boiled down our config to this [sample project](https://github.com/uias/Tabman/files/9933569/tabman3.zip). Did a little bit of debugging and seems to me like the `backgroundView` doesn't size itself, width and height staying at 0. Happy to look into this further if needed. 

Thank you for maintaining such a great library!

### Other useful things

| 2.13.0 | 3.0.0 |
|---|---|
| <img src="https://user-images.githubusercontent.com/44968677/199850941-8a7119e8-233d-4893-acf3-b60d1955e940.mp4" width="350"> | <img src="https://user-images.githubusercontent.com/44968677/199851039-b175339e-b702-4cb8-ab25-00f86fe160e9.mp4" width="350"> |

**Comment by msaps** [comment]
@martin-muller should be resolved in [3.0.1](https://github.com/uias/Tabman/releases/tag/3.0.1) 👍
