### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by mobru** [uias/Tabman#625]
Hi there,

As of May 1st 2024, Apple requires third-party SDKs to add a Privacy Manifest file.
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Are there plans to include a Privacy Manifest?

**Comment by msaps** [comment]
@mobru not sure Tabman needs to have a privacy manifest? It doesn't use any of the specified 'required reason' APIs (such as UserDefaults) and also as far as I can tell only the SDK's listed here are required to have manifests: https://developer.apple.com/support/third-party-SDK-requirements/

Or am I wrong? 😅

**Comment by msaps** [comment]
Added one anyway to both Pageboy and Tabman with #628

**Comment by mobru** [comment]
> @mobru not sure Tabman needs to have a privacy manifest? It doesn't use any of the specified 'required reason' APIs (such as UserDefaults) and also as far as I can tell only the SDK's listed here are required to have manifests: https://developer.apple.com/support/third-party-SDK-requirements/
> 
> Or am I wrong? 😅

Honestly... no idea. Apple is (as always) vague on what is actually required (by whom) and what isn't. I'd say that it could be argued that *every* SDK needs a Privacy Manifest, but also ... maybe not? I guess we'll find out after May 1st. 

Anyhow - thank you very much for providing one (even if it isn't needed)!
