### ISSUE TITLE
Upload Privacy Manifest

### ISSUE THREAD

**Issue by sagarthecoder** [uias/Tabman#626]
Apple says "**Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect.**"

Please add privacy policy otherwise we couldn't use this library.

**Comment by msaps** [comment]
@sagarthecoder not sure Tabman needs to have a privacy manifest? It doesn't use any of the specified 'required reason' APIs (such as UserDefaults) and also as far as I can tell only the SDK's listed here are required to have manifests: https://developer.apple.com/support/third-party-SDK-requirements/

Or am I wrong? 😅

**Comment by msaps** [comment]
Added one anyway to both Pageboy and Tabman with #628
