### ISSUE TITLE
Explain Swift 5.10 requirements

### ISSUE THREAD

**Issue by kapitoshka438** [uias/Tabman#629]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

Tabman 3.1.0 requires Swift 5.10. Are you sure this was necessary?
`swift-tools-version` in Package.swift should define minimum supported Swift version not the latest one. Otherwise it doesn't work in Xcode below 15.3.

### Other useful things

`error: Dependencies could not be resolved because 'tabman' 3.1.0 contains incompatible tools version (5.10.0) and root depends on 'tabman' 3.1.0.`

**Comment by kapitoshka438** [comment]
Same for Pageboy

**Comment by msaps** [comment]
@kapitoshka438 yep good point - just updated it blindly, apologies! Downgraded back to 5.7 for both Tabman and Pageboy (meaning Xcode 14 is the minimum requirement which should be fine)
