### ISSUE TITLE
pageViewController is nil when delegate is set

### ISSUE THREAD

**Issue by GabrielAraujo** [uias/Tabman#63]
Hello,

I have followed the instructions at the main page, but once I set the dataSource in the viewDidLoad the self.reloadPages() in PageboyViewControllerDataSource is executed but it is trying to reference the pageViewController which is nil at that moment.

Bug line: 27 of PageboyControllerManagement.swift
Pods: Tabman 0.4.8, Pageboy 1.0.4, PureLayout 3.0.2

TabmanViewController :

    class TimeLockViewController: TabmanViewController, PageboyViewControllerDataSource  {

    var mainView = TimeLockView()
    var child:Children!
    
    //Rx
    let disposeBag = DisposeBag() // Bag of disposables to release thvarwhen view is being deallocate
    
    //Mvvm
    
    init(child: Children) {
        super.init(nibName: nil, bundle: nil)
        self.child = child
        self.setupNavigation()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func loadView() {
        self.view = mainView
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.setupNavigation()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.dataSource = self
        self.embedBar(inView: self.mainView)
        
        self.setupMvvm()
        self.setupRx()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    fileprivate func setupNavigation() {
        self.navigationItem.title = child.name ?? ""
    }
    
    fileprivate func setupMvvm(){
        
    }
    
    fileprivate func setupRx(){
        
    }
    
    func viewControllers(forPageboyViewController pageboyViewController: PageboyViewController) -> [UIViewController]? {
        // return array of view controllers
        let viewControllers = [UIViewController(), UIViewController()]
        
        // configure the bar
        self.bar.items = [TabmanBarItem(title: "Page 1"),
                          TabmanBarItem(title: "Page 2")]
        
        return viewControllers
    }
    
    func defaultPageIndex(forPageboyViewController pageboyViewController: PageboyViewController) -> PageboyViewController.PageIndex? {
        // use default index
        return nil
    }
    
    }

**Comment by msaps** [comment]
@GabrielAraujo this looks like a bit of a lifecycle issue. The components for a `PageboyViewController` are currently loaded in `loadView`; with you using a custom view in the above, `super` is not called so the components are never initialised. 

It doesn't make much sense to have the initialisation code in `loadView`, so I'll raise an issue and hopefully get this sorted today.

**Comment by msaps** [comment]
@GabrielAraujo this is now resolved in Pageboy and also Tabman, but I'm not sure when I'll get it into a release, as there are a few things I'm currently working on.

Can see this is quite a blocker so you could get access to the fix by using the `develop` branch as your target. This is obviously bleeding edge, so I can't promise there won't be any breakers, but please feel free to raise any issues on anything you find if you do so.

Add this to your Podfile:
```ruby
pod 'Tabman', :git => 'https://github.com/uias/Tabman', :branch => 'develop'
pod 'Pageboy', :git => 'https://github.com/uias/Pageboy', :branch => 'develop'
```

The next stable releases should be along shortly. 😃

**Comment by GabrielAraujo** [comment]
Thanks for the change..

In this controller I don't need to use a custom view. Sorry about that =/

I will use the default branch and remove the custom view so it should work normally.

Thanks for the help
