### ISSUE TITLE
Error compiling develop using Carthage

### ISSUE THREAD

**Issue by robcecil** [uias/Tabman#67]
Not sure where this currently sits but I am getting the error:

```
Undefined symbols for architecture x86_64:
  "direct field offset for Tabman.TabmanViewController.(bar.storage in _57F68DA9D23EDB616EF841D0392909A0) : Tabman.TabmanBarConfig?", referenced from:
      Tabman.TabmanViewController.bar.setter : Tabman.TabmanBarConfig in NavButtonBarViewController.o
      Tabman.TabmanViewController.(bar.materializeForSet : Tabman.TabmanBarConfig).(closure #1) in NavButtonBarViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When I add the line

`github "uias/Tabman" "develop"`

To my Cartfile

Thanks

**Comment by msaps** [comment]
@robcecil just had a quick look into this, apparently from what I've read elsewhere it seems to be an issue with certain versions of Xcode and Swift 3.X Module Optimization? 

Take a look here: https://github.com/ArtSabintsev/Siren/issues/125

Are you using a version of Xcode less than 8.3.X by any chance?

**Comment by robcecil** [comment]
So people are removing lazy vars from frameworks? For shame!

**Comment by msaps** [comment]
@robcecil looks like that was the work around.. 

Have you tried running on Xcode 8.3.2 and seeing if that fixes the issue?

**Comment by robcecil** [comment]
@msaps  I currently cannot upgrade to 8.3.2 for issues related to other dependencies.

**Comment by msaps** [comment]
@robcecil  Going to close this for now as you've manually integrated, but feel free to re-open if you get to using Xcode 8.3.X and the issue still persists 👍
