### ISSUE TITLE
Method for specifying the location of the bar.

### ISSUE THREAD

**Issue by eman6576** [uias/Tabman#70]
Hello,

I have a question about customizing the location of the bar. Is there a way to specify the location of where the bar is going to be placed? For example, in my view, I have a search bar that is bellow the navigation bar. I would then want to position the tab bar bellow the search bar.

**Comment by eman6576** [comment]
After reading the advanced documentation, I saw this method `embedBar`. It gave me the idea to create an auxiliary view in interface builder and place it bellow the search bar. Then calling `embedBar` and using the auxiliary view did the trick. 🎉

**Comment by msaps** [comment]
Glad you got it sorted! 👍
