### ISSUE TITLE
Is it possible to make indicator sticky? (question)

### ISSUE THREAD

**Issue by iSaadSalman** [uias/Tabman#71]
I would like to make the indicator sticky and I want the anchor point for the active tab to be always the center.

Is this possible with Tabman?

Thanks

**Comment by msaps** [comment]
Hi,

This isn't possible with the bar styles that are currently available, but is certainly something that could be added with relative ease. Can raise it as an enhancement? Not sure on a current ETA for getting it in myself though.

Cheers 😄

**Comment by msaps** [comment]
This is now available via the `itemDistribution` property on `TabmanBar.Appearance.Layout`. Simply set it to `centered` when using the `scrollingButtonBar` style `TabmanBar`.

Available from [0.5.1](https://github.com/uias/Tabman/releases/tag/0.5.1) 😄

**Comment by electic** [comment]
To add to this, how would you make it centered, regardless of selected item.
