### ISSUE TITLE
Specify Font for not selected page

### ISSUE THREAD

**Issue by eman6576** [uias/Tabman#72]
Hello,

I was wondering for the `Appearance` proxy if there is a way to specify a font for the tab that isn't selected? Thanks

**Comment by msaps** [comment]
Hi,

Unfortunately this isn't currently possible in Tabman, you can only change the font for the entire set of bar items. The reason for this is that there is no nice way to progressively interpolate between 2 fonts, so it wouldn't provide optimal support for any transition between unselected/selected states.

For this reason I elected to only allow changing the font for all bar items. 

Cheers! 👍

**Comment by eman6576** [comment]
Oh ok, Is there also a way to control how the child views are laid out? If we use an externally view for the tabbar, is there a way to place the content bellow it?

**Comment by eman6576** [comment]
I was able to figure that out by changing the content inset of the tableview i had.

**Comment by msaps** [comment]
Glad you figured it out, please check out #43 for further progress on insetting. 👍
