### ISSUE TITLE
Tabman bar not respecting navigation bar added to UIViewController in Interface Builder.

### ISSUE THREAD

**Issue by SolsmaHawk** [uias/Tabman#75]
I've added a navigation bar manually to view controller in interface builder and Tabman bar is not showing up below it - it's showing up on top of it. Is there a way to manually set the height of the bar from the top of the screen?

**Comment by msaps** [comment]
@SolsmaHawk the automatic insetting behaviour will only work if the `UINavigationBar` is added in such a way that the `layoutMargins` on the view controller are updated. 

Has your navigation bar been manually added by yourself? I.e. not come as part of a `UINavigationController`?

**Comment by SolsmaHawk** [comment]
Yes, the navigation bar was added manually by me and not part of a `UINavigationController`. I think the `embedBar()` method solves my problem though as I can just add a subview below my navigation bar and add it there; I was not aware of that method. Thanks!

**Comment by msaps** [comment]
No worries! Let me know if you have any more questions 🙂
