### ISSUE TITLE
Tabman localization 

### ISSUE THREAD

**Issue by fad12** [uias/Tabman#77]
after applying localization to my project when I switch language to arabic (right to left) the bar is jammed and not responding

**Comment by msaps** [comment]
@fad12 Tabman doesn't currently have any specific support for Right-to-left languages, but it definitely should! So I'll try and get support for this added in the near future 👍

**Comment by almatri** [comment]
Same issue , I hope it can be solved ASAP

**Comment by msaps** [comment]
This is now fixed and available in [`0.6.2`](https://github.com/uias/Tabman/releases/tag/0.6.2) 🎉

**Comment by almatri** [comment]
Thanks a lot Merrick
