### ISSUE TITLE
PageViewController scrollView embed

### ISSUE THREAD

**Issue by AlexZd** [uias/Tabman#81]
Hi, is there way to embed `pageViewController` ? I found a way how to embed `tabBar`, but can't figure out how to move/embed `pageViewController`

What I'm trying to achieve:
---Tabbar container---
---My custom view (not scrollable)---
---Pages---

Also other screen has
---Custom view---
---Tabbar container---
---Pages---
This is one is working fine, but my pages are going under Custom view and tabbar container, I saw that there is way to have some inset (still trying), but it would be much easier to have ability to embed `pageViewController` to any view as tabbar.

**Comment by msaps** [comment]
Hi,

You can embed the bar component easily in an external view via the `embedBar()` functions in `TabmanViewController`. Not quite sure on what you're trying to achieve hierarchy wise, but could it be done with child view controllers? I.e. The `TabmanViewController` would be a child VC in a subview in your parent view controller? Then embed the bar in an external view? 

I think this could give you what you want?

**Comment by AlexZd** [comment]
Yes, it is easy to embed tabBar and I was able to do this with child VC.
But it can be easier to have a method `embedPage` to reduce some code.

This was just curious question :)
You can close if you feel that will not give any profit)

**Comment by msaps** [comment]
I think this is probably best to keep external of Tabman, as it really should be the parent view controller doing the embedding, rather than something within the component reaching out and doing it 👍

**Comment by Ezimetjan** [comment]
**nnnxhdnfn**`ndndnfb```
~~~~
````

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
