### ISSUE TITLE
Remove the line under the bar

### ISSUE THREAD

**Issue by stealdre** [uias/Tabman#82]
Hi,

Like I said in the title, I want to remove this little line under the bar of the .bar style. How is it possible? Thanks!

**Comment by msaps** [comment]
Hi, 

Do you mean the background that spans the entire width of the bar underneath the indicator? If so, simply set a custom appearance configuration with `appearance.style.background = .clear`. 

Resulting in: 
![simulator screen shot 9 jun 2017 11 43 41](https://user-images.githubusercontent.com/3515448/26972259-ee1869ba-4d08-11e7-92ae-80218ef74953.png)

**Comment by stealdre** [comment]
thanks m8!
