### ISSUE TITLE
useRoundedCorners not working

### ISSUE THREAD

**Issue by AlexZd** [uias/Tabman#85]
Hi, seems `useRoundedCorners` property doesn't work.

I checked file `TabmanBar.swif`, line 288 `update(forAppearance:defaultAppearance:)` method there is no assigning

and 

I checked `TabmanLineIndicator.swift` which is internal class, line 50 contains
`TabmanBar.Appearance.defaultAppearance.indicator.useRoundedCorners ?? false`, so basically you are taking value from `defaultAppearance` 

maybe I got your code not correctly, but property `useRoundedCorners` for indicator is not working for me

**Comment by msaps** [comment]
Thanks for pointing this out, fixed it and I'll get it in the next release 👍

**Comment by msaps** [comment]
This is now fixed in [0.6.0](https://github.com/uias/Tabman/releases/tag/0.6.0) 🎉
