### ISSUE TITLE
open minimumItemWidth

### ISSUE THREAD

**Issue by AlexZd** [uias/Tabman#86]
Hi,

I'm using `scrollingButtonBar` style, I found that you are using `TabmanScrollingButtonBar.swift` for this. I'm happy with that behavior, but only thing I need is to set  `minimumItemWidth`, now you have `internal` default value as 44.

I think it would be nice to have such property under `layout` property of bar `Appearance`

Thanks!

**Comment by msaps** [comment]
Yep, agree it would be useful! 👍

**Comment by msaps** [comment]
This is now available as of [0.6.1](https://github.com/uias/Tabman/releases/tag/0.6.1). 🎉
