### ISSUE TITLE
Close button on tab

### ISSUE THREAD

**Issue by kyzmitch** [uias/Tabman#87]
Is it possible to enable/configure appearance to have close buttons on each tab?

**Comment by msaps** [comment]
Not by default, but you can create a custom `TabmanBar` to achieve something similar.. Check out the Advanced Customisation docs here: [Advanced Customisation](https://github.com/uias/Tabman/blob/master/Docs/ADVANCED_CUSTOMISATION.md).

**Comment by kyzmitch** [comment]
Thanks for reply
