### ISSUE TITLE
Titel labels not using same font?

### ISSUE THREAD

**Issue by Lasse-Hansen** [uias/Tabman#91]
Hi.

Am i doing something wrong or is this an error?

Currently im setting the font to be UIFont.systemFont(ofSize: 16.0), but they differ in sizes - see screenshot.

![screen shot 2017-06-14 at 08 39 00](https://user-images.githubusercontent.com/4170317/27118811-57380e96-50dd-11e7-9bce-fcf9b4bcc20c.png)

Style is buttonbar - let me know if you need more info :)

**Comment by msaps** [comment]
Looks like a bug, I'll check it out and have a look 👍

**Comment by msaps** [comment]
This should be resolved in [`0.6.2`](https://github.com/uias/Tabman/releases/tag/0.6.2) 🎉
