### ISSUE TITLE
Example code not working 

### ISSUE THREAD

**Issue by bilawal-liaqat** [uias/Tabman#92]
Dependencies frameworks are missing in example code. can you please create example code with all required framework so we can test it before integrating in our real-time project. 

Thanks

**Comment by msaps** [comment]
Hi,

Have you run `carthage bootstrap --platform ios` when you cloned the repo? This should integrate the dependencies correctly for the example project.

**Comment by RajChanchal** [comment]
I tried installing through pod, but it didn't work. It says: User of undeclared type PageboyViewControllerDataSource
