### ISSUE TITLE
Installing POD error

### ISSUE THREAD

**Issue by krishnameena** [uias/Tabman#98]
I am trying to install it by adding `pod 'Tabman'` but getting following error : 

[!] There are only pre-release versions available satisfying the following requirements:

	'Tabman', '>= 0'

You should explicitly specify the version in order to install a pre-release version

**Comment by msaps** [comment]
Hi,

What does your `Podfile` entry look like? Also try running `pod repo update` before running `pod install`. ☺️

**Comment by krishnameena** [comment]
My Podfile is following : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'QiKCircle-RoomDevice' do
pod 'Alamofire', '~> 4.4'
pod 'ObjectMapper', '~> 2.2'
pod 'AlamofireObjectMapper', '~> 4.0'
pod 'Cosmos', '~> 10.0'
pod 'SDWebImage', '~>3.8'
pod 'SlidingContainerViewController'
pod 'Tabman'
end
```
and I have tried `pod repo update` also but still facing same issue

**Comment by msaps** [comment]
@krishnameena ah, the issue is CocoaPods can't find a pod for Tabman that supports iOS 8. Current versions of Tabman only support iOS 9 and above.

There is currently an issue open for iOS 8 support #96. This is currently in progress and should be available in the very near future 👍

**Comment by krishnameena** [comment]
ok thanks
